// tasks/frontend-creative-tools-story-docs/solution/app/src/components/CommandPalette.tsx
import React, { useEffect, useRef, useState } from 'react';
import { Search } from 'lucide-react';
import { useStore } from '@nanostores/react';
import {
  scenesStore,
  filterStatusStore,
  searchQueryStore,
  viewModeStore,
  ViewMode
} from '../store';

interface Props {
  isOpen: boolean;
  onClose: () => void;
}

export function CommandPalette({ isOpen, onClose }: Props) {
  const dialogRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [query, setQuery] = useState('');

  useEffect(() => {
    if (isOpen) {
      // Small timeout to allow render before focusing
      setTimeout(() => {
        if (inputRef.current) inputRef.current.focus();
      }, 50);

      const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          e.stopPropagation();
          onClose();
        }
      };

      document.addEventListener('keydown', handleKeyDown, true);
      return () => document.removeEventListener('keydown', handleKeyDown, true);
    }
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const commands = [
    { id: 'view-tile', name: 'View: Tile Mode', action: () => viewModeStore.set('tile') },
    { id: 'view-list', name: 'View: List Mode', action: () => viewModeStore.set('list') },
    { id: 'view-slide', name: 'View: Slide Mode', action: () => viewModeStore.set('slide') },
    { id: 'view-canvas', name: 'View: Canvas Mode', action: () => viewModeStore.set('canvas') },
    { id: 'filter-all', name: 'Filter: Show All', action: () => filterStatusStore.set('all') },
    { id: 'filter-draft', name: 'Filter: Drafts', action: () => filterStatusStore.set('draft') },
    { id: 'filter-review', name: 'Filter: Review', action: () => filterStatusStore.set('review') },
    { id: 'filter-ready', name: 'Filter: Ready', action: () => filterStatusStore.set('ready') }
  ];

  const filteredCommands = commands.filter(c =>
    c.name.toLowerCase().includes(query.toLowerCase())
  );

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-start justify-center pt-24">
      <div
        ref={dialogRef}
        tabIndex={-1}
        className="w-full max-w-lg bg-white rounded-xl shadow-2xl flex flex-col focus:outline-none overflow-hidden"
        role="dialog"
        aria-modal="true"
        aria-label="Command Palette"
      >
        <div className="flex items-center px-4 border-b border-gray-200">
          <Search className="w-5 h-5 text-gray-400" />
          <input
            ref={inputRef}
            type="text"
            className="w-full py-4 px-3 outline-none text-lg bg-transparent"
            placeholder="Type a command or search..."
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            aria-label="Command palette input"
          />
        </div>

        <div className="max-h-96 overflow-y-auto">
          {filteredCommands.length > 0 ? (
            <ul className="p-2" role="listbox">
              {filteredCommands.map((cmd, i) => (
                <li key={cmd.id} role="option" aria-selected={i === 0}>
                  <button
                    className={`w-full text-left px-4 py-3 rounded-md text-sm transition-colors ${i === 0 ? 'bg-yellow-50 text-yellow-900' : 'hover:bg-gray-50'}`}
                    onClick={() => {
                      cmd.action();
                      onClose();
                    }}
                  >
                    {cmd.name}
                  </button>
                </li>
              ))}
            </ul>
          ) : (
            <div className="p-8 text-center text-gray-500">
              No commands found.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// tasks/frontend-productivity-clockcraft/solution/app/src/lib/components/CommandPalette.svelte
<script lang="ts">
	import { focusTrap } from "../utils/focusTrap";
	import { onMount, onDestroy } from 'svelte';
	import { uiStore, tagsStore } from '../stores';
	import { get } from 'svelte/store';

	let isOpen = $state(false);
	let query = $state('');
	let selectedIndex = $state(0);

	type Command = {
		id: string;
		title: string;
		action: () => void;
	};

	const baseCommands: Command[] = [
		{ id: 'focus-timer', title: 'Start timer focus', action: () => {
			isOpen = false;
			const timerInput = document.getElementById('timer-name');
			if (timerInput) timerInput.focus();
		}},
		{ id: 'add-manual', title: 'Add entry manually', action: () => { isOpen = false; uiStore.ui.update(s => ({...s, showManualForm: true})); setTimeout(() => { const el = document.getElementById('manual-name'); if (el) el.focus(); }, 50); } },
		{ id: 'view-history', title: 'View history', action: () => { isOpen = false; uiStore.toggleHistoryPanel(); } },
		{ id: 'export', title: 'Export session', action: () => { isOpen = false; uiStore.toggleExportDrawer(); } },
		{ id: 'import', title: 'Import session', action: () => { isOpen = false; uiStore.toggleExportDrawer(); } },
		{ id: 'filter-all', title: 'Filter: All', action: () => { isOpen = false; uiStore.setFilter('all'); } },
		{ id: 'filter-meaningful', title: 'Filter: Meaningful', action: () => { isOpen = false; uiStore.setFilter('meaningful'); } },
		{ id: 'filter-neutral', title: 'Filter: Neutral', action: () => { isOpen = false; uiStore.setFilter('neutral'); } },
		{ id: 'filter-draining', title: 'Filter: Draining', action: () => { isOpen = false; uiStore.setFilter('draining'); } },
	];

	let filteredCommands = $derived(() => {
		const tags = get(tagsStore.tags);
		const tagCommands = tags.map(t => ({
			id: `tag-${t}`,
			title: `Tag: ${t}`,
			action: () => {
				isOpen = false;
				uiStore.setSearch(t);
			}
		}));
		const allCommands = [...baseCommands, ...tagCommands];
		const q = query.toLowerCase();
		if (!q) return allCommands;
		return allCommands.filter(c => c.title.toLowerCase().includes(q));
	});

	function handleKeydown(e: KeyboardEvent) {
		if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
			e.preventDefault();
			isOpen = !isOpen;
			if (isOpen) {
				query = '';
				selectedIndex = 0;
				setTimeout(() => {
					const el = document.getElementById('palette-input');
					if (el) el.focus();
				}, 50);
			}
			return;
		}

		if (!isOpen) return;

		const commands = filteredCommands();
		if (e.key === 'Escape') {
			e.preventDefault();
			isOpen = false;
		} else if (e.key === 'ArrowDown') {
			e.preventDefault();
			selectedIndex = (selectedIndex + 1) % commands.length;
		} else if (e.key === 'ArrowUp') {
			e.preventDefault();
			selectedIndex = (selectedIndex - 1 + commands.length) % commands.length;
		} else if (e.key === 'Enter') {
			e.preventDefault();
			if (commands[selectedIndex]) {
				commands[selectedIndex].action();
			}
		}
	}

	onMount(() => {
		window.addEventListener('keydown', handleKeydown);
	});
	onDestroy(() => {
		window.removeEventListener('keydown', handleKeydown);
	});

	// Reset index when query changes
	$effect(() => {
		const _ = query;
		selectedIndex = 0;
	});
</script>

{#if isOpen}
<div class="fixed inset-0 bg-black/30 z-50 flex items-start justify-center pt-[10vh] p-4" role="presentation" onclick={() => isOpen = false}>
	<div
		class="bg-white radius-card w-full max-w-lg shadow-2xl overflow-hidden flex flex-col"
		onclick={(e) => e.stopPropagation()}
		role="dialog" use:focusTrap
		aria-label="Command palette"
		tabindex="-1"
		onkeydown={(e) => { if (e.key === 'Escape') isOpen = false; }}
	>
		<div class="border-b border-[var(--color-border)] flex items-center px-4 py-3">
			<span class="text-[var(--color-text-muted)] mr-3">🔍</span>
			<input
				id="palette-input"
				bind:value={query}
				type="text"
				placeholder="Type a command or search..."
				class="w-full bg-transparent focus:outline-none text-sm"
				aria-label="Command palette search"
				aria-autocomplete="list"
			/>
		</div>

		<div class="max-h-[60vh] overflow-y-auto p-2" role="listbox">
			{#if filteredCommands().length === 0}
				<p class="text-sm text-[var(--color-text-muted)] p-3 text-center">No matching commands.</p>
			{:else}
				{#each filteredCommands() as cmd, i}
					<button
						type="button"
						class="w-full text-left px-3 py-2 text-sm rounded flex items-center {i === selectedIndex ? 'bg-[var(--color-bg)] font-medium text-[var(--color-text-primary)]' : 'hover:bg-[var(--color-bg)] text-[var(--color-text-muted)]'}"
						role="option"
						aria-selected={i === selectedIndex}
						onclick={() => { cmd.action(); }}
						onmousemove={() => { selectedIndex = i; }}
					>
						{cmd.title}
					</button>
				{/each}
			{/if}
		</div>
	</div>
</div>
{/if}
