// tasks/frontend-creative-tools-palette-library/solution/app/src/components/ExportImport.vue
<template>
  <div class="max-w-5xl mx-auto px-4 py-8 border-t border-gray-200">
    <div class="flex justify-between items-center mb-6">
      <h2 class="font-sans text-xl font-medium">Export / Import Package</h2>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div>
        <h3 class="font-sans font-medium mb-2 text-sm">Export Library</h3>
        <select v-model="exportFormat" class="border border-gray-300 rounded px-3 py-1 font-sans text-sm focus:outline-none focus:ring-2 focus:ring-black mb-3 w-full">
          <option value="css">CSS Variables</option>
          <option value="utility-theme">Utility Theme (JS)</option>
          <option value="scss">SCSS Variables</option>
          <option value="library-json">Palette Package (JSON)</option>
        </select>
        <button @click="doExport" class="w-full bg-black text-white px-4 py-2 rounded font-sans text-sm hover:bg-gray-800 transition-colors">
          Download Artifact
        </button>
      </div>

      <div>
        <h3 class="font-sans font-medium mb-2 text-sm">Import Package (JSON)</h3>
        <form @submit.prevent="onImport" class="flex flex-col gap-3">
          <textarea
            v-model="importData"
            rows="3"
            class="border rounded px-3 py-2 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-black"
            :class="{'border-red-500': importError, 'border-gray-300': !importError}"
            placeholder='Paste JSON here...'
          ></textarea>
          <p v-if="importError" class="text-red-500 text-xs font-sans" role="alert">{{ importError }}</p>
          <button type="submit" class="w-full border border-black text-black px-4 py-2 rounded font-sans text-sm hover:bg-gray-50 transition-colors">
            Import
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { usePaletteStore } from '../stores/palette';
import { z } from 'zod';

const store = usePaletteStore();
const exportFormat = ref('library-json');
const importData = ref('');
const importError = ref('');

const paletteSchema = z.object({
  id: z.string(),
  name: z.string(),
  period: z.string(),
  swatches: z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)),
  favorite: z.boolean().optional()
});
const importSchema = z.array(paletteSchema);

function doExport() {
  const data = store.palettes;
  let content = '';
  let mimeType = 'text/plain';
  let filename = 'export.txt';

  if (exportFormat.value === 'library-json') {
    content = JSON.stringify(data, null, 2);
    mimeType = 'application/json';
    filename = 'palettes.json';
  } else if (exportFormat.value === 'css') {
    content = ':root {\n';
    data.forEach((p, i) => {
      p.swatches.forEach((s, j) => {
        content += `  --color-${p.name.replace(/\s+/g, '-').toLowerCase()}-${j}: ${s};\n`;
      });
    });
    content += '}';
    filename = 'palettes.css';
    mimeType = 'text/css';
  } else if (exportFormat.value === 'scss') {
    data.forEach((p, i) => {
      p.swatches.forEach((s, j) => {
        content += `$color-${p.name.replace(/\s+/g, '-').toLowerCase()}-${j}: ${s};\n`;
      });
    });
    filename = 'palettes.scss';
  } else if (exportFormat.value === 'utility-theme') {
    content = 'module.exports = { theme: { extend: { colors: { \n';
    data.forEach((p, i) => {
      content += `  '${p.name.replace(/\s+/g, '-').toLowerCase()}': {\n`;
      p.swatches.forEach((s, j) => {
        content += `    '${j * 100 || 50}': '${s}',\n`;
      });
      content += `  },\n`;
    });
    content += '} } } };';
    filename = 'theme.js';
    mimeType = 'text/javascript';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function onImport() {
  importError.value = '';
  try {
    const parsed = JSON.parse(importData.value);
    const result = importSchema.safeParse(parsed);
    if (!result.success) {
      importError.value = 'Invalid package format. Must be an array of palettes matching the schema.';
      return;
    }
    store.undoStack.push(JSON.parse(JSON.stringify(store.palettes)));
    store.palettes = result.data;
    importData.value = '';
  } catch (e) {
    importError.value = 'Invalid JSON.';
  }
}
</script>

// tasks/frontend-creative-tools-photo-sequence-caption-loom-handoff-map-rn-figma-variables/solution/app/src/components/ExportImport.jsx
import React, { useState } from 'react';
import { Download, Upload, Copy, Check, AlertCircle } from 'lucide-react';

export default function ExportImport({ artifactData, onImport }) {
  const [copied, setCopied] = useState(false);
  const [importText, setImportText] = useState('');
  const [error, setError] = useState(null);

  const jsonString = JSON.stringify(artifactData, null, 2);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(jsonString);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'photo-caption-v1-handoff-map.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleImport = () => {
    try {
      if (!importText.trim()) {
        setError('Paste JSON to import.');
        return;
      }
      const data = JSON.parse(importText);

      // Validation
      if (data.schemaVersion !== 'v1') {
        throw new Error("Invalid schemaVersion. Expected 'v1'.");
      }
      if (!Array.isArray(data.records)) {
        throw new Error("Invalid format: 'records' must be an array.");
      }

      const validStatuses = ['draft', 'ready', 'changed', 'archived'];
      const ids = new Set();

      for (const record of data.records) {
        if (!record.id || typeof record.id !== 'string') throw new Error("Record missing valid 'id'.");
        if (ids.has(record.id)) throw new Error(`Duplicate record ID found: ${record.id}`);
        ids.add(record.id);

        if (!validStatuses.includes(record.status)) {
          throw new Error(`Invalid status '${record.status}' on record ${record.id}.`);
        }
      }

      onImport(data);
      setImportText('');
      setError(null);
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="w-96 bg-gray-50 flex flex-col h-full shrink-0">
      <div className="p-4 border-b border-gray-200 bg-white">
        <h2 className="text-lg font-semibold text-gray-900">Portable Artifact</h2>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-6">

        <div className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
          <div className="flex justify-between items-center mb-3">
            <h3 className="text-sm font-medium text-gray-900">Export Session</h3>
            <div className="flex space-x-2">
              <button
                onClick={handleCopy}
                className="p-1.5 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                title="Copy to clipboard"
              >
                {copied ? <Check size={16} className="text-green-600" /> : <Copy size={16} />}
              </button>
              <button
                onClick={handleDownload}
                className="p-1.5 text-gray-500 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors"
                title="Download JSON"
              >
                <Download size={16} />
              </button>
            </div>
          </div>
          <div className="bg-gray-900 rounded-md p-3 max-h-64 overflow-y-auto">
            <pre className="text-xs text-green-400 font-mono whitespace-pre-wrap">
              {jsonString}
            </pre>
          </div>
        </div>

        <div className="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
          <h3 className="text-sm font-medium text-gray-900 mb-3">Import Session</h3>
          <textarea
            className={`w-full h-32 p-2 text-xs font-mono border rounded-md focus:ring-blue-500 focus:border-blue-500 ${error ? 'border-red-500' : 'border-gray-300'}`}
            placeholder="Paste photo-caption-v1-handoff-map.json content here..."
            value={importText}
            onChange={(e) => setImportText(e.target.value)}
          ></textarea>
          {error && (
            <div className="mt-2 text-xs text-red-600 flex items-start">
              <AlertCircle size={14} className="mr-1 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}
          <button
            onClick={handleImport}
            className="mt-3 w-full flex justify-center items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-800 hover:bg-gray-900 focus:outline-none"
          >
            <Upload size={16} className="mr-2" />
            Import & Restore
          </button>
        </div>

      </div>
    </div>
  );
}
