// tasks-quarantine/frontend-data-tracking-finance-reports/solution/app/src/components/ImportPanel.jsx
import { useRef } from 'preact/hooks';
import { importPanel, closeImport, importLedger, showToast } from '../state.js';
import { parseLedgerDocument } from '../ledger.js';
import { useFocusTrap } from '../hooks.jsx';
import { Icon } from './Icon.jsx';

export function ImportPanel() {
  const ip = importPanel.value;
  const fileRef = useRef(null);
  const trapRef = useFocusTrap(ip.open, {
    onEscape: closeImport,
    initialFocus: (node) => node && node.querySelector('textarea'),
  });
  if (!ip.open) return null;

  const busy = ip.status === 'busy';

  const readFile = (file) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      importPanel.value = { ...importPanel.value, content: String(reader.result || ''), status: 'idle', error: null, summary: null };
    };
    reader.onerror = () => {
      importPanel.value = { ...importPanel.value, status: 'error', error: 'Could not read the selected file' };
    };
    reader.readAsText(file);
  };

  const commit = () => {
    importPanel.value = { ...importPanel.value, status: 'busy', error: null, summary: null };
    // perceptible busy state for accessibility (4.5)
    setTimeout(() => {
      const parsed = parseLedgerDocument(importPanel.value.content);
      if (!parsed.ok) {
        importPanel.value = { ...importPanel.value, status: 'error', error: parsed.message };
        return;
      }
      importLedger(parsed.data);
      const summary = { transactions: parsed.data.transactions.length, thresholds: parsed.data.thresholds.length };
      importPanel.value = { ...importPanel.value, status: 'success', error: null, summary };
      showToast(`Imported ${summary.transactions} transactions and ${summary.thresholds} thresholds`, 'success');
    }, 220);
  };

  const validContent = importPanel.value.content.trim().length > 0;

  return (
    <div class="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto p-4 sm:items-center">
      <button type="button" aria-label="Close import panel" class="absolute inset-0 bg-[#082727]/40 anim-fade-in" onClick={closeImport} />
      <div
        ref={trapRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby="ld-import-title"
        tabindex="-1"
        class="anim-scale-in relative my-8 w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-black/5"
      >
        <header class="flex items-center justify-between border-b border-[#eef4f1] bg-[#f2faf7] px-5 py-3.5">
          <h2 id="ld-import-title" class="flex items-center gap-2 font-display text-lg font-semibold text-[#0f3d3e]">
            <span class="grid h-7 w-7 place-items-center rounded-lg bg-[#0f3d3e] text-[#8af0d3]">
              <Icon name="lucide:upload" decorative size={15} />
            </span>
            Import ledger JSON
          </h2>
          <button
            type="button"
            class="grid h-8 w-8 place-items-center rounded-lg text-[#4a6460] transition hover:bg-[#e6f7f1] hover:text-[#0f3d3e]"
            onClick={closeImport}
            aria-label="Close import panel"
          >
            <Icon name="lucide:x" decorative size={18} />
          </button>
        </header>

        <div class="flex flex-col gap-3 px-5 py-4">
          <div class="flex items-center gap-2 rounded-lg bg-[#e6f7f1] px-3 py-2 text-xs font-medium text-[#0f3d3e]">
            <Icon name="lucide:replace" decorative size={15} />
            Import mode: <span class="font-semibold">Replace</span> — ledger JSON only. Replaces the current transactions and thresholds.
          </div>

          <div class="flex flex-col gap-1">
            <label for="ld-import-text" class="text-xs font-semibold uppercase tracking-wide text-[#4a6460]">
              Ledger JSON document
            </label>
            <textarea
              id="ld-import-text"
              rows={8}
              class="scroll-area w-full resize-y rounded-lg border border-[#d7eae3] bg-[#0f1f1f] px-3 py-2 font-mono text-[12px] text-[#d7eae3] focus:border-[#2c8a85] focus:outline-none focus-visible:ring-2 focus-visible:ring-[#2c8a85]/40"
              value={ip.content}
              onInput={(e) => {
                importPanel.value = { ...importPanel.value, content: e.target.value, status: 'idle', error: null };
              }}
            />
            <div class="flex items-center justify-between">
              <button
                type="button"
                class="inline-flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold text-[#175250] transition hover:bg-[#e6f7f1]"
                onClick={() => fileRef.current && fileRef.current.click()}
              >
                <Icon name="lucide:file-json" decorative size={15} />
                Load a .json file
              </button>
              <input
                ref={fileRef}
                type="file"
                accept="application/json,.json"
                class="sr-only"
                onChange={(e) => readFile(e.target.files && e.target.files[0])}
              />
              <span class="text-xs text-[#7e958f]">{ip.content.trim().length} characters</span>
            </div>
          </div>

          {ip.status === 'error' && ip.error && (
            <div role="alert" class="flex items-start gap-2 rounded-lg border border-[#f0c9b8] bg-[#fff1e9] px-3 py-2 text-sm text-[#c2410c]">
              <Icon name="lucide:circle-alert" decorative size={16} class="mt-0.5 shrink-0" />
              <span>
                <span class="font-semibold">Import rejected.</span> {ip.error}
              </span>
            </div>
          )}
          {ip.status === 'success' && ip.summary && (
            <div role="status" class="flex items-start gap-2 rounded-lg border border-[#bfe6d6] bg-[#e3f6ee] px-3 py-2 text-sm text-[#047857]">
              <Icon name="lucide:circle-check-big" decorative size={16} class="mt-0.5 shrink-0" />
              <span>
                <span class="font-semibold">Imported with Replace.</span> {ip.summary.transactions} transactions and {ip.summary.thresholds} thresholds now in the ledger.
              </span>
            </div>
          )}

          <div class="mt-1 flex items-center justify-end gap-2">
            <button type="button" class="btn btn-sm bg-white text-[#0f3d3e] ring-1 ring-[#d7eae3] hover:bg-[#e6f7f1]" onClick={closeImport}>
              Close
            </button>
            <button
              type="button"
              class="btn btn-sm bg-[#0f3d3e] text-white hover:bg-[#175250] disabled:bg-[#cfe2db] disabled:text-white/80"
              disabled={!validContent || busy}
              onClick={commit}
            >
              {busy ? (
                <>
                  <Icon name="lucide:loader-circle" decorative size={15} class="animate-spin" />
                  Importing…
                </>
              ) : (
                <>
                  <Icon name="lucide:upload" decorative size={15} />
                  Import with Replace
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// tasks/frontend-productivity-tagnote/solution/app/src/components/ImportPanel.tsx
import { component$, $, useSignal, useStore } from '@builder.io/qwik';
import type { AppState } from '../types';

interface ImportPanelProps {
  onImport: (state: AppState) => void;
  onClose: () => void;
}

export const ImportPanel = component$<ImportPanelProps>(({ onImport, onClose }) => {
  const local = useStore({
    jsonText: '',
    error: '',
    fieldError: ''
  });

  const handleImport = $(() => {
    try {
      const parsed = JSON.parse(local.jsonText);
      if (!parsed || typeof parsed !== 'object') {
        local.error = 'Invalid JSON';
        local.fieldError = 'root';
        return;
      }
      if (parsed.schemaVersion !== 'tagnote-session/v1') {
        local.error = 'Invalid schemaVersion. Expected "tagnote-session/v1"';
        local.fieldError = 'schemaVersion';
        return;
      }
      if (!Array.isArray(parsed.todoTags)) {
        local.error = 'Missing or invalid todoTags';
        local.fieldError = 'todoTags';
        return;
      }
      if (!Array.isArray(parsed.notes)) {
        local.error = 'Missing or invalid notes';
        local.fieldError = 'notes';
        return;
      }
      for (const note of parsed.notes) {
        if (typeof note.text !== 'string' || note.text.length > 2000) {
            local.error = 'Invalid text: must be string at most 2000 characters';
            local.fieldError = 'text';
            return;
        }
        if (note.marks && Array.isArray(note.marks)) {
           for (const mark of note.marks) {
               if (mark.style !== 'bold' && mark.style !== 'italic') {
                   local.error = 'Invalid mark style: must be "bold" or "italic"';
                   local.fieldError = 'marks';
                   return;
               }
           }
        }
        if (typeof note.pinned !== 'boolean') {
            local.error = 'Invalid pinned: must be boolean';
            local.fieldError = 'pinned';
            return;
        }
        if (typeof note.archived !== 'boolean') {
            local.error = 'Invalid archived: must be boolean';
            local.fieldError = 'archived';
            return;
        }
        if (typeof note.done !== 'boolean') {
            local.error = 'Invalid done: must be boolean';
            local.fieldError = 'done';
            return;
        }
      }

      // Restore createdAt from ISO strings
      const importedState: AppState = {
        todoTags: parsed.todoTags,
        notes: parsed.notes.map((n: any) => ({
          id: n.id,
          text: n.text,
          tags: n.tags || [],
          pinned: n.pinned,
          archived: n.archived,
          done: n.done,
          createdAt: n.createdAt ? new Date(n.createdAt).getTime() : Date.now(),
          file: n.attachment ? { name: n.attachment.name, size: n.attachment.sizeBytes } : undefined
        }))
      };

      onImport(importedState);
      onClose();
    } catch (e) {
      local.error = 'Invalid JSON payload';
      local.fieldError = 'json';
    }
  });

  const handleKeyDown = $((e: KeyboardEvent) => {
    if (e.key === 'Escape') onClose();
  });

  const handleFileChange = $((e: Event) => {
     const input = e.target as HTMLInputElement;
     const file = input.files?.[0];
     if (!file) return;
     const reader = new FileReader();
     reader.onload = (e) => {
         if (e.target?.result && typeof e.target.result === 'string') {
             local.jsonText = e.target.result;
         }
     };
     reader.readAsText(file);
     input.value = '';
  });

  return (
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 transition-opacity duration-200" onKeyDown$={handleKeyDown} tabIndex={-1}>
      <div class="w-full max-w-2xl overflow-hidden rounded-xl bg-white shadow-2xl transition-transform duration-200 scale-100">
        <div class="flex items-center justify-between border-b border-gray-200 px-6 py-4 bg-gray-50">
          <h2 class="text-xl font-bold text-gray-800">Import Session JSON</h2>
          <button onClick$={onClose} class="text-gray-400 hover:text-gray-600 focus:outline-none focus:ring-2 focus:ring-[var(--color-accent)] rounded-full p-1" aria-label="Close Import Panel">✕</button>
        </div>

        <div class="p-6">
          <p class="mb-4 text-sm text-gray-600">Paste your TagNote Session JSON here, or upload a file.</p>

          <textarea
            value={local.jsonText}
            onInput$={(e: Event) => { local.jsonText = (e.target as HTMLTextAreaElement).value; local.error = ''; }}
            class="h-[300px] w-full resize-none rounded-lg border border-gray-300 p-4 font-mono text-sm focus:border-[var(--color-accent)] focus:ring-1 focus:ring-[var(--color-accent)]"
            placeholder="{ schemaVersion: 'tagnote-session/v1', ... }"
            aria-label="Import JSON textarea"
          />

          {local.error && (
            <div class="mt-3 rounded bg-red-50 p-3 text-sm text-red-600" aria-live="polite">
              <strong>Error ({local.fieldError}):</strong> {local.error}
            </div>
          )}

          <div class="mt-6 flex items-center justify-between">
            <label class="cursor-pointer rounded-full bg-[var(--color-primary)] px-4 py-2 text-sm font-medium text-[var(--color-accent)] transition-colors hover:bg-[#D4E0F0]">
              Upload File
              <input type="file" class="hidden" accept=".json,application/json" onChange$={handleFileChange} />
            </label>
            <div class="flex gap-3">
              <button onClick$={onClose} class="rounded-full px-4 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-100">
                Cancel
              </button>
              <button onClick$={handleImport} class="rounded-full bg-[var(--color-accent)] px-6 py-2 text-sm font-medium text-white transition-colors hover:bg-[#0066DD]">
                Import
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
});
