// tasks/frontend-productivity-sidedock/solution/app/src/components/SearchBar.vue
<script setup>
import { useSidedockStore } from '../stores/sidedock.js'

const store = useSidedockStore()

function clearSearch() {
  store.searchQuery = ''
}
</script>

<template>
  <div class="px-4 py-2 border-b flex items-center gap-2" style="border-color: var(--color-border); background: white;">
    <label class="flex-1 relative search-label">
      <span>Search bookmarks</span>
      <span aria-hidden="true" class="absolute left-2.5 input-icon text-sm">🔍</span>
      <input
        v-model="store.searchQuery"
        type="text"
        placeholder="Title or URL"
        class="w-full pl-8 pr-3 py-1.5 rounded-md border text-sm outline-none transition-all"
        style="border-color: var(--color-border); font-family: Inter, sans-serif;"
        @focus="$event.target.style.borderColor = 'var(--color-accent)'"
        @blur="$event.target.style.borderColor = 'var(--color-border)'"
        @keydown.escape="clearSearch"
      />
    </label>
    <button
      @click="store.searchScope = store.searchScope === 'current' ? 'all' : 'current'"
      class="px-2.5 py-1.5 rounded-md text-xs font-medium cursor-pointer transition-all border whitespace-nowrap"
      :class="store.searchScope === 'all' ? 'border-transparent' : 'border-[var(--color-border)]'"
      :style="store.searchScope === 'all' 
        ? { background: 'var(--color-accent)', color: 'white' } 
        : { background: 'white', color: 'var(--color-text-primary)' }"
    >
      {{ store.searchScope === 'current' ? 'Search all' : 'Search current' }}
    </button>
  </div>
</template>

<style scoped>
.search-label { display: flex; flex-direction: column; gap: 4px; font-size: 12px; font-weight: 600; }
.input-icon { bottom: 8px; top: auto; }
@media (max-width: 420px) {
  .border-b { align-items: flex-end; flex-wrap: wrap; }
  button { min-height: 44px; }
}
</style>

// tasks/frontend-productivity-tagnote/solution/app/src/components/SearchBar.tsx
import { component$ } from '@builder.io/qwik';
import type { Signal } from '@builder.io/qwik';

interface SearchBarProps {
  query: Signal<string>;
  placeholder?: string;
}

export const SearchBar = component$<SearchBarProps>(({ query, placeholder }) => {
  return (
    <div class="relative px-4 py-3 bg-white border-b border-gray-200">
      <div class="relative">
        <svg
          class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
        >
          <circle cx="11" cy="11" r="8" />
          <path d="m21 21-4.35-4.35" />
        </svg>
        <input
          type="text"
          value={query.value}
          onInput$={(e: Event) => {
            const target = e.target as HTMLInputElement;
            query.value = target.value;
          }}
          placeholder={placeholder || 'Search notes and tags...'}
          class="w-full rounded-lg border border-gray-200 bg-gray-50 py-2.5 pl-10 pr-4 text-[15px] text-[var(--color-text-primary)] outline-none placeholder:text-gray-400 focus:border-[var(--color-accent)] focus:ring-1 focus:ring-[var(--color-accent)]"
        />
        {query.value && (
          <button
            onClick$={() => { query.value = ''; }}
            class="absolute right-3 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600"
          >
            ✕
          </button>
        )}
      </div>
      <div class="scrollbar-hide mt-3 flex gap-2 overflow-x-auto pb-1">
        <button onClick$={() => query.value = 'tag:family'} class="flex-shrink-0 rounded-full bg-[var(--color-primary)] px-3 py-1 text-xs font-medium text-[var(--color-accent)] hover:bg-[#D4E0F0]">
          Tag:Family
        </button>
        <button onClick$={() => query.value = 'tag:todo'} class="flex-shrink-0 rounded-full bg-[var(--color-primary)] px-3 py-1 text-xs font-medium text-[var(--color-accent)] hover:bg-[#D4E0F0]">
          Tag:Todo
        </button>
        <button onClick$={() => query.value = 'done:open'} class="flex-shrink-0 rounded-full bg-[var(--color-primary)] px-3 py-1 text-xs font-medium text-[var(--color-accent)] hover:bg-[#D4E0F0]">
          Done:Open
        </button>
        <button onClick$={() => query.value = 'done:done'} class="flex-shrink-0 rounded-full bg-[var(--color-primary)] px-3 py-1 text-xs font-medium text-[var(--color-accent)] hover:bg-[#D4E0F0]">
          Done:Done
        </button>
      </div>
    </div>
  );
});
