// tasks/frontend-lineforge/solution/app/src/components/Toast.jsx
import { h } from 'preact';
import { toastMessage } from '../store';

// Always mounted so the live region exists before the first status message.
export function Toast() {
  const message = toastMessage.value;
  return (
    <div
      class="fixed top-4 left-1/2 -translate-x-1/2 z-50 pointer-events-none"
      role="status"
      aria-live="polite"
    >
      {message && (
        <div class="toast bg-[var(--color-primary)] text-white px-5 py-3 rounded-[10px] shadow-lg text-base font-medium">
          {message}
        </div>
      )}
    </div>
  );
}

// tasks/frontend-productivity-tagnote/solution/app/src/components/Toast.tsx
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import type { Signal } from '@builder.io/qwik';

interface ToastProps {
  message: Signal<string>;
}

export const Toast = component$<ToastProps>(({ message }) => {
  const visible = useSignal(false);
  const exiting = useSignal(false);
  const displayText = useSignal('');

  useVisibleTask$(({ track }) => {
    track(() => message.value);
    if (message.value) {
      displayText.value = message.value;
      exiting.value = false;
      visible.value = true;
      const timer = setTimeout(() => {
        exiting.value = true;
        setTimeout(() => {
          visible.value = false;
          message.value = '';
        }, 250);
      }, 2500);
      return () => clearTimeout(timer);
    }
  });

  if (!visible.value) return null;

  return (
    <div
      class={`fixed bottom-24 left-1/2 z-50 -translate-x-1/2 ${exiting.value ? 'toast-exit' : 'toast-enter'}`}
      role="status"
      aria-live="polite"
    >
      <div class="rounded-full bg-[var(--color-text-primary)] px-5 py-2.5 text-sm font-medium text-white shadow-lg">
        {displayText.value}
      </div>
    </div>
  );
});
