// artifacts/frontend-creative-tools-material-theme-studio/app/src/components/Toast.tsx
import { useEffect, useRef, useState } from 'react';

export interface ToastState {
  msg: string;
  leaving: boolean;
}

export function useToast() {
  const [toast, setToast] = useState<ToastState | null>(null);
  const timers = useRef<{ hide?: ReturnType<typeof setTimeout>; remove?: ReturnType<typeof setTimeout> }>({});

  const show = (msg: string) => {
    clearTimeout(timers.current.hide);
    clearTimeout(timers.current.remove);
    setToast({ msg, leaving: false });
    timers.current.hide = setTimeout(() => setToast(current => (current ? { ...current, leaving: true } : null)), 2250);
    timers.current.remove = setTimeout(() => setToast(null), 2600);
  };

  useEffect(
    () => () => {
      clearTimeout(timers.current.hide);
      clearTimeout(timers.current.remove);
    },
    []
  );

  return { toast, show };
}

export function ToastView({ toast }: { toast: ToastState | null }) {
  if (!toast) return null;
  return (
    <div
      role="status"
      aria-live="polite"
      className={`fixed bottom-5 left-1/2 z-[1400] rounded bg-blue-600 px-4 py-2.5 text-sm font-medium text-white shadow-xl transition-all duration-300 transform ${
        toast.leaving ? 'opacity-0 translate-y-8' : 'opacity-100 translate-y-0'
      }`}
      style={{ animation: 'toast-in 0.25s ease both' }}
    >
      {toast.msg}
    </div>
  );
}

// tasks/frontend-productivity-tagnote/solution/app/src/components/Toast.tsx
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik';
import type { Signal } from '@builder.io/qwik';

interface ToastProps {
  message: Signal<string>;
}

export const Toast = component$<ToastProps>(({ message }) => {
  const visible = useSignal(false);
  const exiting = useSignal(false);
  const displayText = useSignal('');

  useVisibleTask$(({ track }) => {
    track(() => message.value);
    if (message.value) {
      displayText.value = message.value;
      exiting.value = false;
      visible.value = true;
      const timer = setTimeout(() => {
        exiting.value = true;
        setTimeout(() => {
          visible.value = false;
          message.value = '';
        }, 250);
      }, 2500);
      return () => clearTimeout(timer);
    }
  });

  if (!visible.value) return null;

  return (
    <div
      class={`fixed bottom-24 left-1/2 z-50 -translate-x-1/2 ${exiting.value ? 'toast-exit' : 'toast-enter'}`}
      role="status"
      aria-live="polite"
    >
      <div class="rounded-full bg-[var(--color-text-primary)] px-5 py-2.5 text-sm font-medium text-white shadow-lg">
        {displayText.value}
      </div>
    </div>
  );
});
