// tasks/frontend-notenest/solution/app/src/components/Toast.svelte
<script lang="ts">
  import { getToasts } from '../lib/store.svelte';

  let toasts = $derived(getToasts());
</script>

<div class="fixed top-4 right-4 z-50 flex flex-col gap-2" role="alert" aria-live="polite">
  {#each toasts as toast (toast.id)}
    <div
      class="toast-enter px-4 py-3 rounded-lg shadow-lg text-white text-sm font-medium max-w-xs"
      class:bg-green-500={toast.type === 'success'}
      class:bg-red-500={toast.type === 'error'}
      class:bg-blue-500={toast.type === 'info'}
    >
      {toast.message}
    </div>
  {/each}
</div>

// tasks/frontend-productivity-loopdaily/solution/app/src/components/Toast.tsx
import { useAtom } from "jotai";
import { toastsAtom, removeToastAtom } from "../store";

export default function Toast() {
  const [toasts] = useAtom(toastsAtom);
  const [, remove] = useAtom(removeToastAtom);

  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2 items-center pointer-events-none">
      {toasts.map((t) => {
        const bgColor =
          t.type === "success"
            ? "bg-[#0F9D74]"
            : t.type === "error"
            ? "bg-[#EF4444]"
            : "bg-[#475569]";

        const isAlert = t.type === "error" || t.type === "info";

        return (
          <div
            key={t.id}
            className={`${bgColor} text-white px-5 py-3 rounded-lg shadow-lg text-sm font-medium cursor-pointer toast-enter max-w-xs text-center pointer-events-auto`}
            onClick={() => remove(t.id)}
            role={isAlert ? "alert" : "status"}
            aria-live={isAlert ? "assertive" : "polite"}
          >
            {t.text}
          </div>
        );
      })}
    </div>
  );
}
