// tasks/frontend-productivity-loopdaily/solution/app/src/components/ui/modal.tsx
import { useEffect, useId, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  description?: ReactNode;
  children?: ReactNode;
  /** Element that should regain focus when the dialog closes (defaults to the opener). */
  restoreFocus?: HTMLElement | null;
}

const FOCUSABLE =
  'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Accessible modal dialog: portals to <body>, traps Tab focus while open, closes
 * on Escape / overlay click, and returns focus to the invoking control on close
 * (so the Import button regains focus, not <body>).
 */
export default function Modal({
  open,
  onClose,
  title,
  description,
  children,
  restoreFocus,
}: ModalProps) {
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const restoreRef = useRef<HTMLElement | null>(null);
  const onCloseRef = useRef(onClose);
  const titleId = useId();
  const descId = useId();

  useEffect(() => {
    onCloseRef.current = onClose;
  }, [onClose]);

  useEffect(() => {
    if (!open) return;
    restoreRef.current =
      restoreFocus ?? ((document.activeElement as HTMLElement | null) || null);
    const node = dialogRef.current;
    if (!node) return;

    const focusables = () =>
      Array.from(node.querySelectorAll<HTMLElement>(FOCUSABLE)).filter((el) => {
        return el.offsetParent !== null || el === document.activeElement;
      });

    const first = focusables()[0] ?? node;
    const focusTimer = window.setTimeout(() => {
      first.focus({ preventScroll: true });
    }, 20);

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        onCloseRef.current();
        return;
      }
      if (e.key !== "Tab") return;
      const items = focusables();
      if (items.length === 0) {
        e.preventDefault();
        return;
      }
      const firstEl = items[0];
      const lastEl = items[items.length - 1];
      const active = document.activeElement as HTMLElement;
      if (e.shiftKey && (active === firstEl || active === node)) {
        e.preventDefault();
        lastEl.focus();
      } else if (!e.shiftKey && active === lastEl) {
        e.preventDefault();
        firstEl.focus();
      }
    };

    document.addEventListener("keydown", onKeyDown, true);
    return () => {
      document.removeEventListener("keydown", onKeyDown, true);
      window.clearTimeout(focusTimer);
      const restore = restoreRef.current;
      window.setTimeout(() => {
        if (restore && typeof restore.focus === "function" && document.contains(restore)) {
          restore.focus({ preventScroll: true });
        }
      }, 0);
    };
  }, [open, restoreFocus]);

  if (!open) return null;

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation">
      <div
        className="absolute inset-0 bg-[#1B2430]/40 backdrop-blur-[2px]"
        data-slot="modal-overlay"
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={description ? descId : undefined}
        tabIndex={-1}
        className="relative z-10 w-full max-w-sm rounded-[8px] bg-[#FFFFFF] p-5 text-[#1B2430] shadow-[0_20px_50px_rgba(27,36,48,0.25)] outline-none"
        data-slot="modal-dialog"
      >
        <h2 id={titleId} className="text-lg font-bold text-[#1B2430]">
          {title}
        </h2>
        {description && (
          <p id={descId} className="mt-2 text-sm text-[#64748B]">
            {description}
          </p>
        )}
        <div className="mt-4">{children}</div>
      </div>
    </div>,
    document.body
  );
}

// tasks/frontend-data-tracking-media-timeline/solution/app/src/components/Modal.jsx
import { createEffect, on, onCleanup, Show, children } from "solid-js";
import { Portal } from "solid-js/web";

// Custom dialog primitive: traps focus while open, closes on Escape, and ALWAYS
// returns focus to the element that opened it (the originating control).
const FOCUSABLE =
  'a[href],button:not([disabled]),textarea:not([disabled]),input:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])';

export default function Modal(props) {
  let contentRef;
  let saved = null;
  let firstOpen = true;

  const focusables = () =>
    contentRef ? Array.from(contentRef.querySelectorAll(FOCUSABLE)).filter((el) => el.offsetParent !== null || el === document.activeElement) : [];

  createEffect(
    on(
      () => props.open,
      (open) => {
        if (open) {
          saved = document.activeElement;
          if (firstOpen) {
            firstOpen = false;
            requestAnimationFrame(() => {
              if (props.initialFocus && props.initialFocus()) {
                const el = props.initialFocus();
                if (el && el.focus) el.focus();
              } else {
                const f = focusables();
                if (f.length) f[0].focus();
                else if (contentRef) contentRef.focus();
              }
            });
          }
        } else {
          firstOpen = true;
          if (saved && saved !== document.body && typeof saved.focus === "function") {
            try {
              saved.focus();
            } catch {
              /* ignore */
            }
          }
          saved = null;
        }
      },
    ),
  );

  function onKeyDown(e) {
    if (e.key === "Escape") {
      e.preventDefault();
      e.stopPropagation();
      props.onClose && props.onClose();
      return;
    }
    if (e.key === "Tab") {
      const f = focusables();
      if (!f.length) {
        e.preventDefault();
        return;
      }
      const first = f[0];
      const last = f[f.length - 1];
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault();
        last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault();
        first.focus();
      }
    }
    props.onKeyDown && props.onKeyDown(e);
  }

  function onOverlayClick(e) {
    if (e.target === e.currentTarget && props.closeOnOverlay !== false) {
      props.onClose && props.onClose();
    }
  }

  return (
    <Show when={props.open || props.closing}>
      <Portal mount={props.mount}>
        <div
          class="fixed inset-0 z-[80] flex anim-overlay"
          classList={{
            "items-center justify-center p-4": props.placement !== "right",
            "items-stretch justify-end": props.placement === "right",
          }}
          style={{ background: props.placement === "right" ? "rgba(20,14,8,0.34)" : "rgba(20,14,8,0.42)" }}
          onMouseDown={onOverlayClick}
        >
          <div
            ref={contentRef}
            role={props.role || "dialog"}
            aria-modal="true"
            aria-label={props.label}
            aria-labelledby={props.labelledBy}
            tabindex="-1"
            onKeyDown={onKeyDown}
            class={props.contentClass || "bg-paper rounded-2xl shadow-2xl max-w-lg w-full max-h-[88vh] overflow-auto thin-scroll"}
            classList={{
              "anim-detail-in": !props.closing && props.placement !== "right",
              "anim-detail-out": props.closing && props.placement !== "right",
              "anim-drawer-in": !props.closing && props.placement === "right",
              "anim-drawer-out": props.closing && props.placement === "right",
              "h-full": props.placement === "right",
            }}
          >
            {props.children}
          </div>
        </div>
      </Portal>
    </Show>
  );
}
