// tasks/frontend-scribblespace/solution/app/src/components/CanvasObject.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import type { CanvasObject } from '../types';
import { useAppDispatch, useAppSelector } from '../hooks';
import {
  selectOnly,
  toggleSelect,
  updateObject,
  setConnectFrom,
  addConnector,
  setShowDeleteConfirm,
  clearLastAdded,
  moveObject,
  resizeObject,
} from '../slices/appSlice';
import { NOTE_COLORS, SHAPE_COLORS } from '../slices/appSlice';

interface CanvasObjectProps {
  obj: CanvasObject;
  isSelected: boolean;
  isSearchHighlight: boolean;
  isConnectSource: boolean;
  zoom: number;
}

type Corner = 'nw' | 'ne' | 'sw' | 'se';

const CanvasObjectComponent: React.FC<CanvasObjectProps> = ({
  obj,
  isSelected,
  isSearchHighlight,
  isConnectSource,
  zoom,
}) => {
  const dispatch = useAppDispatch();
  const activeTool = useAppSelector(s => s.app.activeTool);
  const connectFromId = useAppSelector(s => s.app.connectFromId);
  const selectedIds = useAppSelector(s => s.app.selectedIds);
  const lastAddedId = useAppSelector(s => s.app.lastAddedId);

  const [isEditing, setIsEditing] = useState(false);
  const [hovered, setHovered] = useState(false);
  const [dragGhost, setDragGhost] = useState<{ x: number; y: number } | null>(null);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const singleSelected = isSelected && selectedIds.length === 1;

  // Focus a freshly created object so keyboard users can continue immediately
  useEffect(() => {
    if (lastAddedId === obj.id) {
      wrapperRef.current?.focus();
      dispatch(clearLastAdded());
    }
  }, [lastAddedId, obj.id, dispatch]);

  const handleConnectPick = useCallback(() => {
    if (connectFromId === null) {
      dispatch(setConnectFrom(obj.id));
    } else if (connectFromId !== obj.id) {
      dispatch(addConnector({ fromId: connectFromId, toId: obj.id }));
    } else {
      dispatch(setConnectFrom(null));
    }
  }, [connectFromId, obj.id, dispatch]);

  const handleMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.stopPropagation();
      if (activeTool === 'connect') {
        e.preventDefault();
        handleConnectPick();
        return;
      }
      const target = e.target as HTMLElement;
      if (target.closest('button, textarea, input')) return;
      if (isEditing) return;
      e.preventDefault();
      wrapperRef.current?.focus();

      if (e.shiftKey) {
        dispatch(toggleSelect(obj.id));
        return;
      }
      if (!selectedIds.includes(obj.id)) {
        dispatch(selectOnly(obj.id));
      }

      // Drag with an abort path: Escape returns the object to its origin
      const startX = e.clientX;
      const startY = e.clientY;
      const origX = obj.x;
      const origY = obj.y;
      let moved = false;

      const onMove = (me: MouseEvent) => {
        const dx = (me.clientX - startX) / zoom;
        const dy = (me.clientY - startY) / zoom;
        if (!moved && (Math.abs(dx) > 2 || Math.abs(dy) > 2)) {
          moved = true;
          setDragGhost({ x: origX, y: origY });
        }
        if (moved) {
          dispatch(updateObject({ id: obj.id, updates: { x: origX + dx, y: origY + dy } }));
        }
      };
      const cleanup = () => {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onUp);
        document.removeEventListener('keydown', onKey, true);
        setDragGhost(null);
      };
      const onUp = () => cleanup();
      const onKey = (ke: KeyboardEvent) => {
        if (ke.key === 'Escape') {
          dispatch(updateObject({ id: obj.id, updates: { x: origX, y: origY } }));
          cleanup();
        }
      };
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onUp);
      document.addEventListener('keydown', onKey, true);
    },
    [activeTool, handleConnectPick, isEditing, obj.id, obj.x, obj.y, selectedIds, zoom, dispatch]
  );

  const startCornerResize = useCallback(
    (e: React.MouseEvent, corner: Corner) => {
      e.stopPropagation();
      e.preventDefault();
      const startX = e.clientX;
      const startY = e.clientY;
      const orig = { x: obj.x, y: obj.y, w: obj.width, h: obj.height };

      const onMove = (me: MouseEvent) => {
        const dx = (me.clientX - startX) / zoom;
        const dy = (me.clientY - startY) / zoom;
        let newW = orig.w;
        let newH = orig.h;
        let newX = orig.x;
        let newY = orig.y;
        if (corner === 'se' || corner === 'ne') newW = Math.max(60, orig.w + dx);
        if (corner === 'sw' || corner === 'nw') {
          newW = Math.max(60, orig.w - dx);
          newX = orig.x + (orig.w - newW);
        }
        if (corner === 'se' || corner === 'sw') newH = Math.max(50, orig.h + dy);
        if (corner === 'ne' || corner === 'nw') {
          newH = Math.max(50, orig.h - dy);
          newY = orig.y + (orig.h - newH);
        }
        dispatch(
          updateObject({ id: obj.id, updates: { x: newX, y: newY, width: newW, height: newH } })
        );
      };
      const onUp = () => {
        document.removeEventListener('mousemove', onMove);
        document.removeEventListener('mouseup', onUp);
      };
      document.addEventListener('mousemove', onMove);
      document.addEventListener('mouseup', onUp);
    },
    [obj.id, obj.x, obj.y, obj.width, obj.height, zoom, dispatch]
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.target !== e.currentTarget) return;
      if (e.key === 'Enter' || e.key === ' ') {
        e.preventDefault();
        if (activeTool === 'connect') {
          handleConnectPick();
          return;
        }
        if (!selectedIds.includes(obj.id)) {
          dispatch(selectOnly(obj.id));
        }
        if (e.key === 'Enter' && (obj.type === 'note' || obj.type === 'flashcard')) {
          setIsEditing(true);
        }
        return;
      }
      if (e.key === 'Delete' || e.key === 'Backspace') {
        e.preventDefault();
        if (!selectedIds.includes(obj.id)) {
          dispatch(selectOnly(obj.id));
        }
        dispatch(setShowDeleteConfirm(true));
        return;
      }
      const step = 16;
      if (e.key.startsWith('Arrow')) {
        e.preventDefault();
        if (e.shiftKey) {
          const dw = e.key === 'ArrowRight' ? step : e.key === 'ArrowLeft' ? -step : 0;
          const dh = e.key === 'ArrowDown' ? step : e.key === 'ArrowUp' ? -step : 0;
          dispatch(resizeObject({ id: obj.id, dw, dh }));
        } else {
          const dx = e.key === 'ArrowRight' ? step : e.key === 'ArrowLeft' ? -step : 0;
          const dy = e.key === 'ArrowDown' ? step : e.key === 'ArrowUp' ? -step : 0;
          dispatch(moveObject({ id: obj.id, dx, dy }));
        }
      }
    },
    [activeTool, handleConnectPick, obj.id, obj.type, selectedIds, dispatch]
  );

  const finishEditing = useCallback(() => {
    setIsEditing(false);
    wrapperRef.current?.focus();
  }, []);

  // Shadow composition keeps drop shadow, hover, selection and search glow stackable
  const shadows: string[] = [];
  if (obj.type === 'note' || obj.type === 'flashcard') {
    shadows.push('0 3px 10px rgba(33, 29, 58, 0.18)');
  } else {
    shadows.push('0 2px 6px rgba(33, 29, 58, 0.15)');
  }
  if (hovered) shadows.push('0 8px 22px rgba(33, 29, 58, 0.25)');
  if (isSelected) shadows.push('0 0 0 3px var(--color-primary)');
  if (isSearchHighlight) {
    shadows.push('0 0 0 4px rgba(109, 91, 208, 0.85), 0 0 20px 7px rgba(109, 91, 208, 0.55)');
  }
  if (isConnectSource) shadows.push('0 0 0 5px rgba(224, 160, 48, 0.85)');

  const accessibleName =
    obj.type === 'note'
      ? `Note: ${obj.text ? obj.text.slice(0, 60) : 'empty'}`
      : obj.type === 'flashcard'
        ? `Flashcard ${obj.flipped ? 'back' : 'front'}: ${
            (obj.flipped ? obj.back : obj.front)?.slice(0, 60) || 'empty'
          }`
        : `${obj.type.charAt(0).toUpperCase()}${obj.type.slice(1)} shape`;

  const wrapperStyle: React.CSSProperties = {
    position: 'absolute',
    left: obj.x,
    top: obj.y,
    width: obj.width,
    height: obj.height,
    zIndex: obj.zIndex,
    cursor: activeTool === 'connect' ? 'crosshair' : 'move',
    userSelect: isEditing ? 'text' : 'none',
    boxShadow: shadows.join(', '),
    borderRadius: obj.type === 'circle' ? '50%' : '8px',
  };

  const cornerHandles = singleSelected && activeTool === 'select' && (
    <>
      {(['nw', 'ne', 'sw', 'se'] as Corner[]).map(corner => (
        <button
          key={corner}
          type="button"
          tabIndex={-1}
          aria-label={`Resize from ${
            corner === 'nw'
              ? 'top-left'
              : corner === 'ne'
                ? 'top-right'
                : corner === 'sw'
                  ? 'bottom-left'
                  : 'bottom-right'
          } corner`}
          onMouseDown={e => startCornerResize(e, corner)}
          style={{
            position: 'absolute',
            width: 24,
            height: 24,
            top: corner === 'nw' || corner === 'ne' ? -12 : undefined,
            bottom: corner === 'sw' || corner === 'se' ? -12 : undefined,
            left: corner === 'nw' || corner === 'sw' ? -12 : undefined,
            right: corner === 'ne' || corner === 'se' ? -12 : undefined,
            background: 'transparent',
            border: 'none',
            padding: 0,
            cursor: corner === 'nw' || corner === 'se' ? 'nwse-resize' : 'nesw-resize',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 5,
          }}
        >
          <span
            aria-hidden="true"
            style={{
              display: 'block',
              width: 12,
              height: 12,
              backgroundColor: 'var(--color-primary)',
              border: '2px solid #FFFFFF',
              borderRadius: 3,
              boxShadow: '0 1px 3px rgba(33, 29, 58, 0.35)',
            }}
          />
        </button>
      ))}
    </>
  );

  const colorSwatches = (palette: { hex: string; name: string }[]) => (
    <div
      className="flex flex-wrap gap-1"
      role="group"
      aria-label="Color picker"
      onMouseDown={e => e.stopPropagation()}
    >
      {palette.map(c => (
        <button
          key={c.hex}
          type="button"
          aria-label={`Set color to ${c.name}`}
          aria-pressed={obj.color === c.hex}
          title={`Set color to ${c.name}`}
          onClick={e => {
            e.stopPropagation();
            dispatch(updateObject({ id: obj.id, updates: { color: c.hex } }));
          }}
          style={{
            width: 24,
            height: 24,
            borderRadius: '50%',
            backgroundColor: c.hex,
            border: '1.5px solid var(--color-text-secondary)',
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            padding: 0,
          }}
        >
          {obj.color === c.hex && (
            <svg aria-hidden="true" width="12" height="12" viewBox="0 0 12 12" fill="none">
              <path d="M2 6.5 L5 9 L10 3" stroke="#211D3A" strokeWidth="2" strokeLinecap="round" />
            </svg>
          )}
        </button>
      ))}
    </div>
  );

  const ghost = dragGhost && (
    <div
      aria-hidden="true"
      style={{
        position: 'absolute',
        left: dragGhost.x,
        top: dragGhost.y,
        width: obj.width,
        height: obj.height,
        border: '2px dashed var(--color-text-secondary)',
        borderRadius: obj.type === 'circle' ? '50%' : '8px',
        zIndex: 0,
        pointerEvents: 'none',
      }}
    />
  );

  const commonProps = {
    ref: wrapperRef,
    role: 'group' as const,
    'aria-label': accessibleName,
    tabIndex: 0,
    className: 'canvas-object-wrapper',
    onMouseDown: handleMouseDown,
    onKeyDown: handleKeyDown,
    onMouseEnter: () => setHovered(true),
    onMouseLeave: () => setHovered(false),
    onDoubleClick: (e: React.MouseEvent) => {
      e.stopPropagation();
      if (activeTool === 'select' && (obj.type === 'note' || obj.type === 'flashcard')) {
        if (!selectedIds.includes(obj.id)) dispatch(selectOnly(obj.id));
        setIsEditing(true);
      }
    },
    'data-canvas-object': true,
  };

  // === NOTE ===
  if (obj.type === 'note') {
    const labelId = `note-label-${obj.id}`;
    return (
      <>
        {ghost}
        <div {...commonProps} style={{ ...wrapperStyle, backgroundColor: obj.color, padding: 10, display: 'flex', flexDirection: 'column', gap: 6 }}>
          <div className="flex items-center justify-between gap-1" style={{ minHeight: 16 }}>
            <span
              id={labelId}
              className="font-semibold"
              style={{ fontSize: '11px', letterSpacing: '0.03em', color: 'var(--color-text-secondary)' }}
            >
              Note
            </span>
          </div>
          {singleSelected && colorSwatches(NOTE_COLORS)}
          <div className="flex-1 min-h-0">
            {isEditing ? (
              <textarea
                aria-labelledby={labelId}
                className="w-full h-full bg-transparent resize-none"
                style={{
                  fontSize: '16px',
                  lineHeight: 1.5,
                  fontFamily: 'inherit',
                  color: 'var(--color-text-primary)',
                  border: 'none',
                  outline: '2px solid var(--color-primary)',
                  outlineOffset: '2px',
                  borderRadius: 4,
                }}
                value={obj.text || ''}
                onChange={e => dispatch(updateObject({ id: obj.id, updates: { text: e.target.value } }))}
                onBlur={() => setIsEditing(false)}
                onKeyDown={e => {
                  if (e.key === 'Escape') {
                    e.stopPropagation();
                    finishEditing();
                  }
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    finishEditing();
                  }
                }}
                autoFocus
                onMouseDown={e => e.stopPropagation()}
              />
            ) : (
              <div
                className="w-full h-full overflow-hidden whitespace-pre-wrap break-words"
                style={{ fontSize: '16px', lineHeight: 1.5, color: 'var(--color-text-primary)' }}
              >
                {obj.text || (
                  <span style={{ color: 'var(--color-text-secondary)' }}>
                    Double-click or press Enter to add text
                  </span>
                )}
              </div>
            )}
          </div>
          {cornerHandles}
        </div>
      </>
    );
  }

  // === FLASHCARD ===
  if (obj.type === 'flashcard') {
    const sideLabelId = `card-side-${obj.id}`;
    const showingBack = !!obj.flipped;
    const sideValue = showingBack ? obj.back : obj.front;
    return (
      <>
        {ghost}
        <div
          {...commonProps}
          style={{
            ...wrapperStyle,
            backgroundColor: '#FFFFFF',
            border: '1.5px solid var(--color-text-secondary)',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'visible',
          }}
        >
          <div
            className="flex items-center justify-between gap-1 px-2.5 py-1.5"
            style={{ borderBottom: '1px solid var(--color-border)' }}
          >
            <span className="flex items-center gap-1.5">
              <svg aria-hidden="true" width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path
                  d="M11.5 5.5 A5 5 0 0 0 3 3.5 M2.5 8.5 A5 5 0 0 0 11 10.5"
                  stroke="var(--color-primary)"
                  strokeWidth="1.6"
                  strokeLinecap="round"
                />
                <path d="M3 1 L3 4 L6 4" stroke="var(--color-primary)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" fill="none" />
                <path d="M11 13 L11 10 L8 10" stroke="var(--color-primary)" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" fill="none" />
              </svg>
              <span
                id={sideLabelId}
                className="font-semibold"
                style={{ fontSize: '11px', letterSpacing: '0.03em', color: 'var(--color-text-secondary)' }}
              >
                {showingBack ? 'Back' : 'Front'}
              </span>
            </span>
            <button
              type="button"
              className="font-semibold hover:bg-[#EAE6F7]"
              style={{
                fontSize: '12px',
                color: 'var(--color-primary)',
                backgroundColor: '#F3F0FF',
                border: '1px solid var(--color-primary)',
                borderRadius: 6,
                padding: '4px 10px',
                minHeight: 26,
                cursor: 'pointer',
              }}
              onMouseDown={e => e.stopPropagation()}
              onClick={e => {
                e.stopPropagation();
                dispatch(updateObject({ id: obj.id, updates: { flipped: !obj.flipped } }));
              }}
            >
              Flip
            </button>
          </div>
          {singleSelected && (
            <div className="px-2.5 pt-1.5" onMouseDown={e => e.stopPropagation()} />
          )}
          <div className="flex-1 px-2.5 py-2 min-h-0">
            {isEditing ? (
              <textarea
                aria-labelledby={sideLabelId}
                className="w-full h-full bg-transparent resize-none"
                style={{
                  fontSize: '16px',
                  lineHeight: 1.5,
                  fontFamily: 'inherit',
                  color: 'var(--color-text-primary)',
                  border: 'none',
                  outline: '2px solid var(--color-primary)',
                  outlineOffset: '2px',
                  borderRadius: 4,
                }}
                value={sideValue || ''}
                onChange={e =>
                  dispatch(
                    updateObject({
                      id: obj.id,
                      updates: showingBack ? { back: e.target.value } : { front: e.target.value },
                    })
                  )
                }
                onBlur={() => setIsEditing(false)}
                onKeyDown={e => {
                  if (e.key === 'Escape') {
                    e.stopPropagation();
                    finishEditing();
                  }
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault();
                    finishEditing();
                  }
                }}
                autoFocus
                onMouseDown={e => e.stopPropagation()}
              />
            ) : (
              <div
                className="w-full h-full overflow-hidden whitespace-pre-wrap break-words"
                style={{ fontSize: '16px', lineHeight: 1.5, color: 'var(--color-text-primary)' }}
              >
                {sideValue || (
                  <span style={{ color: 'var(--color-text-secondary)' }}>
                    Double-click or press Enter to add {showingBack ? 'back' : 'front'} text
                  </span>
                )}
              </div>
            )}
          </div>
          {cornerHandles}
        </div>
      </>
    );
  }

  // === SHAPES ===
  const shapeSwatches = singleSelected && (
    <div
      style={{ position: 'absolute', top: -40, left: 0, zIndex: 6 }}
      className="bg-white/95 px-2 py-1 shadow-md"
    >
      {colorSwatches(SHAPE_COLORS)}
    </div>
  );

  if (obj.type === 'rectangle' || obj.type === 'circle') {
    return (
      <>
        {ghost}
        <div
          {...commonProps}
          style={{
            ...wrapperStyle,
            backgroundColor: obj.color,
            borderRadius: obj.type === 'circle' ? '50%' : '8px',
          }}
        >
          {shapeSwatches}
          {cornerHandles}
        </div>
      </>
    );
  }

  // arrow
  return (
    <>
      {ghost}
      <div {...commonProps} style={{ ...wrapperStyle, backgroundColor: 'transparent', boxShadow: shadows.slice(1).join(', ') || undefined }}>
        <svg width="100%" height="100%" viewBox="0 0 120 80" preserveAspectRatio="none" aria-hidden="true">
          <line x1="10" y1="40" x2="88" y2="40" stroke={obj.color} strokeWidth="8" strokeLinecap="round" />
          <polygon points="86,24 114,40 86,56" fill={obj.color} />
        </svg>
        {shapeSwatches}
        {cornerHandles}
      </div>
    </>
  );
};

export default CanvasObjectComponent;

// tasks/frontend-productivity-scribblespace/solution/app/src/components/CanvasObject.vue
<script setup lang="ts">
import { ref, computed, watch, nextTick } from 'vue'
import { useAppStore, NOTE_COLORS, SHAPE_COLORS } from '../store'
import type { CanvasObject } from '../types'
import { useEditor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { useMediaQuery } from '@vueuse/core'

const props = defineProps<{
  obj: CanvasObject
  isSelected: boolean
  isSearchHighlight: boolean
  isConnectSource: boolean
  zoom: number
}>()

const store = useAppStore()

const isEditing = ref(false)
const dragGhost = ref<{ x: number, y: number } | null>(null)
const hovered = ref(false)
const wrapperRef = ref<HTMLElement | null>(null)

const singleSelected = computed(() => props.isSelected && store.selectedIds.length === 1)

// Colors
const colors = computed(() => {
  if (props.obj.type === 'note' || props.obj.type === 'flashcard') return NOTE_COLORS
  if (props.obj.type === 'rectangle' || props.obj.type === 'circle' || props.obj.type === 'arrow') return SHAPE_COLORS
  return []
})

// TipTap Editor Setup
const editorText = computed({
  get: () => {
    if (props.obj.type === 'note') return props.obj.text || ''
    if (props.obj.type === 'flashcard') {
      return props.obj.flipped ? (props.obj.back || '') : (props.obj.front || '')
    }
    return ''
  },
  set: (val) => {
    if (props.obj.type === 'note') {
      store.updateObject({ id: props.obj.id, updates: { text: val } })
    } else if (props.obj.type === 'flashcard') {
      if (props.obj.flipped) {
         store.updateObject({ id: props.obj.id, updates: { back: val } })
      } else {
         store.updateObject({ id: props.obj.id, updates: { front: val } })
      }
    }
  }
})

const editor = useEditor({
  content: editorText.value,
  extensions: [StarterKit],
  onUpdate: ({ editor }) => {
    const txt = editor.getText()
    if (txt.length > 8000) {
       store.announce(`${props.obj.type === 'note' ? 'text' : (props.obj.flipped ? 'back' : 'front')} too long (max 8000 chars)`)
       editor.commands.setContent(editorText.value)
    } else {
       editorText.value = editor.getHTML()
    }
  }
})

const renderEditor = useEditor({
  content: editorText.value,
  editable: false,
  extensions: [StarterKit],
})

watch(editorText, (val) => {
   if (!isEditing.value) {
      renderEditor.value?.commands.setContent(val)
   }
})

watch(() => isEditing.value, (val) => {
  if (val) {
    editor.value?.commands.setContent(editorText.value)
    editor.value?.commands.focus()
  } else {
    renderEditor.value?.commands.setContent(editorText.value)
  }
})

const startEditing = () => {
  if (store.activeTool === 'select' && (props.obj.type === 'note' || props.obj.type === 'flashcard')) {
     if (!store.selectedIds.includes(props.obj.id)) {
        store.selectOnly(props.obj.id)
     }
     isEditing.value = true
  }
}

const finishEditing = () => {
  isEditing.value = false
}

// Dragging
let isDragging = false
let startDragWorld = { x: 0, y: 0 }
let startObjWorld = { x: 0, y: 0 }

const handleMouseDown = (e: MouseEvent) => {
  if ((e.target as HTMLElement).closest('.resize-handle') || (e.target as HTMLElement).closest('button') || isEditing.value) {
    return
  }

  if (store.activeTool === 'connect') {
    if (store.connectFromId) {
      store.addConnector({ fromId: store.connectFromId, toId: props.obj.id })
    } else {
      store.setConnectFrom(props.obj.id)
    }
    e.stopPropagation()
    return
  }

  e.stopPropagation()

  if (e.shiftKey) {
    store.toggleSelect(props.obj.id)
    return
  }

  if (!store.selectedIds.includes(props.obj.id)) {
    store.selectOnly(props.obj.id)
  }

  isDragging = true
  dragGhost.value = { x: props.obj.x, y: props.obj.y }
  startObjWorld = { x: props.obj.x, y: props.obj.y }
  startDragWorld = { x: e.clientX, y: e.clientY }

  const onMove = (me: MouseEvent) => {
    if (!isDragging) return
    const dx = (me.clientX - startDragWorld.x) / store.canvasView.zoom
    const dy = (me.clientY - startDragWorld.y) / store.canvasView.zoom
    dragGhost.value = { x: startObjWorld.x + dx, y: startObjWorld.y + dy }
  }

  const onUp = (me: MouseEvent) => {
    isDragging = false
    document.removeEventListener('mousemove', onMove)
    document.removeEventListener('mouseup', onUp)

    if (dragGhost.value) {
       const dx = dragGhost.value.x - props.obj.x
       const dy = dragGhost.value.y - props.obj.y

       if (Math.abs(dx) > 1 || Math.abs(dy) > 1) {
          if (store.selectedIds.length > 1) {
             store._saveHistory()
             store.selectedIds.forEach(id => {
                store.moveObject({ id, dx, dy })
             })
          } else {
             store._saveHistory()
             store.moveObject({ id: props.obj.id, dx, dy })
          }
       }
       dragGhost.value = null
    }
  }

  document.addEventListener('mousemove', onMove)
  document.addEventListener('mouseup', onUp)
}

// Resizing
const handleResizeMouseDown = (e: MouseEvent, corner: 'tl'|'tr'|'bl'|'br') => {
  e.stopPropagation()
  e.preventDefault()

  let startW = props.obj.width
  let startH = props.obj.height
  let startX = props.obj.x
  let startY = props.obj.y
  let startMouseX = e.clientX
  let startMouseY = e.clientY

  const onMove = (me: MouseEvent) => {
    const dx = (me.clientX - startMouseX) / store.canvasView.zoom
    const dy = (me.clientY - startMouseY) / store.canvasView.zoom

    const minW = (props.obj.type === 'note' || props.obj.type === 'flashcard') ? 120 : 48
    const minH = (props.obj.type === 'note' || props.obj.type === 'flashcard') ? 96 : 48

    let newW = startW
    let newH = startH
    let newX = startX
    let newY = startY

    if (corner.includes('r')) newW = Math.max(minW, startW + dx)
    if (corner.includes('l')) {
       newW = Math.max(minW, startW - dx)
       newX = startX + (startW - newW)
    }
    if (corner.includes('b')) newH = Math.max(minH, startH + dy)
    if (corner.includes('t')) {
       newH = Math.max(minH, startH - dy)
       newY = startY + (startH - newH)
    }

    store.updateObject({ id: props.obj.id, updates: { width: newW, height: newH, x: newX, y: newY } })
  }

  const onUp = () => {
    document.removeEventListener('mousemove', onMove)
    document.removeEventListener('mouseup', onUp)
    store._saveHistory()
  }

  document.addEventListener('mousemove', onMove)
  document.addEventListener('mouseup', onUp)
}

const handleKeyDown = (e: KeyboardEvent) => {
  if (isEditing.value) return
  if (!singleSelected.value) return

  if (e.key === 'Enter') {
     startEditing()
     return
  }

  const step = 24
  let handled = true
  if (e.key === 'ArrowUp') store.moveObject({ id: props.obj.id, dx: 0, dy: -step })
  else if (e.key === 'ArrowDown') store.moveObject({ id: props.obj.id, dx: 0, dy: step })
  else if (e.key === 'ArrowLeft') store.moveObject({ id: props.obj.id, dx: -step, dy: 0 })
  else if (e.key === 'ArrowRight') store.moveObject({ id: props.obj.id, dx: step, dy: 0 })
  else handled = false

  if (handled) {
     e.stopPropagation()
     e.preventDefault()
  }
}

const prefersReducedMotion = useMediaQuery('(prefers-reduced-motion: reduce)')

// Vueuse Motion config for entrance
const motionConfig = computed(() => {
  if (prefersReducedMotion.value) return undefined;
  return {
    initial: { opacity: 0, scale: 0.8 },
    enter: { opacity: 1, scale: 1, transition: { type: 'spring', stiffness: 250, damping: 25 } }
  }
})
</script>

<template>
  <div>
    <!-- Ghost -->
    <div
      v-if="dragGhost"
      aria-hidden="true"
      :style="{
        position: 'absolute',
        left: `${dragGhost.x}px`,
        top: `${dragGhost.y}px`,
        width: `${obj.width}px`,
        height: `${obj.height}px`,
        border: '2px dashed var(--color-text-secondary)',
        borderRadius: obj.type === 'circle' ? '50%' : '8px',
        zIndex: 0,
        pointerEvents: 'none'
      }"
    ></div>

    <!-- Wrapper -->
    <div
      ref="wrapperRef"
      role="group"
      :aria-label="obj.type"
      tabindex="0"
      class="canvas-object-wrapper group transition-[transform] duration-300"
      v-motion="motionConfig"
      :data-canvas-object="true"
      :style="{
        position: 'absolute',
        left: `${obj.x}px`,
        top: `${obj.y}px`,
        width: `${obj.width}px`,
        height: `${obj.height}px`,
        zIndex: obj.zIndex,
        boxShadow: isSearchHighlight ? '0 0 0 4px #E0A030' :
                   isConnectSource ? '0 0 0 3px #3F9E6E' :
                   isSelected ? '0 0 0 3px #6D5BD0' : '0 2px 8px rgba(0,0,0,0.1)',
        borderRadius: obj.type === 'circle' ? '50%' : '8px',
        backgroundColor: obj.type === 'flashcard' ? '#FFFFFF' : obj.color,
        display: 'flex',
        flexDirection: 'column',
        transform: (!prefersReducedMotion && obj.type === 'flashcard' && obj.flipped) ? 'rotateY(180deg)' : 'rotateY(0deg)',
      }"
      @mousedown="handleMouseDown"
      @mouseenter="hovered = true"
      @mouseleave="hovered = false"
      @dblclick.stop="startEditing"
      @keydown="handleKeyDown"
    >

      <!-- Arrow specifics -->
      <template v-if="obj.type === 'arrow'">
        <svg width="100%" height="100%" viewBox="0 0 120 80" preserveAspectRatio="none" aria-hidden="true" class="absolute inset-0 z-0">
          <line x1="10" y1="40" x2="88" y2="40" :stroke="obj.color" stroke-width="8" stroke-linecap="round" />
          <polygon points="86,24 114,40 86,56" :fill="obj.color" />
        </svg>
      </template>

      <!-- Note / Flashcard header -->
      <div v-if="obj.type === 'note' || obj.type === 'flashcard'" class="flex items-center justify-between gap-1 p-2 border-b border-gray-200 z-10 shrink-0" :style="{ transform: (!prefersReducedMotion && obj.type === 'flashcard' && obj.flipped) ? 'rotateY(180deg)' : 'none' }">
        <span class="text-[11px] font-semibold text-gray-500 uppercase tracking-wider">
           {{ obj.type === 'flashcard' ? (obj.flipped ? 'Back' : 'Front') : 'Note' }}
        </span>
        <button v-if="obj.type === 'flashcard'" @click.stop="store.updateObject({id: obj.id, updates: { flipped: !obj.flipped }})" class="text-xs text-purple-600 bg-purple-50 px-2 py-1 rounded border border-purple-600 hover:bg-purple-100">
           Flip
        </button>
      </div>

      <!-- Colors Swatch -->
      <div v-if="singleSelected" class="absolute -top-[45px] left-0 bg-white shadow-md p-1 rounded z-20 flex gap-1" :style="{ transform: (!prefersReducedMotion && obj.type === 'flashcard' && obj.flipped) ? 'rotateY(180deg)' : 'none' }">
         <button
            v-for="c in colors"
            :key="c.hex"
            type="button"
            class="w-6 h-6 rounded-full border border-gray-300 focus:ring-2 focus:ring-offset-1 focus:ring-purple-500"
            :style="{ backgroundColor: c.hex }"
            @mousedown.stop
            @click="store.updateObject({ id: obj.id, updates: { color: c.hex } })"
            :title="c.name"
            :aria-label="c.name"
         >
            <div v-if="obj.color === c.hex" class="flex items-center justify-center w-full h-full">
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M2 6.5 L5 9 L10 3" stroke="#000" stroke-width="2" stroke-linecap="round"/></svg>
            </div>
         </button>
      </div>

      <!-- Text Area -->
      <div v-if="(obj.type === 'note' || obj.type === 'flashcard') && isEditing" class="flex-1 p-2 relative z-10 bg-white/50 overflow-hidden flex flex-col" :style="{ transform: (!prefersReducedMotion && obj.type === 'flashcard' && obj.flipped) ? 'rotateY(180deg)' : 'none' }">
         <!-- Format Toolbar -->
         <div class="flex gap-1 mb-1 shrink-0">
            <button type="button" @mousedown.prevent="editor?.chain().focus().toggleBold().run()" class="px-2 py-1 bg-white border rounded text-xs font-bold" :class="{ 'bg-gray-200': editor?.isActive('bold') }">B</button>
            <button type="button" @mousedown.prevent="editor?.chain().focus().toggleItalic().run()" class="px-2 py-1 bg-white border rounded text-xs italic" :class="{ 'bg-gray-200': editor?.isActive('italic') }">I</button>
            <button type="button" @mousedown.prevent="editor?.chain().focus().toggleBulletList().run()" class="px-2 py-1 bg-white border rounded text-xs" :class="{ 'bg-gray-200': editor?.isActive('bulletList') }">•</button>
            <button type="button" @mousedown.prevent="editor?.chain().focus().undo().run()" class="px-2 py-1 bg-white border rounded text-xs ml-auto">Undo</button>
            <button type="button" @mousedown.prevent="editor?.chain().focus().redo().run()" class="px-2 py-1 bg-white border rounded text-xs">Redo</button>
         </div>
         <!-- Editor -->
         <editor-content :editor="editor" class="flex-1 overflow-auto outline-none prose prose-sm focus:ring-2 focus:ring-purple-500 rounded bg-transparent" />
      </div>

      <div v-else-if="(obj.type === 'note' || obj.type === 'flashcard') && !isEditing" class="flex-1 p-2 overflow-hidden break-words z-10" :style="{ transform: (!prefersReducedMotion && obj.type === 'flashcard' && obj.flipped) ? 'rotateY(180deg)' : 'none' }">
        <editor-content :editor="renderEditor" class="w-full h-full outline-none prose prose-sm" />
        <span v-if="!editorText" class="text-gray-500 pointer-events-none absolute top-2 left-2">Double-click to edit...</span>
      </div>

      <!-- Resize Handles -->
      <template v-if="singleSelected">
        <div @mousedown="e => handleResizeMouseDown(e, 'tl')" class="resize-handle absolute -top-1.5 -left-1.5 w-3 h-3 bg-white border-2 border-[#6D5BD0] cursor-nwse-resize z-20" :class="{'rounded-full': obj.type === 'circle'}" />
        <div @mousedown="e => handleResizeMouseDown(e, 'tr')" class="resize-handle absolute -top-1.5 -right-1.5 w-3 h-3 bg-white border-2 border-[#6D5BD0] cursor-nesw-resize z-20" :class="{'rounded-full': obj.type === 'circle'}" />
        <div @mousedown="e => handleResizeMouseDown(e, 'bl')" class="resize-handle absolute -bottom-1.5 -left-1.5 w-3 h-3 bg-white border-2 border-[#6D5BD0] cursor-nesw-resize z-20" :class="{'rounded-full': obj.type === 'circle'}" />
        <div @mousedown="e => handleResizeMouseDown(e, 'br')" class="resize-handle absolute -bottom-1.5 -right-1.5 w-3 h-3 bg-white border-2 border-[#6D5BD0] cursor-nwse-resize z-20" :class="{'rounded-full': obj.type === 'circle'}" />
      </template>

    </div>
  </div>
</template>

<style scoped>
.canvas-object-wrapper {
  outline: none;
  transform-style: preserve-3d;
}
.resize-handle {
  pointer-events: auto;
}
/* Prose styling for tiptap */
:deep(.ProseMirror) {
  outline: none;
  height: 100%;
}
:deep(.ProseMirror p) {
  margin: 0;
}
:deep(.ProseMirror ul) {
  padding-left: 1.2rem;
  margin: 0;
}
</style>
