// tasks/frontend-productivity-scribblespace/solution/app/src/components/MiniMap.tsx
import React, { useMemo } from 'react';
import type { CanvasObject } from '../types';
import { useAppDispatch, useAppSelector } from '../hooks';
import { setCanvasView } from '../slices/appSlice';

interface MiniMapProps {
  objects: CanvasObject[];
  viewportWidth: number;
  viewportHeight: number;
}

const MiniMap: React.FC<MiniMapProps> = ({ objects, viewportWidth, viewportHeight }) => {
  const dispatch = useAppDispatch();
  const canvasView = useAppSelector(s => s.app.canvasView);

  const bounds = useMemo(() => {
    if (objects.length === 0) {
      return { minX: -500, minY: -300, maxX: 500, maxY: 300, width: 1000, height: 600 };
    }
    let minX = Infinity;
    let minY = Infinity;
    let maxX = -Infinity;
    let maxY = -Infinity;
    for (const obj of objects) {
      minX = Math.min(minX, obj.x);
      minY = Math.min(minY, obj.y);
      maxX = Math.max(maxX, obj.x + obj.width);
      maxY = Math.max(maxY, obj.y + obj.height);
    }
    const pad = 150;
    minX -= pad;
    minY -= pad;
    maxX += pad;
    maxY += pad;
    return { minX, minY, maxX, maxY, width: maxX - minX, height: maxY - minY };
  }, [objects]);

  const isNarrow = viewportWidth < 480;
  const mapWidth = isNarrow ? 120 : 170;
  const mapHeight = isNarrow ? 78 : 110;
  const scale = Math.min(mapWidth / bounds.width, mapHeight / bounds.height);

  const viewLeft = -canvasView.panX / canvasView.zoom;
  const viewTop = -canvasView.panY / canvasView.zoom;
  const viewWidth = viewportWidth / canvasView.zoom;
  const viewHeight = viewportHeight / canvasView.zoom;

  const vpX = (viewLeft - bounds.minX) * scale;
  const vpY = (viewTop - bounds.minY) * scale;
  const vpW = viewWidth * scale;
  const vpH = viewHeight * scale;

  const centerOn = (worldX: number, worldY: number) => {
    dispatch(
      setCanvasView({
        ...canvasView,
        panX: -(worldX * canvasView.zoom - viewportWidth / 2),
        panY: -(worldY * canvasView.zoom - viewportHeight / 2),
      })
    );
  };

  const handleClick = (e: React.MouseEvent<HTMLButtonElement>) => {
    if (e.detail === 0) {
      // Keyboard activation: center the view on the middle of the content
      centerOn((bounds.minX + bounds.maxX) / 2, (bounds.minY + bounds.maxY) / 2);
      return;
    }
    const rect = e.currentTarget.getBoundingClientRect();
    const clickX = (e.clientX - rect.left - 4) / scale + bounds.minX;
    const clickY = (e.clientY - rect.top - 4) / scale + bounds.minY;
    centerOn(clickX, clickY);
  };

  const getObjectColor = (obj: CanvasObject): string => {
    if (obj.type === 'flashcard') return '#FFFFFF';
    return obj.color || '#6D5BD0';
  };

  return (
    <button
      type="button"
      aria-label="Board overview map — activate to recenter the view"
      title="Board overview map"
      data-canvas-ui
      onClick={handleClick}
      onMouseDown={e => e.stopPropagation()}
      className="bg-white/95 shadow-md overflow-hidden"
      style={{
        width: mapWidth + 8,
        height: mapHeight + 8,
        borderRadius: '12px',
        border: '1.5px solid var(--color-text-secondary)',
        position: 'absolute',
        bottom: 12,
        right: 12,
        zIndex: 30,
        cursor: 'pointer',
        padding: 0,
      }}
    >
      <svg aria-hidden="true" width={mapWidth + 8} height={mapHeight + 8}>
        <g transform="translate(4, 4)">
          <rect width={mapWidth} height={mapHeight} fill="#F4F2FB" rx="6" />
          {objects.map(obj => (
            <rect
              key={obj.id}
              x={(obj.x - bounds.minX) * scale}
              y={(obj.y - bounds.minY) * scale}
              width={Math.max(3, obj.width * scale)}
              height={Math.max(3, obj.height * scale)}
              fill={getObjectColor(obj)}
              stroke="rgba(33, 29, 58, 0.3)"
              strokeWidth={0.5}
              rx={obj.type === 'circle' ? Math.min(obj.width, obj.height) * scale * 0.5 : 1.5}
            />
          ))}
          <rect
            x={Math.max(0, Math.min(mapWidth - 4, vpX))}
            y={Math.max(0, Math.min(mapHeight - 4, vpY))}
            width={Math.min(mapWidth, Math.max(6, vpW))}
            height={Math.min(mapHeight, Math.max(6, vpH))}
            fill="rgba(109, 91, 208, 0.12)"
            stroke="#6D5BD0"
            strokeWidth={1.5}
            rx={2}
          />
        </g>
      </svg>
    </button>
  );
};

export default MiniMap;

// tasks/frontend-productivity-scribblespace/solution/app/src/components/MiniMap.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore } from '../store'
import type { CanvasObject } from '../types'

const props = defineProps<{
  objects: CanvasObject[]
  viewportWidth: number
  viewportHeight: number
}>()

const store = useAppStore()

// MiniMap scale logic
const bounds = computed(() => {
  if (props.objects.length === 0) {
    return { minX: 0, minY: 0, maxX: 1000, maxY: 1000 }
  }
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
  for (const obj of props.objects) {
    minX = Math.min(minX, obj.x)
    minY = Math.min(minY, obj.y)
    maxX = Math.max(maxX, obj.x + obj.width)
    maxY = Math.max(maxY, obj.y + obj.height)
  }
  // Add some padding
  const padding = 200
  return {
    minX: minX - padding,
    minY: minY - padding,
    maxX: maxX + padding,
    maxY: maxY + padding
  }
})

const mapWidth = 200
const mapHeight = 140

const scale = computed(() => {
  const w = bounds.value.maxX - bounds.value.minX
  const h = bounds.value.maxY - bounds.value.minY
  return Math.min(mapWidth / Math.max(w, 1), mapHeight / Math.max(h, 1))
})

const getMapRect = (x: number, y: number, w: number, h: number) => {
  return {
    left: (x - bounds.value.minX) * scale.value,
    top: (y - bounds.value.minY) * scale.value,
    width: w * scale.value,
    height: h * scale.value
  }
}

const viewportRect = computed(() => {
  const panX = store.canvasView.panX
  const panY = store.canvasView.panY
  const zoom = store.canvasView.zoom

  const vX = -panX / zoom
  const vY = -panY / zoom
  const vW = props.viewportWidth / zoom
  const vH = props.viewportHeight / zoom

  return getMapRect(vX, vY, vW, vH)
})

const handleMapClick = (e: MouseEvent) => {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
  const clickX = e.clientX - rect.left
  const clickY = e.clientY - rect.top

  // World pos of click
  const worldX = clickX / scale.value + bounds.value.minX
  const worldY = clickY / scale.value + bounds.value.minY

  // Recenter view
  store.setCanvasView({
     panX: -worldX * store.canvasView.zoom + props.viewportWidth / 2,
     panY: -worldY * store.canvasView.zoom + props.viewportHeight / 2
  })
}
</script>

<template>
  <div
    class="absolute bottom-4 right-4 bg-white border border-gray-300 shadow-md overflow-hidden z-[45]"
    style="width: 200px; height: 140px; border-radius: 12px; cursor: pointer;"
    data-canvas-ui="true"
    @mousedown.stop="handleMapClick"
    aria-label="Mini-map"
    title="Mini-map (click to recenter)"
  >
    <div
      v-for="obj in objects"
      :key="`mm-${obj.id}`"
      class="absolute opacity-80"
      :style="{
        left: `${getMapRect(obj.x, obj.y, obj.width, obj.height).left}px`,
        top: `${getMapRect(obj.x, obj.y, obj.width, obj.height).top}px`,
        width: `${Math.max(1, getMapRect(obj.x, obj.y, obj.width, obj.height).width)}px`,
        height: `${Math.max(1, getMapRect(obj.x, obj.y, obj.width, obj.height).height)}px`,
        backgroundColor: obj.type === 'flashcard' ? '#DDD' : obj.color,
        borderRadius: obj.type === 'circle' ? '50%' : '1px'
      }"
    ></div>

    <div
      class="absolute border-2 border-[#6D5BD0] bg-[#6D5BD0]/10 pointer-events-none"
      :style="{
        left: `${viewportRect.left}px`,
        top: `${viewportRect.top}px`,
        width: `${viewportRect.width}px`,
        height: `${viewportRect.height}px`
      }"
    ></div>
  </div>
</template>
