// tasks/frontend-creative-tools-portfolioframe/solution/app/src/components/CommandPalette.tsx
import { component$, useSignal, useVisibleTask$, $, useStore, useTask$ } from '@builder.io/qwik';
import type { PortfolioState, HistoryManager, ThemeName, DensityMode } from '../types';
import { SECTION_LABELS } from '../types';
import { setTheme, setDensity, loadDraft } from '../store';

interface CommandPaletteProps {
  state: PortfolioState;
  history: HistoryManager;
  onOpenExport: () => void;
}

interface CommandResult {
  id: string;
  label: string;
  kind: string;
  action: () => void;
}

export const CommandPalette = component$<CommandPaletteProps>(({ state, history, onOpenExport }) => {
  const isOpen = useSignal(false);
  const query = useSignal('');
  const selectedIndex = useSignal(0);
  const inputRef = useSignal<HTMLInputElement>();

  const results = useStore<{ items: CommandResult[] }>({ items: [] });

  useTask$(({ track }) => {
    track(() => query.value);
    track(() => state.drafts.length);
    track(() => isOpen.value);

    if (!isOpen.value) {
      results.items = [];
      return;
    }

    const q = query.value.toLowerCase().trim();
    const allCommands: CommandResult[] = [];

    // Actions
    allCommands.push({
      id: 'action-export',
      label: 'Export package',
      kind: 'Action',
      action: () => { isOpen.value = false; onOpenExport(); }
    });

    // Layout Presets
    allCommands.push({
      id: 'preset-compact',
      label: 'Compact Stack',
      kind: 'Layout Preset',
      action: () => {
        setDensity(state, 'compact');
        isOpen.value = false;
      }
    });
    
    // Themes
    const themes: ThemeName[] = ['sunrise', 'slate', 'forest', 'blossom'];
    themes.forEach(t => {
      allCommands.push({
        id: `theme-${t}`,
        label: `Theme: ${t}`,
        kind: 'Theme',
        action: () => {
          setTheme(state, t);
          isOpen.value = false;
        }
      });
    });

    // Drafts
    state.drafts.forEach(d => {
      allCommands.push({
        id: `draft-${d.name}`,
        label: `Load Draft: ${d.name}`,
        kind: 'Draft',
        action: () => {
          loadDraft(state, history, d.name);
          isOpen.value = false;
        }
      });
    });
    
    // Sections (Scroll to)
    Object.entries(SECTION_LABELS).forEach(([key, label]) => {
      allCommands.push({
        id: `section-${key}`,
        label: `Go to ${label}`,
        kind: 'Section',
        action: () => {
          isOpen.value = false;
          const el = Array.from(document.querySelectorAll('h2, h1')).find(
            (h) => (h.textContent ?? '').trim().toLowerCase() === label.toLowerCase()
          );
          if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
      });
    });

    if (q === '') {
      results.items = allCommands;
    } else {
      results.items = allCommands.filter(c => 
        c.label.toLowerCase().includes(q) || c.kind.toLowerCase().includes(q)
      );
    }
    selectedIndex.value = 0;
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ cleanup }) => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
        e.preventDefault();
        isOpen.value = !isOpen.value;
        if (isOpen.value) {
            query.value = '';
            setTimeout(() => inputRef.value?.focus(), 50);
        }
      } else if (isOpen.value) {
        if (e.key === 'Escape') {
          isOpen.value = false;
        } else if (e.key === 'ArrowDown') {
          e.preventDefault();
          selectedIndex.value = Math.min(selectedIndex.value + 1, results.items.length - 1);
        } else if (e.key === 'ArrowUp') {
          e.preventDefault();
          selectedIndex.value = Math.max(selectedIndex.value - 1, 0);
        } else if (e.key === 'Enter') {
          e.preventDefault();
          if (results.items.length > 0 && results.items[selectedIndex.value]) {
            results.items[selectedIndex.value].action();
          }
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    cleanup(() => window.removeEventListener('keydown', handleKeyDown));
  });

  if (!isOpen.value) return null;

  return (
    <div
      class="fixed inset-0 z-[100] flex items-start justify-center pt-[15vh] p-4"
      style={{ background: 'rgba(0,0,0,0.5)' }}
    >
      <div
        class="w-full max-w-xl bg-white rounded-xl shadow-2xl overflow-hidden flex flex-col"
        style={{ borderColor: 'var(--color-border)', borderWidth: '1px' }}
        role="dialog"
        aria-modal="true"
        tabIndex={-1}
      >
        <div class="p-3 border-b flex items-center" style={{ borderColor: 'var(--color-border)' }}>
          <span class="text-gray-400 mr-2">🔍</span>
          <input
            ref={inputRef}
            type="text"
            class="w-full text-base border-0 focus:ring-0 bg-transparent"
            placeholder="Search commands, presets, drafts..."
            value={query.value}
            onInput$={(e) => { query.value = (e.target as HTMLInputElement).value; }}
            autoFocus
          />
        </div>
        <div class="max-h-80 overflow-y-auto p-2">
          {results.items.length > 0 ? (
            <div class="space-y-1">
              {results.items.map((res, idx) => (
                <button
                  key={res.id}
                  class={`w-full text-left flex items-center justify-between p-2 rounded-lg ${
                    idx === selectedIndex.value ? 'bg-violet-50 text-violet-900' : 'hover:bg-gray-50'
                  }`}
                  onClick$={() => res.action()}
                  onMouseEnter$={() => { selectedIndex.value = idx; }}
                >
                  <span class="font-medium text-sm">{res.label}</span>
                  <span class="text-xs text-gray-500 bg-gray-100 px-2 py-0.5 rounded">
                    {res.kind}
                  </span>
                </button>
              ))}
            </div>
          ) : (
            <div class="p-4 text-center text-sm text-gray-500">
              No matches found for "{query.value}"
            </div>
          )}
        </div>
      </div>
    </div>
  );
});

// tasks/frontend-landing-l1-network-marketing/solution/app/src/components/CommandPalette.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useStore } from '@nanostores/react';
import { $commandPaletteOpen, $eventsManagerOpen, $exportCatalogOpen } from '../store';
import { MagnifyingGlass } from 'phosphor-react';

const destinations = [
  { id: 'marketing-home', label: 'Marketing Home', action: () => document.getElementById('chrome')?.scrollIntoView({ behavior: 'smooth' }) },
  { id: 'events-manager', label: 'Events Manager', action: () => $eventsManagerOpen.set(true) },
  { id: 'global-events', label: 'Global Events', action: () => { $eventsManagerOpen.set(false); document.getElementById('events')?.scrollIntoView({ behavior: 'smooth' }) } },
  { id: 'export-catalog', label: 'Export Catalog', action: () => $exportCatalogOpen.set(true) },
  { id: 'session-leads', label: 'Session Leads', action: () => document.getElementById('session-leads-section')?.scrollIntoView({ behavior: 'smooth' }) },
];

export default function CommandPalette() {
  const isOpen = useStore($commandPaletteOpen);
  const [query, setQuery] = useState('');
  const [activeIndex, setActiveIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  const filtered = destinations.filter(d => d.label.toLowerCase().includes(query.toLowerCase()));

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 100);
      setQuery('');
      setActiveIndex(0);
    }
  }, [isOpen]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;
      if (e.key === 'Escape') {
        $commandPaletteOpen.set(false);
      } else if (e.key === 'ArrowDown') {
        e.preventDefault();
        setActiveIndex(prev => (prev + 1) % filtered.length);
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        setActiveIndex(prev => (prev - 1 + filtered.length) % filtered.length);
      } else if (e.key === 'Enter' && filtered.length > 0) {
        e.preventDefault();
        filtered[activeIndex].action();
        $commandPaletteOpen.set(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, filtered, activeIndex]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-[20vh] bg-black/60 backdrop-blur-sm transition-opacity" role="dialog" aria-modal="true">
      <div className="bg-surface w-full max-w-lg rounded-xl shadow-2xl overflow-hidden border border-white/10 mx-4">
        <div className="flex items-center p-4 border-b border-white/10">
          <MagnifyingGlass size={20} className="text-gray-400 mr-3" />
          <input
            ref={inputRef}
            type="text"
            className="w-full bg-transparent border-none outline-none text-lg text-current"
            placeholder="Search commands..."
            value={query}
            onChange={e => { setQuery(e.target.value); setActiveIndex(0); }}
          />
        </div>
        <ul className="max-h-64 overflow-y-auto py-2">
          {filtered.length === 0 ? (
            <li className="px-4 py-3 text-gray-500 text-center">No results found</li>
          ) : (
            filtered.map((dest, i) => (
              <li key={dest.id}>
                <button
                  type="button"
                  className={`w-full text-left px-4 py-3 transition-colors focus:outline-none ${i === activeIndex ? 'bg-accent/20 text-accent font-medium' : 'hover:bg-white/5'}`}
                  onClick={() => { dest.action(); $commandPaletteOpen.set(false); }}
                  onMouseEnter={() => setActiveIndex(i)}
                >
                  {dest.label}
                </button>
              </li>
            ))
          )}
        </ul>
      </div>
    </div>
  );
}
