// tasks/frontend-creative-tools-frameflick/solution/app/src/components/CommandPalette.vue
<template>
  <div class="palette-overlay" @click.self="close">
    <div
      ref="dialogEl"
      class="palette-dialog"
      role="dialog"
      aria-modal="true"
      aria-label="Command palette"
      @keydown="onKeydown"
    >
      <label class="sr-only" for="palette-filter">Filter commands</label>
      <input
        id="palette-filter"
        ref="filterEl"
        v-model="filter"
        class="palette-filter"
        type="text"
        placeholder="Type a command… (presets, snapshots, views, export)"
        autocomplete="off"
      />
      <ul v-if="visible.length > 0" class="palette-list" role="listbox" aria-label="Commands">
        <li
          v-for="(cmd, i) in visible"
          :key="cmd.id"
          role="option"
          :aria-selected="i === cursor"
          class="palette-item"
          :class="{ active: i === cursor }"
          @click="run(cmd)"
          @mouseenter="cursor = i"
        >
          <span class="cmd-icon" aria-hidden="true">{{ cmd.icon }}</span>
          <span class="cmd-label">{{ cmd.label }}</span>
          <span class="cmd-group">{{ cmd.group }}</span>
        </li>
      </ul>
      <div v-else class="palette-empty">No matching commands.</div>
      <div class="palette-hint" aria-hidden="true">↑↓ navigate · Enter run · Esc close</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useCanvasStore } from '../stores/canvas'
import { usePresetsStore } from '../stores/presets'
import { useSnapshotsStore } from '../stores/snapshots'
import { useHistoryStore } from '../stores/history'
import { useAnnouncer } from '../stores/announcer'

interface Command {
  id: string
  icon: string
  label: string
  group: string
  action: () => void
}

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'view', view: 'editor' | 'collab'): void
}>()

const canvasStore = useCanvasStore()
const presetsStore = usePresetsStore()
const snapshotsStore = useSnapshotsStore()
const history = useHistoryStore()
const announcer = useAnnouncer()

const filter = ref('')
const cursor = ref(0)
const filterEl = ref<HTMLInputElement | null>(null)
const dialogEl = ref<HTMLElement | null>(null)
let previouslyFocused: HTMLElement | null = null

const commands = computed<Command[]>(() => {
  const list: Command[] = [
    { id: 'view-editor', icon: '🖌️', label: 'Go to Editor', group: 'Views', action: () => emit('view', 'editor') },
    { id: 'view-collab', icon: '🤝', label: 'Go to Collaboration', group: 'Views', action: () => emit('view', 'collab') },
    { id: 'act-undo', icon: '↩', label: 'Undo last style change', group: 'Actions', action: () => history.undo() },
    { id: 'act-redo', icon: '↪', label: 'Redo style change', group: 'Actions', action: () => history.redo() },
    { id: 'act-reset', icon: '♻️', label: 'Reset style to upload defaults', group: 'Actions', action: () => { history.markDiscrete(); canvasStore.resetStyle() } },
    { id: 'act-copy', icon: '📄', label: 'Copy settings', group: 'Actions', action: () => history.copySettings() },
  ]
  for (const p of presetsStore.presets) {
    list.push({
      id: `preset-${p.id}`,
      icon: '🎨',
      label: `Apply preset “${p.name}”`,
      group: 'Saved presets',
      action: () => { history.markDiscrete(); canvasStore.applySettings(p.settings); canvasStore.showingBefore = false },
    })
  }
  for (const s of snapshotsStore.snapshots) {
    list.push({
      id: `snapshot-${s.id}`,
      icon: '📸',
      label: `Apply snapshot “${s.name}”`,
      group: 'Snapshots',
      action: () => { history.markDiscrete(); canvasStore.applySettings(s.settings); canvasStore.showingBefore = false },
    })
  }
  return list
})

const visible = computed(() => {
  const q = filter.value.trim().toLowerCase()
  if (!q) return commands.value
  return commands.value.filter(c => c.label.toLowerCase().includes(q) || c.group.toLowerCase().includes(q))
})

// The filtered list is recomputed as the query changes, so re-anchor the
// selection to the first match — a stale index would run the wrong command (or
// none, once the list shrinks below it).
watch(filter, () => { cursor.value = 0 })

function run(cmd: Command) {
  cmd.action()
  announcer.announce(cmd.label)
  close()
}

function onKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    e.preventDefault()
    close()
    return
  }
  if (e.key === 'ArrowDown') {
    e.preventDefault()
    cursor.value = Math.min(cursor.value + 1, visible.value.length - 1)
  } else if (e.key === 'ArrowUp') {
    e.preventDefault()
    cursor.value = Math.max(cursor.value - 1, 0)
  } else if (e.key === 'Enter') {
    e.preventDefault()
    const cmd = visible.value[cursor.value]
    if (cmd) run(cmd)
  }
}

function close() {
  emit('close')
}

onMounted(async () => {
  previouslyFocused = document.activeElement as HTMLElement | null
  await nextTick()
  filterEl.value?.focus()
})

onBeforeUnmount(() => {
  if (previouslyFocused && typeof previouslyFocused.focus === 'function' && document.contains(previouslyFocused)) {
    previouslyFocused.focus()
  }
})
</script>

<style scoped>
.palette-overlay {
  position: fixed;
  inset: 0;
  background: rgba(113, 63, 18, 0.45);
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding: 15vh 16px 16px;
  z-index: 300;
}
.palette-dialog {
  width: 100%;
  max-width: 520px;
  background: #fffbf0;
  border: 2px solid #92400e;
  border-radius: 8px;
  box-shadow: 0 24px 64px rgba(113, 63, 18, 0.4);
  overflow: hidden;
  animation: dialog-in 0.16s ease-out;
}
.palette-filter {
  width: 100%;
  padding: 16px;
  border: none;
  border-bottom: 1px solid #f3d89a;
  background: #fff;
  font-size: 14px;
  color: #713F12;
}
.palette-filter:focus { outline: none; }
.palette-list {
  list-style: none;
  margin: 0;
  padding: 8px;
  max-height: 320px;
  overflow-y: auto;
}
.palette-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: 8px;
  cursor: pointer;
  min-height: 44px;
}
.palette-item.active { background: #FDE047; }
.cmd-icon { font-size: 16px; }
.cmd-label { flex: 1; font-size: 13px; font-weight: 600; color: #713F12; }
.cmd-group {
  font-size: 10px;
  font-weight: 800;
  color: #92400e;
  background: #fef3d0;
  border-radius: 999px;
  padding: 4px 8px;
  white-space: nowrap;
}
.palette-empty { padding: 16px; font-size: 13px; color: #92400e; text-align: center; }
.palette-hint {
  padding: 8px 16px;
  border-top: 1px solid #f3d89a;
  font-size: 11px;
  color: #92400e;
  background: #fff8ee;
  text-align: center;
}
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
@keyframes dialog-in {
  from { opacity: 0; transform: translateY(-12px) scale(0.98); }
  to { opacity: 1; transform: translateY(0) scale(1); }
}
@media (prefers-reduced-motion: reduce) {
  .palette-dialog { animation: none; }
}
</style>

// tasks-quarantine/frontend-landing-readymag/solution/app/src/components/CommandPalette.jsx
import { useEffect, useMemo, useRef, useState } from 'react'
import * as Dialog from '@radix-ui/react-dialog'
import styled from '@emotion/styled'
import { keyframes } from '@emotion/react'
import { colors, fonts } from '../theme/tokens'
import { webmcpBus } from '../webmcp/registerWebmcp'

const fadeIn = keyframes`
  from { opacity: 0; }
  to { opacity: 1; }
`
const popIn = keyframes`
  from { opacity: 0; transform: translateY(-8px) scale(0.98); }
  to { opacity: 1; transform: translateY(0) scale(1); }
`

const Overlay = styled(Dialog.Overlay)`
  position: fixed;
  inset: 0;
  background: rgba(20, 20, 20, 0.42);
  backdrop-filter: blur(2px);
  z-index: 2147482000;
  animation: ${fadeIn} 0.18s ease-out;
  @media (prefers-reduced-motion: reduce) {
    animation: none;
  }
`

const Content = styled(Dialog.Content)`
  position: fixed;
  top: 14vh;
  left: 50%;
  transform: translateX(-50%);
  width: min(560px, calc(100vw - 32px));
  background: ${colors.white};
  border-radius: 16px;
  box-shadow: 0 24px 80px rgba(0, 0, 0, 0.28);
  border: 1px solid rgba(0, 0, 0, 0.08);
  overflow: hidden;
  z-index: 2147482001;
  font-family: ${fonts.inter};
  animation: ${popIn} 0.2s cubic-bezier(0.16, 1, 0.3, 1);
  &:focus {
    outline: none;
  }
  @media (prefers-reduced-motion: reduce) {
    animation: none;
  }
`

const SearchWrap = styled.div`
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 14px 16px;
  border-bottom: 1px solid rgba(0, 0, 0, 0.08);
`

const SearchInput = styled.input`
  flex: 1;
  border: 0;
  outline: none;
  font-family: ${fonts.inter};
  font-size: 16px;
  color: ${colors.dark};
  background: transparent;
  &::placeholder {
    color: ${colors.gray8C};
  }
`

const Kbd = styled.kbd`
  font-family: ${fonts.inter};
  font-size: 11px;
  color: ${colors.gray8C};
  border: 1px solid rgba(0, 0, 0, 0.16);
  border-bottom-width: 2px;
  border-radius: 6px;
  padding: 2px 6px;
  background: ${colors.grayF4};
`

const List = styled.ul`
  list-style: none;
  margin: 0;
  padding: 8px;
  max-height: 46vh;
  overflow-y: auto;
`

const Item = styled.li`
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 10px 12px;
  border-radius: 10px;
  cursor: pointer;
  color: ${colors.dark};
  font-size: 14px;
  background: ${(p) => (p.$active ? colors.grayF4 : 'transparent')};
  outline: none;
  &[data-highlighted] {
    background: ${colors.grayF4};
  }
  .hint {
    color: ${colors.gray8C};
    font-size: 12px;
  }
`

const Empty = styled.li`
  padding: 18px 12px;
  color: ${colors.gray8C};
  font-size: 13px;
  text-align: center;
`

const SECTIONS = [
  { id: 'hero', label: 'hero' },
  { id: 'workflow', label: 'workflow' },
  { id: 'teams', label: 'teams' },
  { id: 'support', label: 'support' },
  { id: 'closing', label: 'closing' },
  { id: 'trial-brief', label: 'trial brief' },
]

/**
 * Command palette (Ctrl/Cmd+K). Built on Radix Dialog so the surface carries
 * role=dialog + aria-modal, traps focus while open, closes on Escape / backdrop
 * click, and the search field exposes an accessible name. Opening it dismisses
 * the Solutions menu first (PRD contract). Enter runs the highlighted command;
 * "Jump to trial brief" scrolls the panel into view and closes the palette.
 */
export default function CommandPalette() {
  const [open, setOpen] = useState(false)
  const [query, setQuery] = useState('')
  const inputRef = useRef(null)
  const prevFocusRef = useRef(null)

  // Open on Ctrl/Cmd+K (and close Solutions first); toggle if already open.
  // Capture the currently-focused control synchronously here — Radix blurs it
  // during its open sequence, so reading document.activeElement later would
  // already yield <body> and we couldn't restore focus on close.
  useEffect(() => {
    const onKey = (e) => {
      const mod = e.metaKey || e.ctrlKey
      if (mod && (e.key === 'k' || e.key === 'K')) {
        e.preventDefault()
        setOpen((v) => {
          if (!v) {
            prevFocusRef.current = document.activeElement
            if (typeof webmcpBus.closeSolutions === 'function') webmcpBus.closeSolutions()
            setQuery('')
          }
          return !v
        })
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [])

  const commands = useMemo(() => {
    const q = query.trim().toLowerCase()
    const base = [
      ...SECTIONS.map((s) => ({
        id: `jump-${s.id}`,
        label: `Jump to ${s.label}`,
        run: () => {
          const el = document.getElementById(`rm-section-${s.id}`)
          if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
        },
      })),
      {
        id: 'advance',
        label: 'Advance slideshow',
        run: () => {
          if (typeof webmcpBus.advanceSlideshow === 'function') webmcpBus.advanceSlideshow()
        },
      },
    ]
    if (!q) return base
    return base.filter((c) => c.label.toLowerCase().includes(q))
  }, [query])

  const runCommand = (cmd) => {
    if (!cmd) return
    cmd.run()
    setOpen(false)
  }

  const handleOpenChange = (next) => {
    // Escape / backdrop close pass through here; opening is handled in the
    // keydown listener so the previously-focused control is captured in time.
    setOpen(next)
  }

  // Radix returns focus to the (null) trigger on Cmd+K open; restore the real
  // previously-focused control on close instead. The restore is deferred one
  // tick so it lands after Radix's own focus-guard cycle (which would otherwise
  // bounce focus back to <body>).
  const restoreFocus = (e) => {
    e.preventDefault()
    const el = prevFocusRef.current
    prevFocusRef.current = null
    if (el && typeof el.focus === 'function' && document.contains(el)) {
      setTimeout(() => el.focus(), 0)
    }
  }

  return (
    <Dialog.Root open={open} onOpenChange={handleOpenChange}>
      <Dialog.Portal>
        <Overlay />
        <Content
          role="dialog"
          aria-modal="true"
          aria-label="Command palette"
          onOpenAutoFocus={(e) => {
            e.preventDefault()
            inputRef.current?.focus()
          }}
          onCloseAutoFocus={restoreFocus}
        >
          <Dialog.Title
            style={{
              position: 'absolute',
              width: 1,
              height: 1,
              overflow: 'hidden',
              clipPath: 'inset(50%)',
            }}
          >
            Command palette
          </Dialog.Title>
          <SearchWrap>
            <SearchInput
              ref={inputRef}
              type="text"
              aria-label="Search commands"
              placeholder="Search commands…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault()
                  runCommand(commands[0])
                }
              }}
            />
            <Kbd>Esc</Kbd>
          </SearchWrap>
          <List role="listbox" aria-label="Commands">
            {commands.length === 0 ? (
              <Empty>No matching commands</Empty>
            ) : (
              commands.map((cmd, i) => (
                <Item
                  key={cmd.id}
                  role="option"
                  aria-selected={i === 0}
                  data-highlighted={i === 0 ? '' : undefined}
                  $active={i === 0}
                  onMouseDown={(e) => {
                    // mousedown so the input keeps focus until we close
                    e.preventDefault()
                    runCommand(cmd)
                  }}
                >
                  <span>{cmd.label}</span>
                  <span className="hint">{i === 0 ? '↵' : ''}</span>
                </Item>
              ))
            )}
          </List>
        </Content>
      </Dialog.Portal>
    </Dialog.Root>
  )
}
