// tasks/frontend-productivity-loopdaily/solution/app/src/components/Toast.tsx
import { useAtom } from "jotai";
import { toastsAtom, removeToastAtom } from "../store";

export default function Toast() {
  const [toasts] = useAtom(toastsAtom);
  const [, remove] = useAtom(removeToastAtom);

  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 flex flex-col gap-2 items-center pointer-events-none">
      {toasts.map((t) => {
        const bgColor =
          t.type === "success"
            ? "bg-[#0F9D74]"
            : t.type === "error"
            ? "bg-[#EF4444]"
            : "bg-[#475569]";

        const isAlert = t.type === "error" || t.type === "info";

        return (
          <div
            key={t.id}
            className={`${bgColor} text-white px-5 py-3 rounded-lg shadow-lg text-sm font-medium cursor-pointer toast-enter max-w-xs text-center pointer-events-auto`}
            onClick={() => remove(t.id)}
            role={isAlert ? "alert" : "status"}
            aria-live={isAlert ? "assertive" : "polite"}
          >
            {t.text}
          </div>
        );
      })}
    </div>
  );
}

// tasks/frontend-dare-night/solution/app/src/components/Toast.svelte
<script lang="ts">
  interface Props {
    toast: { id: number; message: string; type: 'success' | 'error' | 'info' };
  }

  let { toast }: Props = $props();

  function getToastClass(type: string): string {
    switch (type) {
      case 'success': return 'bg-green-600 text-white';
      case 'error': return 'bg-red-600 text-white';
      case 'info': return 'bg-gray-800 text-white';
      default: return 'bg-gray-800 text-white';
    }
  }
</script>

<div
  class="toast-enter px-6 py-3 rounded-full shadow-xl text-sm font-medium pointer-events-auto {getToastClass(toast.type)}"
  role={toast.type === 'error' ? 'alert' : 'status'}
  aria-live={toast.type === 'error' ? 'assertive' : 'polite'}
>
  {toast.message}
</div>
