// tasks/frontend-creative-tools-quilt-block-layout-studio-constraint-canvas-rn-linear-views/solution/app/src/components/ExportImport.jsx
import React, { useState } from 'react';
import { useStore } from '../store/useStore';

export function ExportImport({ onClose }) {
  const { exportSession, importSession, clearState } = useStore();
  const [importText, setImportText] = useState('');
  const [error, setError] = useState(null);
  const [tab, setTab] = useState('export'); // 'export' or 'import'

  const handleCopy = async () => {
    try {
      const data = exportSession();
      await navigator.clipboard.writeText(JSON.stringify(data, null, 2));
      alert('Copied to clipboard!');
    } catch (err) {
      console.error('Copy failed', err);
    }
  };

  const handleDownload = () => {
    const data = exportSession();
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'quilt-layout-v1-constraint-canvas.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleImport = () => {
    try {
      setError(null);
      const data = JSON.parse(importText);
      const success = importSession(data);
      if (success) {
        onClose();
      } else {
        setError('Invalid schema or values.');
      }
    } catch (e) {
      setError('Invalid JSON format.');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[90vh] flex flex-col">
        <div className="flex border-b">
          <button
            className={`flex-1 py-3 font-bold ${tab === 'export' ? 'bg-primary text-white' : 'hover:bg-gray-100'}`}
            onClick={() => setTab('export')}
          >
            Export Session
          </button>
          <button
            className={`flex-1 py-3 font-bold ${tab === 'import' ? 'bg-primary text-white' : 'hover:bg-gray-100'}`}
            onClick={() => setTab('import')}
          >
            Import Session
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          {tab === 'export' ? (
            <div className="flex flex-col h-full gap-4">
              <pre className="bg-gray-900 text-green-400 p-4 rounded overflow-auto flex-1 text-xs">
                {JSON.stringify(exportSession(), null, 2)}
              </pre>
              <div className="flex gap-2">
                <button onClick={handleCopy} className="flex-1 bg-gray-200 py-2 rounded hover:bg-gray-300 font-bold transition">Copy to Clipboard</button>
                <button onClick={handleDownload} className="flex-1 bg-primary text-white py-2 rounded hover:bg-primary-dark font-bold transition">Download JSON</button>
              </div>
            </div>
          ) : (
            <div className="flex flex-col h-full gap-4">
              <p className="text-sm text-gray-600">Paste your session JSON below.</p>
              <textarea
                className="w-full flex-1 border rounded p-4 font-mono text-sm"
                value={importText}
                onChange={(e) => setImportText(e.target.value)}
                placeholder="Paste JSON here..."
              />
              {error && <div className="text-red-500 text-sm font-bold">{error}</div>}
              <div className="flex gap-2">
                <button onClick={clearState} className="flex-1 bg-red-500 text-white py-2 rounded hover:bg-red-600 font-bold transition">Clear State</button>
                <button onClick={handleImport} className="flex-1 bg-primary text-white py-2 rounded hover:bg-primary-dark font-bold transition">Import</button>
              </div>
            </div>
          )}
        </div>

        <div className="p-4 border-t flex justify-end bg-gray-50">
          <button onClick={onClose} className="px-4 py-2 border rounded hover:bg-gray-100 transition font-medium">Close</button>
        </div>
      </div>
    </div>
  );
}

// tasks/frontend-creative-tools-palette-library/solution/app/src/components/ExportImport.vue
<template>
  <div class="max-w-5xl mx-auto px-4 py-8 border-t border-gray-200">
    <div class="flex justify-between items-center mb-6">
      <h2 class="font-sans text-xl font-medium">Export / Import Package</h2>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
      <div>
        <h3 class="font-sans font-medium mb-2 text-sm">Export Library</h3>
        <select v-model="exportFormat" class="border border-gray-300 rounded px-3 py-1 font-sans text-sm focus:outline-none focus:ring-2 focus:ring-black mb-3 w-full">
          <option value="css">CSS Variables</option>
          <option value="utility-theme">Utility Theme (JS)</option>
          <option value="scss">SCSS Variables</option>
          <option value="library-json">Palette Package (JSON)</option>
        </select>
        <button @click="doExport" class="w-full bg-black text-white px-4 py-2 rounded font-sans text-sm hover:bg-gray-800 transition-colors">
          Download Artifact
        </button>
      </div>

      <div>
        <h3 class="font-sans font-medium mb-2 text-sm">Import Package (JSON)</h3>
        <form @submit.prevent="onImport" class="flex flex-col gap-3">
          <textarea
            v-model="importData"
            rows="3"
            class="border rounded px-3 py-2 font-mono text-xs focus:outline-none focus:ring-2 focus:ring-black"
            :class="{'border-red-500': importError, 'border-gray-300': !importError}"
            placeholder='Paste JSON here...'
          ></textarea>
          <p v-if="importError" class="text-red-500 text-xs font-sans" role="alert">{{ importError }}</p>
          <button type="submit" class="w-full border border-black text-black px-4 py-2 rounded font-sans text-sm hover:bg-gray-50 transition-colors">
            Import
          </button>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { usePaletteStore } from '../stores/palette';
import { z } from 'zod';

const store = usePaletteStore();
const exportFormat = ref('library-json');
const importData = ref('');
const importError = ref('');

const paletteSchema = z.object({
  id: z.string(),
  name: z.string(),
  period: z.string(),
  swatches: z.array(z.string().regex(/^#[0-9a-fA-F]{6}$/)),
  favorite: z.boolean().optional()
});
const importSchema = z.array(paletteSchema);

function doExport() {
  const data = store.palettes;
  let content = '';
  let mimeType = 'text/plain';
  let filename = 'export.txt';

  if (exportFormat.value === 'library-json') {
    content = JSON.stringify(data, null, 2);
    mimeType = 'application/json';
    filename = 'palettes.json';
  } else if (exportFormat.value === 'css') {
    content = ':root {\n';
    data.forEach((p, i) => {
      p.swatches.forEach((s, j) => {
        content += `  --color-${p.name.replace(/\s+/g, '-').toLowerCase()}-${j}: ${s};\n`;
      });
    });
    content += '}';
    filename = 'palettes.css';
    mimeType = 'text/css';
  } else if (exportFormat.value === 'scss') {
    data.forEach((p, i) => {
      p.swatches.forEach((s, j) => {
        content += `$color-${p.name.replace(/\s+/g, '-').toLowerCase()}-${j}: ${s};\n`;
      });
    });
    filename = 'palettes.scss';
  } else if (exportFormat.value === 'utility-theme') {
    content = 'module.exports = { theme: { extend: { colors: { \n';
    data.forEach((p, i) => {
      content += `  '${p.name.replace(/\s+/g, '-').toLowerCase()}': {\n`;
      p.swatches.forEach((s, j) => {
        content += `    '${j * 100 || 50}': '${s}',\n`;
      });
      content += `  },\n`;
    });
    content += '} } } };';
    filename = 'theme.js';
    mimeType = 'text/javascript';
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function onImport() {
  importError.value = '';
  try {
    const parsed = JSON.parse(importData.value);
    const result = importSchema.safeParse(parsed);
    if (!result.success) {
      importError.value = 'Invalid package format. Must be an array of palettes matching the schema.';
      return;
    }
    store.undoStack.push(JSON.parse(JSON.stringify(store.palettes)));
    store.palettes = result.data;
    importData.value = '';
  } catch (e) {
    importError.value = 'Invalid JSON.';
  }
}
</script>
