// tasks/frontend-creative-tools-color-palette-archive/solution/app/src/components/library/nomenclature-view.tsx
import { oaColorName } from "../../utils/color-names";
import { component$, useContext } from '@builder.io/qwik';
import { GlobalStoreContext } from '../../store';
import { hueSort } from '../../utils/colors';

export const NomenclatureView = component$(() => {
  const store = useContext(GlobalStoreContext);

  let visiblePalettes = store.palettes.filter(p => !p.archived);

  if (store.periodFilter) {
    visiblePalettes = visiblePalettes.filter(p => p.period === store.periodFilter);
  }

  // Build and deduplicate rows
  const rows: any[] = [];
  const seen = new Set<string>();

  visiblePalettes.forEach((card) => {
    (card.swatches || []).forEach((hex) => {
      const key = String(hex).toLowerCase();
      if (seen.has(key)) return;
      seen.add(key);
      const colorName = oaColorName(key);
      rows.push({
        hex: key,
        period: card.period,
        title: card.name,
        artist: card.artist,
        name: colorName.name,
        note: colorName.note,
      });
    });
  });

  // Sort deterministic
  rows.sort((a, b) => hueSort(a.hex) - hueSort(b.hex));

  return (
    <div id="nomenclature-view" class="palette-library__view palette-library__view--nomenclature" role="tabpanel">
       <div class="nomenclature-row nomenclature-row--header grid grid-cols-[3rem_6rem_minmax(120px,1fr)_minmax(120px,1fr)_minmax(200px,1fr)] gap-4 pb-2 border-b-2 border-black font-bold text-xs uppercase tracking-widest mb-4">
          <span></span>
          <span>Hex</span>
          <span>Name</span>
          <span>Notes</span>
          <span>Painting</span>
       </div>
       <div class="flex flex-col gap-2">
       {rows.map(row => (
         <div key={row.hex} class="nomenclature-row grid grid-cols-[3rem_6rem_minmax(120px,1fr)_minmax(120px,1fr)_minmax(200px,1fr)] gap-4 items-center py-2 border-b border-gray-200 hover:bg-white transition-colors" data-hex={row.hex} data-period={row.period}>
            <button
              type="button"
              class="nomenclature-swatch w-10 h-10 rounded-full border border-gray-300 relative"
              style={{ backgroundColor: row.hex }}
              data-hex={row.hex}
              title={`Click to copy ${row.hex}`}
              onClick$={() => {
                  navigator.clipboard.writeText(row.hex);
                  store.copyFeedback = row.hex;
                  setTimeout(() => store.copyFeedback = null, 1000);
              }}
            >
              {store.copyFeedback === row.hex && (
                  <span class="absolute inset-0 flex items-center justify-center bg-white/20 text-white text-xs font-bold drop-shadow-md rounded-full">
                    ✓
                  </span>
                )}
            </button>
            <span class="nomenclature-hex font-mono text-sm">{row.hex}</span>
            <span class="nomenclature-name text-sm capitalize" data-color-name>{row.name}</span>
            <span class="nomenclature-note text-sm text-gray-500 italic truncate" data-color-note title={row.note}>{row.note}</span>
            <div class="nomenclature-source flex flex-col">
              <button type="button" class="nomenclature-source__title text-left font-serif font-bold text-sm hover:underline">{row.title}</button>
              <span class="nomenclature-source__artist text-xs text-gray-600">{row.artist}</span>
            </div>
         </div>
       ))}
       </div>
    </div>
  );
});

// tasks/frontend-creative-tools-palette-library/solution/app/src/components/NomenclatureView.vue
<template>
  <div class="max-w-5xl mx-auto px-4 py-8">
    <div v-if="sortedAndDedupedSwatches.length === 0" class="py-12 text-center font-serif text-gray-500">
      No colors found for the selected filter. Try adjusting your search or restoring palettes.
    </div>

    <div v-else class="flex flex-col gap-2">
      <div class="grid grid-cols-12 gap-4 pb-2 border-b border-gray-200 font-mono text-xs text-gray-500 uppercase tracking-widest">
        <div class="col-span-1">Swatch</div>
        <div class="col-span-2">Hex</div>
        <div class="col-span-3">Name</div>
        <div class="col-span-3">Notes</div>
        <div class="col-span-3">Source</div>
      </div>

      <div
        v-for="(item, index) in sortedAndDedupedSwatches"
        :key="item.hex + index"
        class="grid grid-cols-12 gap-4 items-center py-2 hover:bg-gray-50 group transition-colors"
      >
        <div class="col-span-1">
          <button
            @click="copyHex(item.hex, index)"
            class="w-8 h-8 rounded-full border border-gray-200 focus:outline-none focus:ring-2 focus:ring-black focus:ring-offset-2 relative"
            :style="{ backgroundColor: item.hex }"
            :aria-label="`Copy hex ${item.hex}`"
          >
            <span class="absolute inset-0 m-auto w-full text-center text-xs text-white opacity-0 group-focus:opacity-100 transition-opacity drop-shadow">Copy</span>
            <span
              v-if="store.copyFeedback === `nom-${index}`"
              class="absolute top-0 -right-16 h-6 leading-6 bg-black text-white text-xs px-2 py-0.5 rounded shadow z-10 whitespace-nowrap"
              aria-live="polite"
            >Copied</span>
          </button>
        </div>
        <div class="col-span-2 font-mono text-sm uppercase">
          {{ item.hex }}
        </div>
        <div class="col-span-3 font-serif italic text-base">
          {{ colorName(item.hex) }}
        </div>
        <div class="col-span-3 font-sans text-sm text-gray-600">
          Historical pigment equivalent.
        </div>
        <div class="col-span-3 font-sans text-sm font-medium">
          {{ item.paletteName }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { usePaletteStore } from '../stores/palette';
import { oaColorName } from '../../vendor/oa-color-library.js';
const store = usePaletteStore();

function hueSortValue(hex) {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h[0]+h[0]+h[1]+h[1]+h[2]+h[2];
  let r = parseInt(h.substring(0,2),16) / 255;
  let g = parseInt(h.substring(2,4),16) / 255;
  let b = parseInt(h.substring(4,6),16) / 255;
  let max = Math.max(r,g,b), min = Math.min(r,g,b);
  let l = (max + min) / 2;
  if (max === min) return 1000 + (1 - l) * 100;
  let d = max - min;
  let s = d / (1 - Math.abs(2*l - 1));
  let hue;
  if (max === r) hue = ((g - b) / d + (g < b ? 6 : 0)) / 6;
  else if (max === g) hue = ((b - r) / d + 2) / 6;
  else hue = ((r - g) / d + 4) / 6;
  if (s < 0.12 || l < 0.12) return 1000 + (1 - l) * 100;
  return hue * 360;
}

const sortedAndDedupedSwatches = computed(() => {
  const swatches = store.allSwatches;
  const sorted = [...swatches].sort((a, b) => hueSortValue(a.hex) - hueSortValue(b.hex));
  const seen = new Set();
  const deduped = [];
  for (const item of sorted) {
    const lower = item.hex.toLowerCase();
    if (!seen.has(lower)) {
      seen.add(lower);
      deduped.push(item);
    }
  }
  return deduped;
});

function copyHex(hex, index) {
  navigator.clipboard.writeText(hex).then(() => {
    store.copyFeedback = `nom-${index}`;
    setTimeout(() => {
      if (store.copyFeedback === `nom-${index}`) {
        store.copyFeedback = null;
      }
    }, 1000);
  });
}

function colorName(hex) {
  return oaColorName(hex).name;
}
</script>
