// tasks/frontend-productivity-lineforge/solution/app/src/components/ExportCenter.jsx
import { h } from 'preact';
import { useSignal } from '@preact/signals';
import { useRef, useEffect } from 'preact/hooks';
import {
  showExportCenter, importError,
  buildStudyPackText, buildCurrentPGN, importStudyPackText,
  favorites, savedLines, boardTheme, currentOpening, selectedNodeId
} from '../store';

function download(filename, text, mime) {
  try {
    const blob = new Blob([text], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  } catch { /* download unavailable */ }
}

export function ExportCenter() {
  const copied = useSignal('');
  const copyFailed = useSignal('');
  const importText = useSignal('');
  const dialogRef = useRef(null);
  const openerRef = useRef(null);

  // Recompute previews from live store state on every render (signals read below).
  // Reading the signals here subscribes this component to their changes.
  const _f = favorites.value; const _s = savedLines.value; const _t = boardTheme.value;
  const _o = currentOpening.value; const _n = selectedNodeId.value;
  const studyPackText = buildStudyPackText();
  const pgnText = buildCurrentPGN();

  useEffect(() => {
    openerRef.current = document.activeElement;
    const el = dialogRef.current;
    if (el) {
      const first = el.querySelector('button, [href], input, textarea, select');
      if (first) first.focus();
    }
    return () => {
      if (openerRef.current && typeof openerRef.current.focus === 'function') {
        openerRef.current.focus();
      }
    };
  }, []);

  const close = () => { showExportCenter.value = false; importError.value = ''; };

  const onKeyDown = (e) => {
    if (e.key === 'Escape') { e.preventDefault(); close(); return; }
    if (e.key !== 'Tab') return;
    const el = dialogRef.current;
    if (!el) return;
    const focusable = el.querySelectorAll('button, [href], input, textarea, select, [tabindex]:not([tabindex="-1"])');
    if (focusable.length === 0) return;
    const list = Array.from(focusable).filter(n => !n.disabled);
    const first = list[0];
    const last = list[list.length - 1];
    if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }
    else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }
  };

  // Falls back to a hidden-textarea execCommand copy when the async Clipboard
  // API is unavailable (insecure context, permission denied, older browser).
  const fallbackCopy = (text) => {
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.setAttribute('readonly', '');
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      ta.style.pointerEvents = 'none';
      document.body.appendChild(ta);
      ta.select();
      ta.setSelectionRange(0, text.length);
      const ok = !!(document.execCommand && document.execCommand('copy'));
      document.body.removeChild(ta);
      return ok;
    } catch {
      return false;
    }
  };

  const copy = (label, text) => {
    const finish = (ok) => {
      if (ok) {
        copyFailed.value = '';
        copied.value = label;
        setTimeout(() => { if (copied.value === label) copied.value = ''; }, 1600);
      } else {
        copied.value = '';
        copyFailed.value = label;
        setTimeout(() => { if (copyFailed.value === label) copyFailed.value = ''; }, 1600);
      }
    };
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(
        () => finish(true),
        () => finish(fallbackCopy(text))
      );
    } else {
      finish(fallbackCopy(text));
    }
  };

  const doImport = () => {
    importStudyPackText(importText.value);
  };

  return (
    <div
      class="fixed inset-0 bg-black/40 z-40 flex justify-end export-overlay"
      onClick={close}
    >
      <div
        ref={dialogRef}
        class="w-full max-w-lg bg-[var(--color-surface)] h-full overflow-y-auto shadow-xl"
        role="dialog"
        aria-modal="true"
        aria-label="Export center"
        onClick={e => e.stopPropagation()}
        onKeyDown={onKeyDown}
      >
        <div class="p-4 border-b border-neutral-400 flex items-center justify-between gap-2">
          <h2>Export center</h2>
          <button type="button" class="btn-secondary btn-compact" onClick={close}>Close</button>
        </div>

        <div class="p-4 space-y-5">
          <p aria-live="polite" class="sr-only-live text-sm"
            style={`color: var(${copyFailed.value ? '--color-danger' : '--color-success'});`}>
            {copied.value
              ? `${copied.value} copied to clipboard`
              : copyFailed.value
                ? `Could not copy ${copyFailed.value} to clipboard`
                : ''}
          </p>

          {/* Study pack JSON */}
          <section>
            <div class="flex items-center justify-between gap-2 mb-1 flex-wrap">
              <h3>Study pack JSON</h3>
              <div class="flex gap-2">
                <button type="button" class="btn-secondary btn-compact"
                  onClick={() => copy('Study pack JSON', studyPackText)}>
                  {copied.value === 'Study pack JSON' ? 'Copied!' : copyFailed.value === 'Study pack JSON' ? 'Copy failed' : 'Copy'}
                </button>
                <button type="button" class="btn-primary btn-compact"
                  onClick={() => download('lineforge-study-pack.json', studyPackText, 'application/json')}>
                  Download study pack
                </button>
              </div>
            </div>
            <pre class="export-preview" aria-label="Study pack JSON preview">{studyPackText}</pre>
          </section>

          {/* Current line PGN */}
          <section>
            <div class="flex items-center justify-between gap-2 mb-1 flex-wrap">
              <h3>Current line PGN</h3>
              <div class="flex gap-2">
                <button type="button" class="btn-secondary btn-compact"
                  onClick={() => copy('Current line PGN', pgnText)}>
                  {copied.value === 'Current line PGN' ? 'Copied!' : copyFailed.value === 'Current line PGN' ? 'Copy failed' : 'Copy'}
                </button>
                <button type="button" class="btn-primary btn-compact"
                  onClick={() => download('lineforge-current-line.pgn', pgnText, 'application/x-chess-pgn')}>
                  Download PGN
                </button>
              </div>
            </div>
            <pre class="export-preview" aria-label="Current line PGN preview">{pgnText}</pre>
          </section>

          {/* Import */}
          <section>
            <h3 class="mb-1">Import study pack</h3>
            <label class="block text-sm font-medium mb-1" for="import-json">Paste study pack JSON</label>
            <textarea
              id="import-json"
              class="text-input w-full font-mono text-sm"
              rows={5}
              placeholder='{"formatVersion":"1", ...}'
              value={importText.value}
              onInput={e => { importText.value = e.target.value; if (importError.value) importError.value = ''; }}
              aria-describedby={importError.value ? 'import-error' : undefined}
              aria-invalid={importError.value ? 'true' : undefined}
            />
            <div class="flex items-center gap-2 mt-2">
              <button type="button" class="btn-primary btn-compact"
                disabled={!importText.value.trim()}
                onClick={doImport}>
                Import study pack
              </button>
            </div>
            <p id="import-error" aria-live="polite" class="mt-1 text-sm font-medium" style="color: var(--color-danger); min-height: 1.25rem;">
              {importError.value}
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}

// tasks/frontend-creative-tools-panecraft/solution/app/src/components/ExportCenter.svelte
<script lang="ts">
  import * as store from '../lib/store';
  import Modal from './Modal.svelte';

  const center = $derived(store.getExportCenter());

  // Live previews compiled straight from the store — they always include the
  // latest session mutations under the field-contract keys.
  const workspaceJson = $derived(JSON.stringify(store.compileWorkspaceExport(), null, 2));
  const markdownReport = $derived(store.compileMarkdownReport());

  let copied = $state(false);
  let copyTimer: ReturnType<typeof setTimeout> | null = null;
  let importText = $state('');
  let importError = $state('');
  let importSuccess = $state('');
  let fileInput = $state<HTMLInputElement | undefined>();

  function activePreview(): string {
    return center.tab === 'workspace-json' ? workspaceJson : markdownReport;
  }

  function close() {
    store.closeExportCenter();
    copied = false;
    importError = '';
    importSuccess = '';
  }

  function downloadText(filename: string, content: string, mime: string) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }

  function downloadActive() {
    if (center.tab === 'workspace-json') {
      downloadText('panecraft-workspace.json', workspaceJson, 'application/json');
      store.announce('Workspace JSON download started.');
    } else {
      downloadText('panecraft-report.md', markdownReport, 'text/markdown');
      store.announce('Markdown report download started.');
    }
  }

  async function copyActive() {
    const text = activePreview();
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    copied = true;
    store.announce(
      center.tab === 'workspace-json'
        ? 'Workspace JSON copied to clipboard.'
        : 'Markdown report copied to clipboard.',
    );
    if (copyTimer) clearTimeout(copyTimer);
    copyTimer = setTimeout(() => {
      copied = false;
    }, 2000);
  }

  function runImport(raw: unknown) {
    importSuccess = '';
    importError = '';
    const result = store.applyWorkspaceImport(raw);
    if (result.ok) {
      importSuccess = `Imported ${result.pageCount} page(s) and ${result.paneCount} pane(s). The workspace now matches the document.`;
      importText = '';
      store.announce(importSuccess);
    } else {
      importError = `${result.field}: ${result.message}`;
      store.announce(`Import rejected — ${result.field} is invalid.`);
    }
  }

  function importFromPaste() {
    const text = importText.trim();
    if (!text) {
      importError = 'document: paste Workspace JSON before importing.';
      return;
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      importError = 'document: the pasted text is not valid JSON.';
      return;
    }
    runImport(parsed);
  }

  async function handleImportFile(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    try {
      const text = await file.text();
      runImport(JSON.parse(text));
    } catch {
      importError = 'document: the selected file is not valid JSON.';
    }
    input.value = '';
  }
</script>

<Modal
  open={center.open}
  heading="Export Center"
  labelledBy="export-center-heading"
  widthClass="max-w-3xl"
  onClose={close}
>
  <div class="px-6 py-3 border-b border-[var(--color-border)]">
    <div class="flex gap-1" role="tablist" aria-label="Workspace formats">
      <button
        type="button"
        role="tab"
        aria-selected={center.tab === 'workspace-json'}
        class="tap-target px-3 py-1.5 text-sm rounded-t-[var(--radius-base)] border-b-2 transition-colors {center.tab === 'workspace-json'
          ? 'border-[var(--color-primary)] font-semibold text-[var(--color-text-primary)]'
          : 'border-transparent text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]'}"
        onclick={() => (center.tab = 'workspace-json')}
      >Workspace JSON</button>
      <button
        type="button"
        role="tab"
        aria-selected={center.tab === 'markdown-report'}
        class="tap-target px-3 py-1.5 text-sm rounded-t-[var(--radius-base)] border-b-2 transition-colors {center.tab === 'markdown-report'
          ? 'border-[var(--color-primary)] font-semibold text-[var(--color-text-primary)]'
          : 'border-transparent text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)]'}"
        onclick={() => (center.tab = 'markdown-report')}
      >Markdown Report</button>
    </div>
  </div>

  <div class="p-6 space-y-4">
    <div>
      <label for="export-preview" class="block text-xs font-medium text-[var(--color-text-primary)] mb-1">
        Live preview — {center.tab === 'workspace-json' ? 'Workspace JSON (WorkspaceDocument)' : 'Markdown report'}
      </label>
      <textarea
        id="export-preview"
        readonly
        class="w-full h-56 p-3 font-mono text-xs leading-relaxed border border-[var(--color-border)] rounded-[var(--radius-base)] bg-[var(--color-surface)] text-[var(--color-text-primary)] resize-y"
        value={activePreview()}
      ></textarea>
      <div class="flex flex-wrap items-center gap-2 mt-2">
        <button
          type="button"
          class="copy-control tap-target px-3 py-2 text-sm rounded-[var(--radius-base)] {copied ? 'copy-flash' : 'bg-[var(--color-primary)] text-white hover:opacity-90'}"
          onclick={copyActive}
        >
          {copied ? 'Copied!' : 'Copy'}
        </button>
        <button
          type="button"
          class="tap-target px-3 py-2 text-sm border border-[var(--color-border)] rounded-[var(--radius-base)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface)] transition-colors"
          onclick={downloadActive}
        >
          Download
        </button>
        <span class="text-xs text-[var(--color-text-secondary)]" aria-live="polite">
          {#if copied}
            {center.tab === 'workspace-json' ? 'Workspace JSON copied to clipboard.' : 'Markdown report copied to clipboard.'}
          {:else}
            Compiled live from the current workspace.
          {/if}
        </span>
      </div>
    </div>

    <div class="border-t border-[var(--color-border)] pt-4">
      <h3 class="text-sm font-semibold text-[var(--color-text-primary)] mb-2">Import Workspace JSON</h3>
      <p class="text-xs text-[var(--color-text-secondary)] mb-2">
        Paste a WorkspaceDocument (schemaVersion panecraft-workspace-v1) or pick an exported .json file. Invalid documents are rejected whole — nothing is applied partially.
      </p>
      <div class="flex flex-col sm:flex-row gap-2">
        <label for="import-paste" class="sr-only">Paste Workspace JSON</label>
        <textarea
          id="import-paste"
          class="flex-1 h-24 p-3 font-mono text-xs border rounded-[var(--radius-base)] bg-white resize-y {importError ? 'input-invalid' : 'border-[var(--color-border)]'}"
          placeholder="Paste Workspace JSON here (schemaVersion panecraft-workspace-v1)"
          bind:value={importText}
        ></textarea>
        <div class="flex sm:flex-col gap-2">
          <button
            type="button"
            class="tap-target px-3 py-2 text-sm bg-[var(--color-primary)] text-white rounded-[var(--radius-base)] hover:opacity-90 transition-opacity"
            onclick={importFromPaste}
          >Import Pasted JSON</button>
          <button
            type="button"
            class="tap-target px-3 py-2 text-sm border border-[var(--color-border)] rounded-[var(--radius-base)] text-[var(--color-text-primary)] hover:bg-[var(--color-surface)] transition-colors"
            onclick={() => fileInput?.click()}
          >Choose File…</button>
          <input
            bind:this={fileInput}
            type="file"
            accept="application/json,.json"
            class="hidden"
            aria-label="Import workspace JSON file"
            onchange={handleImportFile}
          />
        </div>
      </div>
      <div aria-live="polite">
        {#if importError}
          <p class="field-error" role="alert">Import rejected — {importError} The workspace is unchanged.</p>
        {/if}
        {#if importSuccess}
          <p class="text-xs mt-1" style="color: var(--color-accent);">{importSuccess}</p>
        {/if}
      </div>
    </div>
  </div>
</Modal>
