// tasks/frontend-planning-carry-on-packing-optimizer-scenario-weaver-rn-spotify-playlists/solution/app/src/components/Header.tsx
import React, { useRef } from 'react';
import { Download, Upload, Undo2, Briefcase } from 'lucide-react';
import type { DerivedState } from '../types';

interface HeaderProps {
  exportData: () => any;
  importData: (data: any) => void;
  derived: DerivedState;
  undo: () => void;
  canUndo: boolean;
}

export function Header({ exportData, importData, derived, undo, canUndo }: HeaderProps) {
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExport = () => {
    const data = exportData();
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'carry-on-pack-v1-scenario-weaver.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const json = JSON.parse(event.target?.result as string);
        importData(json);
      } catch (err) {
        console.error("Failed to parse JSON", err);
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) fileInputRef.current.value = '';
  };

  return (
    <header className="bg-slate-900 border-b border-slate-700 py-4 px-6 sticky top-0 z-10 shadow-lg">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3 text-indigo-400">
          <Briefcase className="w-8 h-8" />
          <h1 className="text-2xl font-bold text-white tracking-tight">PackOpt<span className="text-indigo-400">.</span></h1>
        </div>

        <div className="flex items-center gap-6 bg-slate-800/50 px-6 py-2 rounded-full border border-slate-700">
          <div className="text-center">
            <div className="text-xs text-slate-400 font-medium uppercase tracking-wider">Total Weight</div>
            <div className="text-lg font-mono text-white">{derived.totalWeight}g</div>
          </div>
          <div className="w-px h-8 bg-slate-700"></div>
          <div className="text-center">
            <div className="text-xs text-slate-400 font-medium uppercase tracking-wider">Items</div>
            <div className="text-lg font-mono text-white">{derived.totalItems}</div>
          </div>
          <div className="w-px h-8 bg-slate-700"></div>
          <div className="text-center">
            <div className="text-xs text-slate-400 font-medium uppercase tracking-wider">Ready</div>
            <div className="text-lg font-mono text-emerald-400">{derived.readyItems}</div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={undo}
            disabled={!canUndo}
            className="p-2 text-slate-300 hover:text-white hover:bg-slate-700 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            aria-label="Undo last action"
            title="Undo (Ctrl+Z)"
          >
            <Undo2 className="w-5 h-5" />
          </button>
          <div className="w-px h-6 bg-slate-700 mx-2"></div>
          <button
            onClick={() => fileInputRef.current?.click()}
            className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-600 rounded-lg transition-colors text-sm font-medium"
          >
            <Upload className="w-4 h-4" />
            Import
          </button>
          <input
            type="file"
            ref={fileInputRef}
            onChange={handleImport}
            accept=".json"
            className="hidden"
          />
          <button
            onClick={handleExport}
            className="flex items-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors text-sm font-medium"
          >
            <Download className="w-4 h-4" />
            Export
          </button>
        </div>
      </div>
    </header>
  );
}

// tasks/frontend-creative-tools-panecraft/solution/app/src/components/Header.svelte
<script lang="ts">
  import * as store from '../lib/store';

  let showWorkspacePanel = $state(false);
  let importFeedback = $state('');
  let copyFeedback = $state('');
  let fileInput = $state<HTMLInputElement | undefined>();

  function downloadText(filename: string, content: string, mime: string) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }

  function downloadWorkspaceJson() {
    downloadText('panecraft-workspace.json', JSON.stringify(store.compileWorkspaceExport(), null, 2), 'application/json');
  }

  function downloadMarkdownReport() {
    downloadText('panecraft-report.md', store.compileMarkdownReport(), 'text/markdown');
  }

  async function copyWorkspaceJson() {
    const text = JSON.stringify(store.compileWorkspaceExport(), null, 2);
    try {
      await navigator.clipboard.writeText(text);
      copyFeedback = 'Copied workspace JSON to clipboard.';
    } catch {
      const input = document.createElement('textarea');
      input.value = text;
      document.body.appendChild(input);
      input.select();
      document.execCommand('copy');
      document.body.removeChild(input);
      copyFeedback = 'Copied workspace JSON to clipboard.';
    }
    setTimeout(() => copyFeedback = '', 2000);
  }

  function triggerImport() {
    fileInput?.click();
  }

  async function handleImportFile(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      const result = store.applyWorkspaceImport(parsed);
      importFeedback = result.ok
        ? `Imported ${result.pageCount} page(s), ${result.paneCount} pane(s).`
        : `Import failed: ${result.error}`;
    } catch {
      importFeedback = 'Import failed: file is not valid JSON.';
    }
    input.value = '';
  }
</script>

<header class="bg-[var(--color-secondary)] text-white py-4 px-4">
  <div class="max-w-7xl mx-auto flex items-center justify-between">
    <h1 class="text-[28px] font-semibold tracking-tight">PaneCraft</h1>
    <div class="flex items-center gap-3">
      <span class="text-xs text-white/60">Dashboard Builder</span>
      <button
        class="px-3 py-1.5 text-xs border border-white/30 rounded-[var(--radius-base)] text-white hover:bg-white/10 whitespace-nowrap"
        aria-expanded={showWorkspacePanel}
        onclick={() => showWorkspacePanel = !showWorkspacePanel}
      >
        Workspace
      </button>
    </div>
  </div>

  {#if showWorkspacePanel}
    <div class="max-w-7xl mx-auto mt-3 p-4 bg-white text-[var(--color-text-primary)] rounded-[var(--radius-base)] shadow-lg" role="region" aria-label="Workspace export and import">
      <div class="flex flex-wrap items-center gap-2">
        <button class="px-3 py-1.5 text-xs bg-[var(--color-primary)] text-white rounded-[var(--radius-base)] hover:opacity-90" onclick={downloadWorkspaceJson}>
          Download Workspace JSON
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={copyWorkspaceJson}>
          Copy Workspace JSON
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={downloadMarkdownReport}>
          Download Markdown Report
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={triggerImport}>
          Import Workspace JSON
        </button>
        <input
          bind:this={fileInput}
          type="file"
          accept="application/json"
          class="hidden"
          onchange={handleImportFile}
        />
      </div>
      <p class="text-xs text-[var(--color-text-secondary)] mt-2" aria-live="polite">{copyFeedback || importFeedback || 'Export the workspace as JSON or a Markdown report, or import a previously exported JSON file.'}</p>
    </div>
  {/if}
</header>
