// tasks/frontend-creative-tools-panecraft/solution/app/src/components/Header.svelte
<script lang="ts">
  import * as store from '../lib/store';

  let showWorkspacePanel = $state(false);
  let importFeedback = $state('');
  let copyFeedback = $state('');
  let fileInput = $state<HTMLInputElement | undefined>();

  function downloadText(filename: string, content: string, mime: string) {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = filename;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
    URL.revokeObjectURL(url);
  }

  function downloadWorkspaceJson() {
    downloadText('panecraft-workspace.json', JSON.stringify(store.compileWorkspaceExport(), null, 2), 'application/json');
  }

  function downloadMarkdownReport() {
    downloadText('panecraft-report.md', store.compileMarkdownReport(), 'text/markdown');
  }

  async function copyWorkspaceJson() {
    const text = JSON.stringify(store.compileWorkspaceExport(), null, 2);
    try {
      await navigator.clipboard.writeText(text);
      copyFeedback = 'Copied workspace JSON to clipboard.';
    } catch {
      const input = document.createElement('textarea');
      input.value = text;
      document.body.appendChild(input);
      input.select();
      document.execCommand('copy');
      document.body.removeChild(input);
      copyFeedback = 'Copied workspace JSON to clipboard.';
    }
    setTimeout(() => copyFeedback = '', 2000);
  }

  function triggerImport() {
    fileInput?.click();
  }

  async function handleImportFile(event: Event) {
    const input = event.currentTarget as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) return;
    try {
      const text = await file.text();
      const parsed = JSON.parse(text);
      const result = store.applyWorkspaceImport(parsed);
      importFeedback = result.ok
        ? `Imported ${result.pageCount} page(s), ${result.paneCount} pane(s).`
        : `Import failed: ${result.error}`;
    } catch {
      importFeedback = 'Import failed: file is not valid JSON.';
    }
    input.value = '';
  }
</script>

<header class="bg-[var(--color-secondary)] text-white py-4 px-4">
  <div class="max-w-7xl mx-auto flex items-center justify-between">
    <h1 class="text-[28px] font-semibold tracking-tight">PaneCraft</h1>
    <div class="flex items-center gap-3">
      <span class="text-xs text-white/60">Dashboard Builder</span>
      <button
        class="px-3 py-1.5 text-xs border border-white/30 rounded-[var(--radius-base)] text-white hover:bg-white/10 whitespace-nowrap"
        aria-expanded={showWorkspacePanel}
        onclick={() => showWorkspacePanel = !showWorkspacePanel}
      >
        Workspace
      </button>
    </div>
  </div>

  {#if showWorkspacePanel}
    <div class="max-w-7xl mx-auto mt-3 p-4 bg-white text-[var(--color-text-primary)] rounded-[var(--radius-base)] shadow-lg" role="region" aria-label="Workspace export and import">
      <div class="flex flex-wrap items-center gap-2">
        <button class="px-3 py-1.5 text-xs bg-[var(--color-primary)] text-white rounded-[var(--radius-base)] hover:opacity-90" onclick={downloadWorkspaceJson}>
          Download Workspace JSON
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={copyWorkspaceJson}>
          Copy Workspace JSON
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={downloadMarkdownReport}>
          Download Markdown Report
        </button>
        <button class="px-3 py-1.5 text-xs border border-[var(--color-border)] rounded-[var(--radius-base)] hover:bg-[var(--color-surface)]" onclick={triggerImport}>
          Import Workspace JSON
        </button>
        <input
          bind:this={fileInput}
          type="file"
          accept="application/json"
          class="hidden"
          onchange={handleImportFile}
        />
      </div>
      <p class="text-xs text-[var(--color-text-secondary)] mt-2" aria-live="polite">{copyFeedback || importFeedback || 'Export the workspace as JSON or a Markdown report, or import a previously exported JSON file.'}</p>
    </div>
  {/if}
</header>

// tasks/frontend-data-tracking-home-air-quality-trendbook-constraint-canvas-rn-linear-views/solution/app/src/components/Header.tsx
import React, { useRef } from 'react';
import { useAppContext } from '../store';
import { Download, Upload, Undo2, Copy } from 'lucide-react';

export const Header = () => {
  const { state, dispatch } = useAppContext();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleExport = () => {
    const payload = {
      schemaVersion: state.schemaVersion,
      exportedAt: new Date().toISOString(),
      records: state.records,
      derived: state.derived,
      history: state.history
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'air-quality-v1-constraint-canvas.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleImport = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target?.result as string);
        dispatch({ type: 'IMPORT_SESSION', payload: json });
      } catch (err) {
        console.error("Failed to parse import file", err);
        alert("Invalid artifact file.");
      }
    };
    reader.readAsText(file);
    if (fileInputRef.current) {
        fileInputRef.current.value = ''; // Reset input
    }
  };

  const handleCopy = () => {
    const payload = {
      schemaVersion: state.schemaVersion,
      exportedAt: new Date().toISOString(),
      records: state.records,
      derived: state.derived,
      history: state.history
    };
    navigator.clipboard.writeText(JSON.stringify(payload, null, 2)).catch(() => {});
  };

  const hasUndo = state.past.length > 0;

  return (
    <header className="bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between shadow-sm shrink-0 flex-wrap gap-2">
      <div className="flex items-center gap-4">
        <h1 className="text-xl font-bold text-gray-900 tracking-tight">Home Air Quality</h1>
        <div className="hidden md:block h-6 w-px bg-gray-300"></div>
        <span className="hidden md:block text-sm text-gray-500 font-medium">Trendbook</span>
      </div>

      <div className="flex items-center gap-3">
        <button
          onClick={() => dispatch({ type: 'UNDO' })}
          disabled={!hasUndo}
          className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-sm font-medium transition-colors ${
            hasUndo ? 'text-gray-700 hover:bg-gray-100' : 'text-gray-400 cursor-not-allowed'
          }`}
          title="Undo last action (Ctrl/Cmd+Z)"
        >
          <Undo2 className="w-4 h-4" />
          <span className="hidden sm:inline">Undo</span>
        </button>

        <div className="h-6 w-px bg-gray-300 mx-1"></div>

        <button
          onClick={handleCopy}
          className="flex items-center gap-2 px-3 py-1.5 text-gray-700 hover:bg-gray-100 rounded-md text-sm font-medium transition-colors"
          title="Copy artifact"
        >
          <Copy className="w-4 h-4" />
          <span className="hidden sm:inline">Copy</span>
        </button>

        <button
          onClick={handleExport}
          className="flex items-center gap-2 px-3 py-1.5 text-gray-700 hover:bg-gray-100 rounded-md text-sm font-medium transition-colors"
        >
          <Download className="w-4 h-4" />
          <span className="hidden sm:inline">Export</span>
        </button>

        <label className="flex items-center gap-2 px-3 py-1.5 text-gray-700 hover:bg-gray-100 rounded-md text-sm font-medium transition-colors cursor-pointer">
          <Upload className="w-4 h-4" />
          <span className="hidden sm:inline">Import</span>
          <input
            type="file"
            accept=".json"
            className="hidden"
            ref={fileInputRef}
            onChange={handleImport}
          />
        </label>
      </div>
    </header>
  );
};
