// tasks/frontend-productivity-scribblespace/solution/app/src/components/BoardSwitcher.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useAppStore } from '../store'
import {
  DialogRoot,
  DialogPortal,
  DialogOverlay,
  DialogContent,
  DialogTitle,
  DialogDescription
} from 'reka-ui'

const store = useAppStore()
const renameState = ref<{ id: string; name: string; error?: string } | null>(null)

const boardToDelete = computed(() => store.boards.find(b => b.id === store.boardDeleteId) || null)

const startRename = (board: any) => {
  renameState.value = { id: board.id, name: board.name, error: '' }
}

const confirmRename = () => {
  if (!renameState.value) return
  const { id, name } = renameState.value
  const trimmed = name.trim()

  if (trimmed.length === 0 || trimmed.length > 60) {
    renameState.value.error = 'board-name field must be 1 to 60 characters'
    store.announce('board-name field must be 1 to 60 characters')
    const b = store.boards.find(b => b.id === id)
    if (b) renameState.value.name = b.name
    return
  }

  store.renameBoard(id, trimmed)
  renameState.value = null
}

const handleKeyDown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    renameState.value = null
  } else if (e.key === 'Enter') {
    confirmRename()
  }
}
</script>

<template>
  <div class="flex items-center gap-1 overflow-x-auto min-w-0" role="tablist" aria-label="Boards">
    <div
      v-for="board in store.boards"
      :key="board.id"
      role="tab"
      :aria-selected="board.id === store.activeBoardId"
      class="flex items-center min-w-[120px] max-w-[200px] bg-white border border-gray-200 rounded-t-lg overflow-hidden shrink-0"
      :class="{'border-b-0 border-[#6D5BD0] shadow-sm z-10 bg-[#6D5BD0] text-white': board.id === store.activeBoardId}"
    >
      <div v-if="renameState?.id === board.id" class="flex flex-col w-full px-2 py-1">
        <input
          v-model="renameState.name"
          type="text"
          aria-label="Board name"
          aria-describedby="board-name-error"
          class="w-full text-sm border-b border-[#6D5BD0] outline-none"
          @keydown="handleKeyDown"
          @blur="confirmRename"
          autofocus
        />
        <span v-if="renameState.error" id="board-name-error" role="alert" class="text-xs text-red-600 mt-1">{{ renameState.error }}</span>
      </div>
      <button
        v-else
        type="button"
        class="flex-1 truncate px-3 py-1.5 text-sm text-left  outline-none focus:ring-2 focus:ring-inset focus:ring-[#6D5BD0]"
        :class="board.id === store.activeBoardId ? 'font-semibold text-white' : 'text-gray-600'"
        @click="store.setActiveBoard(board.id)"
      >
        {{ board.name }}
      </button>

      <div class="flex items-center shrink-0 pr-1 gap-0.5">
        <button
          v-if="renameState?.id !== board.id"
          type="button"
          class="p-1 hover:bg-gray-100 rounded text-gray-400 hover:text-gray-700 outline-none focus:ring-2 focus:ring-[#6D5BD0]"
          aria-label="Rename board"
          @click="startRename(board)"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
        </button>
        <button
          type="button"
          class="p-1 hover:bg-red-50 rounded text-gray-400 hover:text-red-600 outline-none focus:ring-2 focus:ring-red-500"
          aria-label="Delete board"
          @click="store.requestDeleteBoard(board.id)"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
        </button>
      </div>
    </div>

    <button
      type="button"
      class="ml-1 p-1.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 rounded-lg text-gray-500 shrink-0 outline-none focus:ring-2 focus:ring-[#6D5BD0]"
      aria-label="New Board"
      @click="store.addBoard()"
    >
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
    </button>

    <DialogRoot :open="!!boardToDelete" @update:open="(open: boolean) => { if (!open) store.requestDeleteBoard(null) }">
      <DialogPortal>
        <DialogOverlay class="fixed inset-0 bg-black/40 z-50" />
        <DialogContent class="fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white rounded-xl shadow-xl p-6 w-[min(400px,calc(100vw-24px))] z-50" :trap-focus="true">
          <DialogTitle class="text-xl font-bold text-gray-900 mb-2">Delete board {{ boardToDelete?.name }}?</DialogTitle>
          <DialogDescription class="text-gray-600 mb-6">
            This deletes the board with everything on it. Another board opens in its place.
          </DialogDescription>

          <div class="flex justify-end gap-3">
            <button
              type="button"
              class="bg-white hover:bg-gray-100 text-gray-700 border border-gray-300 font-medium rounded-lg px-4 py-2 text-sm"
              @click="store.requestDeleteBoard(null)"
            >
              Cancel
            </button>
            <button
              type="button"
              class="bg-red-600 hover:bg-red-700 text-white font-medium rounded-lg px-4 py-2 text-sm"
              @click="store.deleteBoard()"
            >
              Delete
            </button>
          </div>
        </DialogContent>
      </DialogPortal>
    </DialogRoot>
  </div>
</template>

// tasks/frontend-scribblespace/solution/app/src/components/BoardSwitcher.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useAppDispatch, useAppSelector } from '../hooks';
import {
  addBoard,
  renameBoard,
  requestDeleteBoard,
  deleteBoard,
  setActiveBoard,
} from '../slices/appSlice';
import ConfirmDialog from './ConfirmDialog';

const BoardSwitcher: React.FC = () => {
  const dispatch = useAppDispatch();
  const boards = useAppSelector(s => s.app.boards);
  const activeBoardId = useAppSelector(s => s.app.activeBoardId);
  const boardDeleteId = useAppSelector(s => s.app.boardDeleteId);

  const [renamingId, setRenamingId] = useState<string | null>(null);
  const [renameValue, setRenameValue] = useState('');
  const [renameError, setRenameError] = useState('');
  const renameInputRef = useRef<HTMLInputElement>(null);
  const renameButtonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (renamingId) {
      renameInputRef.current?.focus();
      renameInputRef.current?.select();
    }
  }, [renamingId]);

  const startRename = (boardId: string) => {
    const board = boards.find(b => b.id === boardId);
    if (board) {
      setRenamingId(boardId);
      setRenameValue(board.name);
      setRenameError('');
    }
  };

  const saveRename = () => {
    if (!renamingId) return;
    if (!renameValue.trim()) {
      setRenameError('Name is empty. Enter a board name to save it.');
      return;
    }
    if (renameValue.trim().length > 60) {
      setRenameError('Name is too long. Use 60 characters or fewer.');
      return;
    }
    dispatch(renameBoard({ boardId: renamingId, name: renameValue }));
    setRenamingId(null);
    setRenameError('');
    renameButtonRef.current?.focus();
  };

  const cancelRename = () => {
    setRenamingId(null);
    setRenameError('');
    renameButtonRef.current?.focus();
  };

  const boardToDelete = boards.find(b => b.id === boardDeleteId);

  return (
    <nav className="flex flex-wrap items-center gap-1 min-w-0" aria-label="Boards">
      {boards.map(board => {
        const isActive = board.id === activeBoardId;
        return (
          <div key={board.id} className="relative flex items-center gap-0.5">
            <button
              type="button"
              aria-pressed={isActive}
              className="font-medium whitespace-nowrap"
              style={{
                fontSize: '14px',
                minHeight: '48px',
                padding: '0 14px',
                borderRadius: '8px',
                border: '1.5px solid transparent',
                cursor: 'pointer',
                backgroundColor: isActive ? 'var(--color-primary)' : 'transparent',
                color: isActive ? '#FFFFFF' : 'var(--color-text-secondary)',
                transition: 'background-color 120ms ease, color 120ms ease',
              }}
              onMouseEnter={e => {
                if (!isActive) e.currentTarget.style.backgroundColor = '#EAE6F7';
              }}
              onMouseLeave={e => {
                if (!isActive) e.currentTarget.style.backgroundColor = 'transparent';
              }}
              onClick={() => dispatch(setActiveBoard(board.id))}
            >
              {board.name}
            </button>
            {isActive && (
              <>
                <button
                  ref={renameButtonRef}
                  type="button"
                  aria-label={`Rename board ${board.name}`}
                  title="Rename board"
                  className="flex items-center justify-center hover:bg-[#EAE6F7]"
                  style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '8px',
                    border: 'none',
                    background: 'transparent',
                    cursor: 'pointer',
                    color: 'var(--color-text-secondary)',
                  }}
                  onClick={() => startRename(board.id)}
                >
                  <svg aria-hidden="true" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path
                      d="M11.5 2.5 L13.5 4.5 L5.5 12.5 L2.5 13.5 L3.5 10.5 Z"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      strokeLinejoin="round"
                    />
                  </svg>
                </button>
                <button
                  type="button"
                  aria-label={`Delete board ${board.name}`}
                  title="Delete board"
                  className="flex items-center justify-center hover:bg-[#EAE6F7]"
                  style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '8px',
                    border: '1.5px solid var(--color-warning)',
                    background: '#FFF8E8',
                    cursor: 'pointer',
                    color: '#7A4A00',
                  }}
                  onClick={() => dispatch(requestDeleteBoard(board.id))}
                >
                  <svg aria-hidden="true" width="16" height="16" viewBox="0 0 16 16" fill="none">
                    <path d="M4 4 L12 12 M12 4 L4 12" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" />
                  </svg>
                </button>
              </>
            )}
            {renamingId === board.id && (
              <div
                className="absolute top-full left-0 mt-1 bg-white shadow-lg p-3 z-50"
                style={{ borderRadius: '8px', border: '1.5px solid var(--color-text-secondary)', minWidth: '220px' }}
                onKeyDown={e => {
                  if (e.key === 'Escape') {
                    e.stopPropagation();
                    cancelRename();
                  }
                }}
              >
                <label
                  htmlFor="board-rename-input"
                  className="block font-medium mb-1"
                  style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}
                >
                  Board name
                </label>
                <input
                  id="board-rename-input"
                  ref={renameInputRef}
                  type="text"
                  value={renameValue}
                  aria-invalid={!!renameError}
                  aria-describedby={renameError ? 'board-rename-error' : undefined}
                  className="w-full px-2 py-1.5"
                  style={{
                    fontSize: '14px',
                    borderRadius: '8px',
                    border: '1.5px solid var(--color-text-secondary)',
                    color: 'var(--color-text-primary)',
                  }}
                  onChange={e => {
                    setRenameValue(e.target.value);
                    if (renameError) setRenameError('');
                  }}
                  onKeyDown={e => {
                    if (e.key === 'Enter') saveRename();
                  }}
                />
                {renameError && (
                  <p id="board-rename-error" role="alert" className="mt-1" style={{ fontSize: '12px', color: '#A4541B', fontWeight: 600 }}>
                    {renameError}
                  </p>
                )}
                <div className="flex gap-2 mt-2 justify-end">
                  <button
                    type="button"
                    className="btn-secondary"
                    style={{ minHeight: '36px', fontSize: '13px' }}
                    onClick={cancelRename}
                  >
                    Cancel
                  </button>
                  <button
                    type="button"
                    className="btn-primary"
                    style={{ minHeight: '36px', fontSize: '13px' }}
                    onClick={saveRename}
                  >
                    Save
                  </button>
                </div>
              </div>
            )}
          </div>
        );
      })}
      <button type="button" className="btn-primary" onClick={() => dispatch(addBoard())}>
        New Board
      </button>

      {boardToDelete && (
        <ConfirmDialog
          title={`Delete board ${boardToDelete.name}?`}
          body="This deletes the board with everything on it. Another board opens in its place."
          confirmLabel="Delete"
          onConfirm={() => dispatch(deleteBoard(boardToDelete.id))}
          onCancel={() => dispatch(requestDeleteBoard(null))}
        />
      )}
    </nav>
  );
};

export default BoardSwitcher;
