// tasks/frontend-productivity-scribblespace/solution/app/src/components/OutlineView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useAppStore, NOTE_COLORS, SHAPE_COLORS } from '../store'

const store = useAppStore()

const board = computed(() => store.activeBoard)
const sortedObjects = computed(() => {
  if (!board.value) return []
  return [...board.value.objects].sort((a, b) => b.zIndex - a.zIndex)
})

const colorName = (hex: string) => {
  const map: Record<string, string> = {}
  NOTE_COLORS.forEach(c => map[c.hex.toUpperCase()] = c.name)
  SHAPE_COLORS.forEach(c => map[c.hex.toUpperCase()] = c.name)
  return map[hex.toUpperCase()] || hex
}

const snippet = (text?: string) => {
  if (!text) return '(empty)'
  const plain = text.replace(/<[^>]*>?/gm, '')
  return plain.length > 40 ? plain.substring(0, 40) + '...' : plain
}
</script>

<template>
  <div class="h-full overflow-y-auto bg-white p-6 outline-none" tabindex="-1">
    <div class="max-w-4xl mx-auto">
      <h2 class="text-2xl font-bold text-gray-900 mb-6">Outline: {{ board?.name }}</h2>

      <div v-if="sortedObjects.length === 0" class="text-gray-500 italic">
        No objects on this board.
      </div>

      <div v-else class="flex flex-col gap-2 relative">
        <transition-group
          name="list"
          enter-active-class="transition-all duration-300 ease-out"
          leave-active-class="transition-all duration-200 ease-in absolute"
          enter-from-class="opacity-0 -translate-y-4"
          leave-to-class="opacity-0 scale-95"
          move-class="transition-transform duration-300 ease-in-out"
        >
          <div
            v-for="obj in sortedObjects"
            :key="obj.id"
            class="flex items-center gap-4 p-4 border border-gray-200 rounded-xl hover:bg-gray-50 bg-white"
            :class="{ 'ring-2 ring-[#6D5BD0]': store.selectedIds.includes(obj.id), 'ring-2 ring-[#E0A030] bg-[#FFF9C4]/30': store.searchMatchIds.includes(obj.id) }"
          >
             <div class="w-12 h-12 rounded flex items-center justify-center shrink-0 border border-gray-200" :style="{ backgroundColor: obj.type === 'flashcard' ? '#FFF' : obj.color, borderRadius: obj.type === 'circle' ? '50%' : '4px' }">
                <svg v-if="obj.type === 'arrow'" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>
             </div>

             <div class="flex-1 min-w-0 flex flex-col justify-center">
                <div class="flex items-center gap-2">
                   <span class="font-semibold text-gray-900 capitalize">{{ obj.type }}</span>
                   <span class="text-xs text-gray-500 uppercase tracking-wide bg-gray-100 px-2 py-0.5 rounded">{{ colorName(obj.color) }}</span>
                   <span v-if="obj.type === 'flashcard'" class="text-xs text-purple-600 bg-purple-50 px-2 py-0.5 rounded border border-purple-200">
                      {{ obj.flipped ? 'Showing Back' : 'Showing Front' }}
                   </span>
                </div>

                <div v-if="obj.type === 'note' || obj.type === 'flashcard'" class="text-sm text-gray-600 truncate mt-1">
                   {{ snippet(obj.type === 'note' ? obj.text : (obj.flipped ? obj.back : obj.front)) }}
                </div>
             </div>

             <div class="flex items-center gap-2 shrink-0">
                <button v-if="obj.type === 'note' || obj.type === 'flashcard'" type="button" class="px-3 py-1.5 text-sm bg-white border border-gray-300 rounded hover:bg-gray-50 text-gray-700" @click="store.selectOnly(obj.id); store.setViewMode('canvas')">
                   Edit on Canvas
                </button>
                <button v-if="obj.type === 'flashcard'" type="button" class="px-3 py-1.5 text-sm bg-purple-50 border border-purple-200 rounded hover:bg-purple-100 text-purple-700" @click="store.updateObject({ id: obj.id, updates: { flipped: !obj.flipped } })">
                   Flip
                </button>
                <button type="button" class="px-3 py-1.5 text-sm bg-red-50 border border-red-200 rounded hover:bg-red-100 text-red-700" @click="store.selectOnly(obj.id); store.setShowDeleteConfirm(true)">
                   Delete
                </button>
             </div>
          </div>
        </transition-group>
      </div>
    </div>
  </div>
</template>

<style scoped>
@media (prefers-reduced-motion) {
  .list-enter-active,
  .list-leave-active,
  .list-move {
    transition: none !important;
  }
}
</style>

// tasks/frontend-scribblespace/solution/app/src/components/OutlineView.tsx
import React, { useState } from 'react';
import { useAppDispatch, useAppSelector } from '../hooks';
import {
  updateObject,
  selectOnly,
  setShowDeleteConfirm,
} from '../slices/appSlice';
import { NOTE_COLORS, SHAPE_COLORS } from '../slices/appSlice';

const colorName = (hex: string): string => {
  const named = [...NOTE_COLORS, ...SHAPE_COLORS].find(
    c => c.hex.toLowerCase() === hex.toLowerCase()
  );
  return named ? named.name : 'custom';
};

const OutlineView: React.FC = () => {
  const dispatch = useAppDispatch();
  const boards = useAppSelector(s => s.app.boards);
  const activeBoardId = useAppSelector(s => s.app.activeBoardId);
  const selectedIds = useAppSelector(s => s.app.selectedIds);
  const [editingId, setEditingId] = useState<string | null>(null);

  const board = boards.find(b => b.id === activeBoardId);
  const objects = board?.objects || [];

  if (objects.length === 0) {
    return (
      <div className="flex items-center justify-center h-full px-4" style={{ backgroundColor: 'var(--color-background)' }}>
        <div className="text-center px-8 py-6" style={{ backgroundColor: 'rgba(255,255,255,0.85)', borderRadius: '12px', maxWidth: 420 }}>
          <p className="font-semibold" style={{ fontSize: '18px', color: 'var(--color-text-primary)' }}>
            This board is empty
          </p>
          <p className="mt-1" style={{ fontSize: '14px', lineHeight: 1.5, color: 'var(--color-text-secondary)' }}>
            Add a note, flashcard or shape to see it listed here
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto px-4 py-4" style={{ backgroundColor: 'var(--color-background)' }}>
      <div className="mx-auto" style={{ maxWidth: 720 }}>
        <h2 className="font-semibold mb-3" style={{ fontSize: '18px', color: 'var(--color-text-primary)' }}>
          Outline of {board?.name}
        </h2>
        <ul className="flex flex-col gap-2 list-none p-0 m-0">
          {objects.map(obj => {
            const isSelected = selectedIds.includes(obj.id);
            const isEditing = editingId === obj.id;
            const typeLabel =
              obj.type === 'note'
                ? 'Note'
                : obj.type === 'flashcard'
                  ? 'Flashcard'
                  : `Shape — ${obj.type}`;
            return (
              <li
                key={obj.id}
                className="bg-white p-3 shadow-sm"
                style={{
                  borderRadius: '8px',
                  border: isSelected
                    ? '2px solid var(--color-primary)'
                    : '1px solid var(--color-border)',
                }}
              >
                <div className="flex flex-wrap items-center gap-2">
                  <span
                    className="font-semibold whitespace-nowrap"
                    style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}
                  >
                    {typeLabel}
                  </span>
                  {obj.type !== 'flashcard' && (
                    <span className="flex items-center gap-1" style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>
                      <span
                        aria-hidden="true"
                        style={{
                          display: 'inline-block',
                          width: 12,
                          height: 12,
                          borderRadius: '50%',
                          backgroundColor: obj.color,
                          border: '1px solid var(--color-text-secondary)',
                        }}
                      />
                      {colorName(obj.color)}
                    </span>
                  )}
                  {obj.type === 'flashcard' && (
                    <span style={{ fontSize: '12px', color: 'var(--color-text-secondary)' }}>
                      Showing the {obj.flipped ? 'back' : 'front'}
                    </span>
                  )}
                  <span className="ml-auto flex gap-2">
                    {obj.type === 'flashcard' && (
                      <button
                        type="button"
                        className="btn-secondary"
                        style={{ minHeight: '36px', fontSize: '13px' }}
                        onClick={() =>
                          dispatch(updateObject({ id: obj.id, updates: { flipped: !obj.flipped } }))
                        }
                      >
                        Flip
                      </button>
                    )}
                    {(obj.type === 'note' || obj.type === 'flashcard') && (
                      <button
                        type="button"
                        className="btn-secondary"
                        style={{ minHeight: '36px', fontSize: '13px' }}
                        onClick={() => setEditingId(isEditing ? null : obj.id)}
                      >
                        {isEditing ? 'Done' : 'Edit'}
                      </button>
                    )}
                    <button
                      type="button"
                      className="btn-warning"
                      style={{ minHeight: '36px', fontSize: '13px' }}
                      onClick={() => {
                        dispatch(selectOnly(obj.id));
                        dispatch(setShowDeleteConfirm(true));
                      }}
                    >
                      Delete
                    </button>
                  </span>
                </div>

                {!isEditing && obj.type === 'note' && (
                  <p className="mt-2 whitespace-pre-wrap break-words" style={{ fontSize: '15px', lineHeight: 1.5, color: 'var(--color-text-primary)' }}>
                    {obj.text || 'No text yet'}
                  </p>
                )}
                {!isEditing && obj.type === 'flashcard' && (
                  <div className="mt-2" style={{ fontSize: '15px', lineHeight: 1.5, color: 'var(--color-text-primary)' }}>
                    <p className="m-0">Front: {obj.front || 'no text yet'}</p>
                    <p className="m-0">Back: {obj.back || 'no text yet'}</p>
                  </div>
                )}

                {isEditing && obj.type === 'note' && (
                  <div className="mt-2">
                    <label
                      htmlFor={`outline-note-${obj.id}`}
                      className="block font-medium mb-1"
                      style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}
                    >
                      Note text
                    </label>
                    <textarea
                      id={`outline-note-${obj.id}`}
                      className="w-full p-2"
                      style={{
                        fontSize: '15px',
                        lineHeight: 1.5,
                        fontFamily: 'inherit',
                        borderRadius: '8px',
                        border: '1.5px solid var(--color-text-secondary)',
                        minHeight: 70,
                      }}
                      value={obj.text || ''}
                      onChange={e =>
                        dispatch(updateObject({ id: obj.id, updates: { text: e.target.value } }))
                      }
                      onKeyDown={e => {
                        if (e.key === 'Escape') setEditingId(null);
                      }}
                    />
                  </div>
                )}
                {isEditing && obj.type === 'flashcard' && (
                  <div className="mt-2 flex flex-col gap-2">
                    <div>
                      <label
                        htmlFor={`outline-front-${obj.id}`}
                        className="block font-medium mb-1"
                        style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}
                      >
                        Front
                      </label>
                      <input
                        id={`outline-front-${obj.id}`}
                        type="text"
                        className="w-full p-2"
                        style={{
                          fontSize: '15px',
                          borderRadius: '8px',
                          border: '1.5px solid var(--color-text-secondary)',
                        }}
                        value={obj.front || ''}
                        onChange={e =>
                          dispatch(updateObject({ id: obj.id, updates: { front: e.target.value } }))
                        }
                        onKeyDown={e => {
                          if (e.key === 'Escape') setEditingId(null);
                          if (e.key === 'Enter') setEditingId(null);
                        }}
                      />
                    </div>
                    <div>
                      <label
                        htmlFor={`outline-back-${obj.id}`}
                        className="block font-medium mb-1"
                        style={{ fontSize: '13px', color: 'var(--color-text-primary)' }}
                      >
                        Back
                      </label>
                      <input
                        id={`outline-back-${obj.id}`}
                        type="text"
                        className="w-full p-2"
                        style={{
                          fontSize: '15px',
                          borderRadius: '8px',
                          border: '1.5px solid var(--color-text-secondary)',
                        }}
                        value={obj.back || ''}
                        onChange={e =>
                          dispatch(updateObject({ id: obj.id, updates: { back: e.target.value } }))
                        }
                        onKeyDown={e => {
                          if (e.key === 'Escape') setEditingId(null);
                          if (e.key === 'Enter') setEditingId(null);
                        }}
                      />
                    </div>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
};

export default OutlineView;
