// tasks/frontend-creative-tools-euroscope/solution/app/src/components/CommandPalette.tsx
import { For, Show, createEffect, createSignal, onCleanup } from "solid-js";
import { STEPS, goToStep, selectTheme } from "../store";
import { THEME_ORDER, type ThemeName } from "../data/themes";
import { Search } from "./Icon";

type Result = {
  kind: "Stage" | "Theme";
  label: string;
  hint: string;
  run: () => void;
};

const ALL_RESULTS: Result[] = [
  ...STEPS.map((label, i) => ({
    kind: "Stage" as const,
    label,
    hint: `Stage ${i + 1}`,
    run: () => goToStep(i),
  })),
  ...THEME_ORDER.map((name) => ({
    kind: "Theme" as const,
    label: `Theme ${name}`,
    hint: "Apply palette",
    run: () => selectTheme(name as ThemeName),
  })),
];

// Modal command palette (Ctrl+K / Cmd+K): dialog semantics with aria-modal,
// focus trapped while open, Escape closes, focus returns to the opener.

export default function CommandPalette(props: {
  open: boolean;
  onClose: () => void;
}) {
  const [query, setQuery] = createSignal("");
  const [highlight, setHighlight] = createSignal(0);
  const [rendered, setRendered] = createSignal(false);
  const [closing, setClosing] = createSignal(false);
  let inputRef: HTMLInputElement | undefined;
  let dialogEl: HTMLDivElement | undefined;

  const results = () => {
    const q = query().trim().toLowerCase();
    if (!q) return ALL_RESULTS;
    return ALL_RESULTS.filter((r) => r.label.toLowerCase().includes(q));
  };

  createEffect(() => {
    if (props.open) {
      setQuery("");
      setHighlight(0);
      setClosing(false);
      setRendered(true);
      queueMicrotask(() => inputRef?.focus());
    } else if (rendered()) {
      setClosing(true);
      const t = setTimeout(() => {
        setRendered(false);
        setClosing(false);
      }, 180);
      onCleanup(() => clearTimeout(t));
    }
  });

  const activate = (r: Result) => {
    r.run();
    props.onClose();
  };

  const onDialogKeyDown = (e: KeyboardEvent) => {
    if (e.key === "Escape") {
      e.preventDefault();
      props.onClose();
      return;
    }
    if (e.key === "ArrowDown" || e.key === "ArrowUp") {
      e.preventDefault();
      const n = results().length;
      if (!n) return;
      const delta = e.key === "ArrowDown" ? 1 : -1;
      setHighlight((h) => (h + delta + n) % n);
      return;
    }
    if (e.key === "Enter") {
      e.preventDefault();
      const r = results()[highlight()];
      if (r) activate(r);
      return;
    }
    if (e.key === "Tab") {
      // keep focus inside the dialog
      e.preventDefault();
      const focusables: HTMLElement[] = [
        inputRef,
        ...(dialogEl?.querySelectorAll<HTMLElement>("button[data-result]") ?? []),
      ].filter(Boolean) as HTMLElement[];
      if (!focusables.length) return;
      const idx = focusables.indexOf(document.activeElement as HTMLElement);
      const next = e.shiftKey
        ? (idx - 1 + focusables.length) % focusables.length
        : (idx + 1) % focusables.length;
      focusables[next].focus();
    }
  };

  return (
    <Show when={rendered()}>
      <div
        classList={{
          "fixed inset-0 z-50 flex items-start justify-center bg-black/30 px-4 pt-[16vh] transition-opacity duration-150":
            true,
          "opacity-0": closing(),
        }}
        onMouseDown={(e) => {
          if (e.target === e.currentTarget) props.onClose();
        }}
      >
        <div
          ref={dialogEl}
          role="dialog"
          aria-modal="true"
          aria-label="Command palette"
          onKeyDown={onDialogKeyDown}
          classList={{
            "w-full max-w-[440px] overflow-hidden rounded-lg border border-scope-bg3 bg-white shadow-xl":
              true,
            "palette-closing": closing(),
            "palette-opening": !closing(),
          }}
        >
          <div class="flex items-center gap-2 border-b border-scope-bg3 px-3">
            <span class="text-scope-fg2">
              <Search size={16} />
            </span>
            <input
              ref={inputRef}
              value={query()}
              onInput={(e) => {
                setQuery(e.currentTarget.value);
                setHighlight(0);
              }}
              aria-label="Search stages and themes"
              placeholder="Type to search stages and themes…"
              class="h-11 w-full bg-transparent text-sm text-scope-fg1 placeholder:text-scope-fg3 focus:outline-none"
            />
            <kbd class="shrink-0 rounded border border-scope-bg3 bg-scope-bg2 px-1.5 py-0.5 text-[10px] text-scope-fg2">
              esc
            </kbd>
          </div>
          <ul class="max-h-[280px] overflow-y-auto p-1.5" aria-label="Results">
            <Show
              when={results().length > 0}
              fallback={
                <li class="px-3 py-6 text-center text-sm text-scope-fg2">
                  No stage or theme matched{" "}
                  <span class="font-medium text-scope-fg1">“{query()}”</span>.
                </li>
              }
            >
              <For each={results()}>
                {(r, i) => (
                  <li>
                    <button
                      type="button"
                      data-result
                      onMouseEnter={() => setHighlight(i())}
                      onFocus={() => setHighlight(i())}
                      onClick={() => activate(r)}
                      classList={{
                        "flex w-full cursor-pointer items-center gap-2 rounded-md px-3 py-2 text-left text-sm transition-colors duration-100 focus:outline-none":
                          true,
                        "bg-scope-accent text-white": highlight() === i(),
                        "text-scope-fg1": highlight() !== i(),
                      }}
                    >
                      <span
                        classList={{
                          "w-14 shrink-0 rounded-full px-2 py-0.5 text-center text-[10px] font-semibold uppercase tracking-wide":
                            true,
                          "bg-white/20 text-white": highlight() === i(),
                          "bg-scope-bg2 text-scope-fg2": highlight() !== i(),
                        }}
                      >
                        {r.kind}
                      </span>
                      <span class="min-w-0 grow truncate">{r.label}</span>
                      <span
                        classList={{
                          "shrink-0 text-[10px]": true,
                          "text-white/70": highlight() === i(),
                          "text-scope-fg3": highlight() !== i(),
                        }}
                      >
                        {r.hint}
                      </span>
                    </button>
                  </li>
                )}
              </For>
            </Show>
          </ul>
          <div class="border-t border-scope-bg3 bg-scope-bg2/60 px-3 py-1.5 text-[10px] text-scope-fg2">
            ↑↓ to navigate · Enter to activate · Esc to close
          </div>
        </div>
      </div>
    </Show>
  );
}

// tasks/frontend-creative-tools-story-docs/solution/app/src/components/features/CommandPalette.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import { useStore } from '@nanostores/react';
import { viewModeStore, undo, redo } from '@/store';
import {
  isCommandPaletteOpenStore,
  isExportDrawerOpenStore,
  isImportModalOpenStore,
  openAddScene,
} from '@/store/ui';
import { useDialogFocus } from '../common/useDialogFocus';
import { Ri, type RiIconName } from '../common/Ri';
import { clsx } from 'clsx';

interface Command {
  id: string;
  label: string;
  icon: RiIconName;
  hint?: string;
  run: () => void;
}

const COMMANDS: Command[] = [
  { id: 'add-scene', label: 'Add Scene', icon: 'add-line', run: () => openAddScene() },
  { id: 'export', label: 'Export Storyboard', icon: 'download-2-line', run: () => isExportDrawerOpenStore.set(true) },
  { id: 'import', label: 'Import Storyboard', icon: 'upload-2-line', run: () => isImportModalOpenStore.set(true) },
  { id: 'mode-tile', label: 'Switch to Tile', icon: 'apps-line', run: () => viewModeStore.set('tile') },
  { id: 'mode-list', label: 'Switch to List', icon: 'list-unordered', run: () => viewModeStore.set('list') },
  { id: 'mode-slide', label: 'Switch to Slide', icon: 'slideshow-line', run: () => viewModeStore.set('slide') },
  { id: 'mode-canvas', label: 'Switch to Canvas', icon: 'drag-move-2-line', run: () => viewModeStore.set('canvas') },
  { id: 'undo', label: 'Undo', icon: 'arrow-go-back-line', run: () => undo() },
  { id: 'redo', label: 'Redo', icon: 'arrow-go-forward-line', run: () => redo() },
];

export function CommandPalette() {
  const isOpen = useStore(isCommandPaletteOpenStore);
  const [query, setQuery] = useState('');
  const [selected, setSelected] = useState(0);
  const panelRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  const close = () => isCommandPaletteOpenStore.set(false);
  useDialogFocus(isOpen, close, panelRef, { initialFocus: inputRef });

  const filtered = useMemo(
    () => COMMANDS.filter((c) => c.label.toLowerCase().includes(query.trim().toLowerCase())),
    [query]
  );

  useEffect(() => {
    if (isOpen) {
      setQuery('');
      setSelected(0);
    }
  }, [isOpen]);

  useEffect(() => {
    setSelected(0);
  }, [query]);

  const activate = (cmd: Command) => {
    close();
    cmd.run();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[70] overflow-y-auto" role="presentation">
      <div className="flex min-h-full items-start justify-center p-4 pt-[12vh]">
        <div className="fixed inset-0 bg-gray-900/40 backdrop-blur-[2px] transition-opacity" aria-hidden="true" onClick={close} />
        <div
          ref={panelRef}
          role="dialog"
          aria-modal="true"
          aria-label="Command palette"
          tabIndex={-1}
          className="form-enter relative w-full max-w-xl overflow-hidden rounded-2xl bg-white shadow-2xl ring-1 ring-black/5"
        >
          <div className="relative border-b border-gray-100">
            <Ri name="search-line" size={17} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" />
            <label htmlFor="command-search" className="sr-only">
              Search commands
            </label>
            <input
              id="command-search"
              ref={inputRef}
              type="text"
              autoComplete="off"
              placeholder="Search commands…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'ArrowDown') {
                  e.preventDefault();
                  setSelected((s) => (filtered.length ? (s + 1) % filtered.length : 0));
                } else if (e.key === 'ArrowUp') {
                  e.preventDefault();
                  setSelected((s) => (filtered.length ? (s - 1 + filtered.length) % filtered.length : 0));
                } else if (e.key === 'Enter' && filtered[selected]) {
                  e.preventDefault();
                  activate(filtered[selected]);
                }
              }}
              className="h-14 w-full bg-transparent pl-11 pr-14 text-sm text-gray-900 outline-none placeholder:text-gray-400"
            />
            <kbd className="absolute right-4 top-1/2 -translate-y-1/2 rounded-md border border-gray-200 bg-gray-50 px-1.5 py-0.5 text-[10px] font-bold text-gray-400">
              ESC
            </kbd>
          </div>

          {filtered.length > 0 ? (
            <ul role="listbox" aria-label="Commands" className="max-h-80 overflow-y-auto p-2">
              {filtered.map((cmd, i) => (
                <li key={cmd.id} role="option" aria-selected={i === selected} id={`cmd-${cmd.id}`}>
                  <button
                    type="button"
                    onClick={() => activate(cmd)}
                    onMouseEnter={() => setSelected(i)}
                    className={clsx(
                      'flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-medium transition-colors focus:outline-none',
                      i === selected ? 'bg-yellow-50 text-gray-900 ring-1 ring-inset ring-yellow-200/70' : 'text-gray-600'
                    )}
                  >
                    <span
                      className={clsx(
                        'grid h-8 w-8 shrink-0 place-items-center rounded-lg',
                        i === selected ? 'bg-yellow-400 text-yellow-950' : 'bg-gray-100 text-gray-500'
                      )}
                    >
                      <Ri name={cmd.icon} size={16} />
                    </span>
                    {cmd.label}
                    {i === selected && <Ri name="keyboard-line" size={14} className="ml-auto text-gray-300" />}
                  </button>
                </li>
              ))}
            </ul>
          ) : (
            <p className="px-5 py-8 text-center text-sm text-gray-500">
              No commands match “{query}”. Try “scene”, “export”, or “switch”.
            </p>
          )}

          <div className="flex items-center gap-3 border-t border-gray-100 bg-[#fafaf8] px-4 py-2.5 text-[11px] font-medium text-gray-400">
            <span className="inline-flex items-center gap-1">
              <kbd className="rounded border border-gray-200 bg-white px-1 py-0.5 font-bold">↑↓</kbd> navigate
            </span>
            <span className="inline-flex items-center gap-1">
              <kbd className="rounded border border-gray-200 bg-white px-1 py-0.5 font-bold">↵</kbd> run
            </span>
            <span className="inline-flex items-center gap-1">
              <kbd className="rounded border border-gray-200 bg-white px-1 py-0.5 font-bold">esc</kbd> close
            </span>
            <span className="ml-auto hidden items-center gap-1 sm:inline-flex">
              opened with <kbd className="rounded border border-gray-200 bg-white px-1 py-0.5 font-bold">⌘K</kbd>
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}
