// tasks/frontend-productivity-clockcraft/solution/app/src/lib/components/CommandPalette.svelte
<script lang="ts">
	import { focusTrap } from "../utils/focusTrap";
	import { onMount, onDestroy } from 'svelte';
	import { uiStore, tagsStore } from '../stores';
	import { get } from 'svelte/store';

	let isOpen = $state(false);
	let query = $state('');
	let selectedIndex = $state(0);

	type Command = {
		id: string;
		title: string;
		action: () => void;
	};

	const baseCommands: Command[] = [
		{ id: 'focus-timer', title: 'Start timer focus', action: () => {
			isOpen = false;
			const timerInput = document.getElementById('timer-name');
			if (timerInput) timerInput.focus();
		}},
		{ id: 'add-manual', title: 'Add entry manually', action: () => { isOpen = false; uiStore.ui.update(s => ({...s, showManualForm: true})); setTimeout(() => { const el = document.getElementById('manual-name'); if (el) el.focus(); }, 50); } },
		{ id: 'view-history', title: 'View history', action: () => { isOpen = false; uiStore.toggleHistoryPanel(); } },
		{ id: 'export', title: 'Export session', action: () => { isOpen = false; uiStore.toggleExportDrawer(); } },
		{ id: 'import', title: 'Import session', action: () => { isOpen = false; uiStore.toggleExportDrawer(); } },
		{ id: 'filter-all', title: 'Filter: All', action: () => { isOpen = false; uiStore.setFilter('all'); } },
		{ id: 'filter-meaningful', title: 'Filter: Meaningful', action: () => { isOpen = false; uiStore.setFilter('meaningful'); } },
		{ id: 'filter-neutral', title: 'Filter: Neutral', action: () => { isOpen = false; uiStore.setFilter('neutral'); } },
		{ id: 'filter-draining', title: 'Filter: Draining', action: () => { isOpen = false; uiStore.setFilter('draining'); } },
	];

	let filteredCommands = $derived(() => {
		const tags = get(tagsStore.tags);
		const tagCommands = tags.map(t => ({
			id: `tag-${t}`,
			title: `Tag: ${t}`,
			action: () => {
				isOpen = false;
				uiStore.setSearch(t);
			}
		}));
		const allCommands = [...baseCommands, ...tagCommands];
		const q = query.toLowerCase();
		if (!q) return allCommands;
		return allCommands.filter(c => c.title.toLowerCase().includes(q));
	});

	function handleKeydown(e: KeyboardEvent) {
		if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
			e.preventDefault();
			isOpen = !isOpen;
			if (isOpen) {
				query = '';
				selectedIndex = 0;
				setTimeout(() => {
					const el = document.getElementById('palette-input');
					if (el) el.focus();
				}, 50);
			}
			return;
		}

		if (!isOpen) return;

		const commands = filteredCommands();
		if (e.key === 'Escape') {
			e.preventDefault();
			isOpen = false;
		} else if (e.key === 'ArrowDown') {
			e.preventDefault();
			selectedIndex = (selectedIndex + 1) % commands.length;
		} else if (e.key === 'ArrowUp') {
			e.preventDefault();
			selectedIndex = (selectedIndex - 1 + commands.length) % commands.length;
		} else if (e.key === 'Enter') {
			e.preventDefault();
			if (commands[selectedIndex]) {
				commands[selectedIndex].action();
			}
		}
	}

	onMount(() => {
		window.addEventListener('keydown', handleKeydown);
	});
	onDestroy(() => {
		window.removeEventListener('keydown', handleKeydown);
	});

	// Reset index when query changes
	$effect(() => {
		const _ = query;
		selectedIndex = 0;
	});
</script>

{#if isOpen}
<div class="fixed inset-0 bg-black/30 z-50 flex items-start justify-center pt-[10vh] p-4" role="presentation" onclick={() => isOpen = false}>
	<div
		class="bg-white radius-card w-full max-w-lg shadow-2xl overflow-hidden flex flex-col"
		onclick={(e) => e.stopPropagation()}
		role="dialog" use:focusTrap
		aria-label="Command palette"
		tabindex="-1"
		onkeydown={(e) => { if (e.key === 'Escape') isOpen = false; }}
	>
		<div class="border-b border-[var(--color-border)] flex items-center px-4 py-3">
			<span class="text-[var(--color-text-muted)] mr-3">🔍</span>
			<input
				id="palette-input"
				bind:value={query}
				type="text"
				placeholder="Type a command or search..."
				class="w-full bg-transparent focus:outline-none text-sm"
				aria-label="Command palette search"
				aria-autocomplete="list"
			/>
		</div>

		<div class="max-h-[60vh] overflow-y-auto p-2" role="listbox">
			{#if filteredCommands().length === 0}
				<p class="text-sm text-[var(--color-text-muted)] p-3 text-center">No matching commands.</p>
			{:else}
				{#each filteredCommands() as cmd, i}
					<button
						type="button"
						class="w-full text-left px-3 py-2 text-sm rounded flex items-center {i === selectedIndex ? 'bg-[var(--color-bg)] font-medium text-[var(--color-text-primary)]' : 'hover:bg-[var(--color-bg)] text-[var(--color-text-muted)]'}"
						role="option"
						aria-selected={i === selectedIndex}
						onclick={() => { cmd.action(); }}
						onmousemove={() => { selectedIndex = i; }}
					>
						{cmd.title}
					</button>
				{/each}
			{/if}
		</div>
	</div>
</div>
{/if}

// tasks/frontend-creative-tools-story-docs/solution/app/src/components/features/CommandPalette.tsx
import React, { useEffect, useRef, useState } from 'react';
import { useStore } from '@nanostores/react';
import { isCommandPaletteOpenStore, isExportDrawerOpenStore, showToast } from '@/store/ui';
import { viewModeStore, undo, redo } from '@/store';
import { clsx } from 'clsx';

const commands = [
    { id: 'add-scene', label: 'Add Scene', action: () => showToast('Use Add Scene button on board') },
    { id: 'export', label: 'Export storyboard', action: () => isExportDrawerOpenStore.set(true) },
    { id: 'mode-tile', label: 'Switch to Tile', action: () => viewModeStore.set('tile') },
    { id: 'mode-list', label: 'Switch to List', action: () => viewModeStore.set('list') },
    { id: 'mode-slide', label: 'Switch to Slide', action: () => viewModeStore.set('slide') },
    { id: 'undo', label: 'Undo', action: () => undo() },
    { id: 'redo', label: 'Redo', action: () => redo() }
];

export function CommandPalette() {
    const isOpen = useStore(isCommandPaletteOpenStore);
    const [search, setSearch] = useState('');
    const [selectedIndex, setSelectedIndex] = useState(0);
    const inputRef = useRef<HTMLInputElement>(null);

    const filteredCommands = commands.filter(c => c.label.toLowerCase().includes(search.toLowerCase()));

    useEffect(() => {
        if (isOpen) {
            setSearch('');
            setSelectedIndex(0);
            setTimeout(() => inputRef.current?.focus(), 50);
        }
    }, [isOpen]);

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (!isOpen) return;

            if (e.key === 'Escape') {
                isCommandPaletteOpenStore.set(false);
            } else if (e.key === 'ArrowDown') {
                e.preventDefault();
                setSelectedIndex(prev => (prev + 1) % filteredCommands.length);
            } else if (e.key === 'ArrowUp') {
                e.preventDefault();
                setSelectedIndex(prev => (prev - 1 + filteredCommands.length) % filteredCommands.length);
            } else if (e.key === 'Enter' && filteredCommands[selectedIndex]) {
                e.preventDefault();
                filteredCommands[selectedIndex].action();
                isCommandPaletteOpenStore.set(false);
            }
        };

        window.addEventListener('keydown', handleKeyDown);
        return () => window.removeEventListener('keydown', handleKeyDown);
    }, [isOpen, filteredCommands, selectedIndex]);

    if (!isOpen) return null;

    return (
        <div className="fixed inset-0 z-[80] overflow-y-auto p-4 sm:p-6 md:p-20 flex items-start justify-center" role="dialog" aria-modal="true" aria-label="Command Palette">
            <div className="fixed inset-0 bg-gray-500/50 transition-opacity" aria-hidden="true" onClick={() => isCommandPaletteOpenStore.set(false)}></div>
            <div className="relative mx-auto max-w-xl w-full transform divide-y divide-gray-100 overflow-hidden rounded-xl bg-white shadow-2xl ring-1 ring-black/5 transition-all animate-fade-in-up">
                <div className="relative">
                    <svg className="pointer-events-none absolute left-4 top-3.5 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                        <path fillRule="evenodd" d="M9 3.5a5.5 5.5 0 100 11 5.5 5.5 0 000-11zM2 9a7 7 0 1112.452 4.391l3.328 3.329a.75.75 0 11-1.06 1.06l-3.329-3.328A7 7 0 012 9z" clipRule="evenodd" />
                    </svg>
                    <input
                        ref={inputRef}
                        type="text"
                        className="h-12 w-full border-0 bg-transparent pl-11 pr-4 text-gray-900 placeholder:text-gray-400 focus:ring-0 sm:text-sm outline-none"
                        placeholder="Search commands..."
                        value={search}
                        onChange={(e) => { setSearch(e.target.value); setSelectedIndex(0); }}
                        aria-label="Search commands"
                    />
                </div>

                {filteredCommands.length > 0 ? (
                    <ul className="max-h-96 scroll-py-3 overflow-y-auto p-3" role="listbox">
                        {filteredCommands.map((command, idx) => (
                            <li
                                key={command.id}
                                className={clsx(
                                    "group flex cursor-default select-none rounded-xl p-3",
                                    idx === selectedIndex ? "bg-gray-100 text-gray-900" : "text-gray-500 hover:bg-gray-50 hover:text-gray-900"
                                )}
                                id={`option-${idx}`}
                                role="option"
                                aria-selected={idx === selectedIndex}
                                onClick={() => {
                                    command.action();
                                    isCommandPaletteOpenStore.set(false);
                                }}
                            >
                                <span className="ml-3 flex-auto truncate">{command.label}</span>
                            </li>
                        ))}
                    </ul>
                ) : (
                    <div className="p-6 text-center text-sm text-gray-500">No commands found.</div>
                )}
            </div>
        </div>
    );
}
