// tasks/frontend-data-tracking-expense-breakdown-reports/solution/app/src/app/components/export-drawer.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subject, combineLatest, takeUntil } from 'rxjs';
import type { AppState } from '../core/model';
import { buildJsonReport, buildMarkdownReport } from '../core/report';
import { TrapFocusDirective } from '../core/trap-focus.directive';
import * as A from '../store/app.actions';
import { selectBurnRate, selectFilteredTransactions, selectFilters } from '../store/app.selectors';

/**
 * Export report drawer. JSON and Markdown tabs compile live from the shared
 * store — every create/edit/delete/import is reflected the moment it happens.
 */
@Component({
  selector: 'app-export-drawer',
  imports: [TrapFocusDirective],
  template: `
    @if (open) {
      <div class="fixed inset-0 z-50 flex justify-end bg-teal-950/45" (click)="onScrim($event)">
        <aside
          appTrapFocus
          fallbackFocusId="export-report-btn"
          (escapePressed)="close()"
          role="dialog"
          aria-modal="true"
          aria-labelledby="drawer-title"
          tabindex="-1"
          class="drawer-panel flex h-full w-full max-w-xl flex-col border-l border-mint-200 bg-white shadow-2xl shadow-teal-950/30"
        >
          <header class="flex items-start justify-between gap-4 border-b border-mint-100 px-6 py-4">
            <div>
              <p class="eyebrow text-[11px] font-semibold uppercase tracking-[0.14em] text-mint-600">Shared demo report</p>
              <h2 id="drawer-title" class="font-display text-lg font-bold text-teal-950">Export report</h2>
              <p class="mt-0.5 text-xs text-ink-soft">Compiled live from the session store — {{ count }} transactions in scope.</p>
            </div>
            <button type="button" (click)="close()" aria-label="Close export drawer"
              class="flex h-10 w-10 items-center justify-center rounded-lg text-ink-soft transition-colors hover:bg-mint-100 hover:text-teal-950 focus-ring">
              <i class="pi pi-times"></i>
            </button>
          </header>

          <div class="flex items-center gap-2 border-b border-mint-100 px-6 pt-3" role="tablist" aria-label="Export format">
            <button type="button" role="tab" [attr.aria-selected]="tab === 'markdown'" (click)="setTab('markdown')"
              class="tab-btn" [class.tab-active]="tab === 'markdown'">Markdown</button>
            <button type="button" role="tab" [attr.aria-selected]="tab === 'json'" (click)="setTab('json')"
              class="tab-btn" [class.tab-active]="tab === 'json'">JSON</button>
            <span class="ml-auto pb-1 text-[11px] text-ink-soft">Updates live with every mutation</span>
          </div>

          <div class="min-h-0 flex-1 overflow-y-auto bg-mint-50 px-6 py-4">
            <pre class="print-area whitespace-pre-wrap break-words rounded-xl border border-mint-100 bg-white p-4 font-mono text-[12px] leading-relaxed text-ink"
              [class.report-prose]="tab === 'markdown'">{{ text }}</pre>
          </div>

          <footer class="flex flex-wrap items-center gap-3 border-t border-mint-100 px-6 py-4">
            @if (tab === 'markdown') {
              <button type="button" class="btn-primary" (click)="download('markdown')">
                <i class="pi pi-download mr-1.5 text-xs"></i>Download Markdown
              </button>
            } @else {
              <button type="button" class="btn-primary" (click)="download('json')">
                <i class="pi pi-download mr-1.5 text-xs"></i>Download JSON
              </button>
            }
            <button type="button" class="btn-secondary copy-btn" [class.copied]="copied" (click)="copy()">
              @if (copied) {
                <i class="pi pi-check mr-1.5 text-xs"></i>Copied
              } @else {
                <i class="pi pi-copy mr-1.5 text-xs"></i>Copy
              }
            </button>
            <span class="ml-auto text-[11px] text-ink-soft">
              {{ tab === 'markdown' ? 'expense-breakdown-report.md' : 'expense-breakdown-report.json' }}
            </span>
          </footer>
        </aside>
      </div>
    }
  `,
})
export class ExportDrawerComponent implements OnInit, OnDestroy {
  open = false;
  tab: 'markdown' | 'json' = 'markdown';
  text = '';
  count = 0;
  copied = false;

  private destroy$ = new Subject<void>();
  private copyTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(private store: Store<{ app: AppState }>) {}

  ngOnInit(): void {
    this.store.select((s) => s.app.drawerOpen).pipe(takeUntil(this.destroy$)).subscribe((open) => {
      this.open = open;
      if (open) this.copied = false;
    });
    this.store.select((s) => s.app.drawerTab).pipe(takeUntil(this.destroy$)).subscribe((tab) => (this.tab = tab));
    combineLatest([
      this.store.select(selectFilteredTransactions),
      this.store.select(selectFilters),
      this.store.select(selectBurnRate),
    ])
      .pipe(takeUntil(this.destroy$))
      .subscribe(([txs, filters, burn]) => {
        const input = {
          transactions: txs,
          filters,
          burn: { ceiling: burn.ceiling, monthToDate: burn.monthToDate, projectedMonthEnd: burn.projectedMonthEnd, over: burn.over },
        };
        this.count = input.transactions.length;
        this.text = this.tab === 'json' ? buildJsonReport(input) : buildMarkdownReport(input);
      });
  }

  setTab(tab: 'markdown' | 'json'): void {
    this.store.dispatch(A.openDrawer({ tab }));
  }

  download(format: 'markdown' | 'json'): void {
    const filename = format === 'markdown' ? 'expense-breakdown-report.md' : 'expense-breakdown-report.json';
    const mime = format === 'markdown' ? 'text/markdown' : 'application/json';
    const blob = new Blob([this.text], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 4000);
    this.store.dispatch(A.showToast({ message: `Downloading ${filename}`, nonce: Date.now() }));
  }

  async copy(): Promise<void> {
    try {
      await navigator.clipboard.writeText(this.text);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = this.text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      try {
        document.execCommand('copy');
      } finally {
        document.body.removeChild(ta);
      }
    }
    this.copied = true;
    this.store.dispatch(A.showToast({ message: 'Copied to clipboard', nonce: Date.now() }));
    if (this.copyTimer) clearTimeout(this.copyTimer);
    this.copyTimer = setTimeout(() => (this.copied = false), 2800);
  }

  close(): void {
    this.store.dispatch(A.closeDrawer());
  }

  onScrim(event: MouseEvent): void {
    if (event.target === event.currentTarget) this.close();
  }

  ngOnDestroy(): void {
    if (this.copyTimer) clearTimeout(this.copyTimer);
    this.destroy$.next();
    this.destroy$.complete();
  }
}

// tasks/frontend-creative-tools-story-docs/solution/app/src/components/features/ExportDrawer.tsx
import { useRef, useState } from 'react';
import { useStore } from '@nanostores/react';
import { scenesStore } from '@/store';
import { isExportDrawerOpenStore, exportFormatStore, showToast } from '@/store/ui';
import { compileArtifact, artifactFilename, EXPORT_FORMATS, type ExportFormat } from '@/lib/exporters';
import { useDialogFocus } from '../common/useDialogFocus';
import { Ri } from '../common/Ri';
import { clsx } from 'clsx';

export async function copyTextToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    try {
      const ta = document.createElement('textarea');
      ta.value = text;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      const ok = document.execCommand('copy');
      document.body.removeChild(ta);
      return ok;
    } catch {
      return false;
    }
  }
}

export function ExportDrawer() {
  const isOpen = useStore(isExportDrawerOpenStore);
  const format = useStore(exportFormatStore);
  const scenes = useStore(scenesStore);
  const [copied, setCopied] = useState(false);
  const panelRef = useRef<HTMLDivElement>(null);
  const closeRef = useRef<HTMLButtonElement>(null);

  const close = () => isExportDrawerOpenStore.set(false);
  useDialogFocus(isOpen, close, panelRef, { initialFocus: closeRef });

  const content = isOpen ? compileArtifact(scenes, format) : '';

  const handleCopy = async (fmt: ExportFormat = format) => {
    const ok = await copyTextToClipboard(compileArtifact(scenesStore.get(), fmt));
    setCopied(true);
    setTimeout(() => setCopied(false), 1600);
    showToast(ok ? 'Copied to Clipboard' : 'Copy Failed');
  };

  const handleDownload = () => {
    const text = compileArtifact(scenesStore.get(), format);
    const blob = new Blob([text], { type: format === 'json' ? 'application/json' : 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = artifactFilename(format);
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('Download Started');
  };

  const TAB_LABELS: Record<ExportFormat, string> = { markdown: 'Markdown', json: 'JSON', outline: 'Outline' };

  return (
    <div className={clsx('fixed inset-0 z-50 overflow-hidden', !isOpen && 'pointer-events-none')} aria-hidden={!isOpen}>
      <div
        className={clsx(
          'absolute inset-0 bg-gray-900/40 transition-opacity duration-300',
          isOpen ? 'opacity-100' : 'opacity-0'
        )}
        onClick={close}
        aria-hidden="true"
      />
      <div
        ref={panelRef}
        role="dialog"
        aria-modal="true"
        aria-label="Export storyboard"
        tabIndex={-1}
        className={clsx(
          'absolute inset-y-0 right-0 flex w-full max-w-2xl flex-col bg-white shadow-2xl',
          isOpen ? 'panel-open translate-x-0' : 'panel-closed translate-x-full'
        )}
      >
        <div className="flex items-center justify-between border-b border-gray-200 px-5 py-4">
          <div className="flex items-center gap-2.5">
            <span className="grid h-9 w-9 place-items-center rounded-xl bg-yellow-50 text-yellow-700 ring-1 ring-inset ring-yellow-200/70">
              <Ri name="download-2-line" size={18} />
            </span>
            <div>
              <h2 className="text-base font-bold tracking-tight text-gray-900">Export Storyboard</h2>
              <p className="text-xs text-gray-500">Live artifacts — regenerated from the current board</p>
            </div>
          </div>
          <button
            ref={closeRef}
            type="button"
            aria-label="Close export drawer"
            onClick={close}
            className="grid h-11 w-11 place-items-center rounded-xl text-gray-500 transition-colors hover:bg-gray-100 hover:text-gray-900 focus:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400"
          >
            <Ri name="close-line" size={20} />
          </button>
        </div>

        <div className="border-b border-gray-200 bg-[#fafaf8]" role="tablist" aria-label="Export format">
          {EXPORT_FORMATS.map((tab) => (
            <button
              key={tab}
              role="tab"
              aria-selected={format === tab}
              onClick={() => exportFormatStore.set(tab)}
              className={clsx(
                '-mb-px inline-flex h-12 items-center gap-1.5 border-b-2 px-4 text-sm font-semibold transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400',
                format === tab
                  ? 'border-yellow-500 text-yellow-700'
                  : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-800'
              )}
            >
              <Ri name={tab === 'json' ? 'file-text-line' : tab === 'markdown' ? 'file-copy-line' : 'list-unordered'} size={15} />
              {TAB_LABELS[tab]}
            </button>
          ))}
        </div>

        <div className="flex-1 overflow-y-auto bg-[#f7f7f4] p-4">
          <pre
            aria-label={`${format} preview`}
            className="h-full min-h-64 overflow-x-auto whitespace-pre-wrap rounded-xl border border-gray-200 bg-white p-4 font-mono text-[12.5px] leading-relaxed text-gray-800 shadow-inner"
          >
            {content}
          </pre>
        </div>

        <div className="flex items-center justify-end gap-2.5 border-t border-gray-200 bg-white px-5 py-4">
          <button
            type="button"
            onClick={() => handleCopy()}
            className="inline-flex h-11 items-center gap-2 rounded-xl border border-gray-300 bg-white px-4 text-sm font-semibold text-gray-700 shadow-sm transition-colors hover:border-yellow-400 hover:bg-yellow-50 hover:text-yellow-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400"
          >
            <Ri name={copied ? 'check-line' : 'file-copy-line'} size={16} className={copied ? 'text-emerald-600' : undefined} />
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button
            type="button"
            onClick={handleDownload}
            className="inline-flex h-11 items-center gap-2 rounded-xl bg-yellow-400 px-5 text-sm font-bold text-yellow-950 shadow-sm shadow-yellow-400/40 transition-all hover:bg-yellow-300 focus:outline-none focus-visible:ring-2 focus-visible:ring-yellow-500 focus-visible:ring-offset-2"
          >
            <Ri name="download-2-line" size={16} />
            Download
          </button>
        </div>
      </div>
    </div>
  );
}
