// tasks/frontend-workflow-seed-dataset-studio/solution/app/src/lib/components/Modal.svelte
<script lang="ts">
  import { tick, type Snippet } from 'svelte';
  import { X } from 'phosphor-svelte';

  let { open, title, description = '', onclose, children }: {
    open: boolean;
    title: string;
    description?: string;
    onclose: () => void;
    children: Snippet;
  } = $props();

  let panel = $state<HTMLDivElement>();
  let opener: Element | null = null;
  let mounted = $state(false);
  let visible = $state(false);
  let leaving = $state(false);

  $effect(() => {
    if (open) {
      mounted = true;
      leaving = false;
      opener = document.activeElement;
      requestAnimationFrame(() => {
        visible = true;
        tick().then(() => (panel?.querySelector<HTMLElement>('input, textarea, select, button') ?? panel)?.focus());
      });
    } else if (mounted) {
      visible = false;
      leaving = true;
      const timer = setTimeout(() => {
        mounted = false;
        leaving = false;
        if (opener instanceof HTMLElement) opener.focus();
      }, 250);
      return () => clearTimeout(timer);
    }
  });

  function keydown(event: KeyboardEvent) {
    if (!open && !visible) return;
    if (event.key === 'Escape') { event.preventDefault(); onclose(); return; }
    if (event.key !== 'Tab' || !panel) return;
    const items = [...panel.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), [tabindex="0"]')];
    if (!items.length) return;
    const first = items[0];
    const last = items[items.length - 1];
    if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
    else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
  }
</script>

<svelte:window onkeydown={keydown} />

{#if mounted}
  <div
    class="modal-backdrop"
    class:modal-open={visible && !leaving}
    class:modal-leave={leaving}
    role="presentation"
    onclick={(event) => event.target === event.currentTarget && onclose()}
  >
    <div
      bind:this={panel}
      class="modal-panel"
      class:modal-panel-open={visible && !leaving}
      class:modal-panel-leave={leaving}
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-title"
      aria-describedby={description ? 'modal-description' : undefined}
      tabindex="-1"
    >
      <header class="modal-header">
        <div>
          <h2 id="modal-title">{title}</h2>
          {#if description}<p id="modal-description">{description}</p>{/if}
        </div>
        <button class="icon-button" aria-label="Close dialog" onclick={onclose}><X size={18} aria-hidden="true" /></button>
      </header>
      <div class="modal-body">{@render children()}</div>
    </div>
  </div>
{/if}

// tasks/frontend-productivity-loopdaily/solution/app/src/components/ui/modal.tsx
import { useEffect, useId, useRef, type ReactNode } from "react";
import { createPortal } from "react-dom";

interface ModalProps {
  open: boolean;
  onClose: () => void;
  title: string;
  description?: ReactNode;
  children?: ReactNode;
  /** Element that should regain focus when the dialog closes (defaults to the opener). */
  restoreFocus?: HTMLElement | null;
}

const FOCUSABLE =
  'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';

/**
 * Accessible modal dialog: portals to <body>, traps Tab focus while open, closes
 * on Escape / overlay click, and returns focus to the invoking control on close
 * (so the Import button regains focus, not <body>).
 */
export default function Modal({
  open,
  onClose,
  title,
  description,
  children,
  restoreFocus,
}: ModalProps) {
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const restoreRef = useRef<HTMLElement | null>(null);
  const onCloseRef = useRef(onClose);
  const titleId = useId();
  const descId = useId();

  useEffect(() => {
    onCloseRef.current = onClose;
  }, [onClose]);

  useEffect(() => {
    if (!open) return;
    restoreRef.current =
      restoreFocus ?? ((document.activeElement as HTMLElement | null) || null);
    const node = dialogRef.current;
    if (!node) return;

    const focusables = () =>
      Array.from(node.querySelectorAll<HTMLElement>(FOCUSABLE)).filter((el) => {
        return el.offsetParent !== null || el === document.activeElement;
      });

    const first = focusables()[0] ?? node;
    const focusTimer = window.setTimeout(() => {
      first.focus({ preventScroll: true });
    }, 20);

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        onCloseRef.current();
        return;
      }
      if (e.key !== "Tab") return;
      const items = focusables();
      if (items.length === 0) {
        e.preventDefault();
        return;
      }
      const firstEl = items[0];
      const lastEl = items[items.length - 1];
      const active = document.activeElement as HTMLElement;
      if (e.shiftKey && (active === firstEl || active === node)) {
        e.preventDefault();
        lastEl.focus();
      } else if (!e.shiftKey && active === lastEl) {
        e.preventDefault();
        firstEl.focus();
      }
    };

    document.addEventListener("keydown", onKeyDown, true);
    return () => {
      document.removeEventListener("keydown", onKeyDown, true);
      window.clearTimeout(focusTimer);
      const restore = restoreRef.current;
      window.setTimeout(() => {
        if (restore && typeof restore.focus === "function" && document.contains(restore)) {
          restore.focus({ preventScroll: true });
        }
      }, 0);
    };
  }, [open, restoreFocus]);

  if (!open) return null;

  return createPortal(
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation">
      <div
        className="absolute inset-0 bg-[#1B2430]/40 backdrop-blur-[2px]"
        data-slot="modal-overlay"
        onClick={onClose}
        aria-hidden="true"
      />
      <div
        ref={dialogRef}
        role="dialog"
        aria-modal="true"
        aria-labelledby={titleId}
        aria-describedby={description ? descId : undefined}
        tabIndex={-1}
        className="relative z-10 w-full max-w-sm rounded-[8px] bg-[#FFFFFF] p-5 text-[#1B2430] shadow-[0_20px_50px_rgba(27,36,48,0.25)] outline-none"
        data-slot="modal-dialog"
      >
        <h2 id={titleId} className="text-lg font-bold text-[#1B2430]">
          {title}
        </h2>
        {description && (
          <p id={descId} className="mt-2 text-sm text-[#64748B]">
            {description}
          </p>
        )}
        <div className="mt-4">{children}</div>
      </div>
    </div>,
    document.body
  );
}
