// tasks-quarantine/frontend-creative-tools-exposure-control-lab/solution/app/src/components/PresetForm.vue
<template>
  <div class="bg-panel p-6 rounded-[10px] w-full max-w-md shadow-2xl max-h-[90vh] overflow-y-auto">
    <h2 class="text-lg font-medium mb-4 mt-0">{{ initialData ? 'Edit Preset' : 'Create Preset' }}</h2>

    <form @submit="onSubmit" novalidate class="flex flex-col gap-4">
      <!-- Name -->
      <div>
        <label for="preset-name" class="block text-sm font-medium mb-1">Name</label>
        <input
          id="preset-name"
          v-model="name"
          type="text"
          autocomplete="off"
          class="w-full px-3 py-2 border rounded focus-visible:outline-2 focus-visible:outline-primary bg-white text-sm"
          :class="errors.name ? 'border-red-500' : 'border-black/20'"
          :aria-invalid="errors.name ? 'true' : 'false'"
          aria-describedby="preset-name-error"
        >
        <span v-if="errors.name" id="preset-name-error" class="text-red-600 text-[10px] mt-1 block font-medium" aria-live="polite">{{ errors.name }}</span>
      </div>

      <div class="grid grid-cols-3 gap-2">
        <!-- Aperture -->
        <div>
          <label for="preset-aperture" class="block text-sm font-medium mb-1">Aperture</label>
          <input
            id="preset-aperture"
            v-model="aperture"
            type="text"
            inputmode="decimal"
            list="aperture-options"
            autocomplete="off"
            class="w-full px-2 py-2 border rounded focus-visible:outline-2 focus-visible:outline-primary bg-white text-sm"
            :class="errors.aperture ? 'border-red-500' : 'border-black/20'"
            :aria-invalid="errors.aperture ? 'true' : 'false'"
            aria-describedby="preset-aperture-error"
          >
          <datalist id="aperture-options">
            <option v-for="stop in apertureStops" :key="stop" :value="'f/' + stop"></option>
          </datalist>
          <span v-if="errors.aperture" id="preset-aperture-error" class="text-red-600 text-[10px] mt-1 block font-medium" aria-live="polite">{{ errors.aperture }}</span>
        </div>

        <!-- Shutter -->
        <div>
          <label for="preset-shutter" class="block text-sm font-medium mb-1">Shutter</label>
          <input
            id="preset-shutter"
            v-model="shutter"
            type="text"
            inputmode="numeric"
            list="shutter-options"
            autocomplete="off"
            class="w-full px-2 py-2 border rounded focus-visible:outline-2 focus-visible:outline-primary bg-white text-sm"
            :class="errors.shutter ? 'border-red-500' : 'border-black/20'"
            :aria-invalid="errors.shutter ? 'true' : 'false'"
            aria-describedby="preset-shutter-error"
          >
          <datalist id="shutter-options">
            <option v-for="stop in shutterStops" :key="stop" :value="'1/' + stop"></option>
          </datalist>
          <span v-if="errors.shutter" id="preset-shutter-error" class="text-red-600 text-[10px] mt-1 block font-medium" aria-live="polite">{{ errors.shutter }}</span>
        </div>

        <!-- ISO -->
        <div>
          <label for="preset-iso" class="block text-sm font-medium mb-1">ISO</label>
          <input
            id="preset-iso"
            v-model="iso"
            type="text"
            inputmode="numeric"
            list="iso-options"
            autocomplete="off"
            class="w-full px-2 py-2 border rounded focus-visible:outline-2 focus-visible:outline-primary bg-white text-sm"
            :class="errors.iso ? 'border-red-500' : 'border-black/20'"
            :aria-invalid="errors.iso ? 'true' : 'false'"
            aria-describedby="preset-iso-error"
          >
          <datalist id="iso-options">
            <option v-for="stop in isoStops" :key="stop" :value="String(stop)"></option>
          </datalist>
          <span v-if="errors.iso" id="preset-iso-error" class="text-red-600 text-[10px] mt-1 block font-medium" aria-live="polite">{{ errors.iso }}</span>
        </div>
      </div>

      <!-- LookTag -->
      <div>
        <label for="preset-looktag" class="block text-sm font-medium mb-1">Look Tag</label>
        <input
          id="preset-looktag"
          v-model="lookTag"
          type="text"
          list="looktag-options"
          autocomplete="off"
          class="w-full px-3 py-2 border rounded focus-visible:outline-2 focus-visible:outline-primary bg-white text-sm capitalize"
          :class="errors.lookTag ? 'border-red-500' : 'border-black/20'"
          :aria-invalid="errors.lookTag ? 'true' : 'false'"
          aria-describedby="preset-looktag-error"
        >
        <datalist id="looktag-options">
          <option v-for="tag in lookTags" :key="tag" :value="tag"></option>
        </datalist>
        <span v-if="errors.lookTag" id="preset-looktag-error" class="text-red-600 text-[10px] mt-1 block font-medium" aria-live="polite">{{ errors.lookTag }}</span>
      </div>

      <div class="flex justify-end gap-2 mt-2">
        <button type="button" class="px-4 py-2 rounded bg-black/10 hover:bg-black/20 text-sm font-medium transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary" @click="$emit('cancel')">Cancel</button>
        <button
          type="submit"
          class="px-4 py-2 rounded bg-primary hover:bg-red-600 text-white text-sm font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
          :disabled="!meta.valid"
        >
          {{ initialData ? 'Save preset' : 'Create preset' }}
        </button>
      </div>
    </form>
  </div>
</template>

<script setup>
import { useForm, useField } from 'vee-validate'
import { toTypedSchema } from '@vee-validate/zod'
import { z } from 'zod'
import { useStore } from '../store.js'
import {
  apertureStops, shutterStops, isoStops, lookTags,
  APERTURE_LIST_TEXT, SHUTTER_LIST_TEXT, ISO_LIST_TEXT
} from '../domain.js'

const props = defineProps({
  initialData: {
    type: Object,
    default: null
  }
})
const emit = defineEmits(['save', 'cancel'])
const store = useStore()

// The create/edit form accepts typed input (with datalist suggestions) so an
// out-of-list stop or lookTag can be attempted and rejected with a visible
// inline error, while the submitted record is coerced back to the strict
// ExposurePreset API shape (numbers for stops, lowercase enum lookTag).
function parseStopInput(val) {
  if (typeof val !== 'string') return val
  const trimmed = val.trim()
  if (trimmed === '') return val
  const numeric = Number(trimmed.replace(/^f\/|^1\//i, ''))
  return Number.isNaN(numeric) ? val : numeric
}

const FormSchema = z.object({
  name: z.string()
    .min(1, 'Name is required. Enter a name of 1 to 40 characters.')
    .max(40, 'Name is longer than 40 characters. Shorten it to 40 or fewer.'),
  aperture: z.preprocess(parseStopInput,
    z.number({ invalid_type_error: `Aperture must be a number. Pick one of ${APERTURE_LIST_TEXT}.` })
      .refine(val => apertureStops.includes(val), val => ({ message: `Aperture ${val} is not a supported stop. Pick one of ${APERTURE_LIST_TEXT}.` }))),
  shutter: z.preprocess(parseStopInput,
    z.number({ invalid_type_error: `Shutter must be a number. Pick one of ${SHUTTER_LIST_TEXT}.` })
      .refine(val => shutterStops.includes(val), val => ({ message: `Shutter ${val} is not a supported stop. Pick one of ${SHUTTER_LIST_TEXT}.` }))),
  iso: z.preprocess(parseStopInput,
    z.number({ invalid_type_error: `ISO must be a number. Pick one of ${ISO_LIST_TEXT}.` })
      .refine(val => isoStops.includes(val), val => ({ message: `ISO ${val} is not a supported stop. Pick one of ${ISO_LIST_TEXT}.` }))),
  lookTag: z.preprocess(
    val => typeof val === 'string' ? val.trim().toLowerCase() : val,
    z.enum(['soft', 'crisp', 'grainy', 'night', 'daylight', 'cinematic'], {
      errorMap: () => ({ message: 'Look tag must be one of soft, crisp, grainy, night, daylight, cinematic.' })
    })),
  favorite: z.boolean().default(false).optional()
}).refine(
  data => {
    if (props.initialData && data.name === props.initialData.name) return true
    return !store.presets.some(p => p.name === data.name)
  },
  { message: 'Name must be unique — another preset already uses it. Choose a different name.', path: ['name'] }
)

const { handleSubmit, errors, meta } = useForm({
  validationSchema: toTypedSchema(FormSchema),
  initialValues: props.initialData ? { ...props.initialData } : {
    name: '',
    aperture: store.aperture,
    shutter: store.shutter,
    iso: store.iso,
    lookTag: 'cinematic',
    favorite: false
  },
  mode: 'eager'
})

const { value: name } = useField('name')
const { value: aperture } = useField('aperture')
const { value: shutter } = useField('shutter')
const { value: iso } = useField('iso')
const { value: lookTag } = useField('lookTag')
// Not bound to a visible input -- registering it keeps an edited preset's
// existing favorite flag in the submitted payload instead of dropping it
// (favorite is only ever changed via the star toggle in PresetsView).
const { value: favorite } = useField('favorite')

const onSubmit = handleSubmit(values => {
  emit('save', values)
})
</script>

// tasks/frontend-creative-tools-camera-exposure/solution/app/src/PresetForm.jsx
import { createSignal, For, Show } from "solid-js";
import { createForm } from "@tanstack/solid-form";
import { z } from "zod";
import { store, APERTURE_STOPS, SHUTTER_STOPS, ISO_STOPS, createPreset, updatePreset } from "./store";

const schema = z.object({
  name: z.string().trim().min(1, "required — enter a 1–64 character name").max(64, "must be 64 characters or fewer"),
  aperture: z.number().refine((v) => APERTURE_STOPS.includes(v), "must be a supported f-stop"),
  shutter: z.number().refine((v) => SHUTTER_STOPS.includes(v), "must be a supported shutter speed"),
  iso: z.number().refine((v) => ISO_STOPS.includes(v), "must be a supported ISO"),
  lookTag: z.string().trim().min(1, "required — add a 1–32 character look tag").max(32, "must be 32 characters or fewer"),
  favorite: z.boolean().default(false),
});

const FIELD_LABEL = { name: "Name", aperture: "Aperture", shutter: "Speed", iso: "ISO", lookTag: "Look tag" };

export default function PresetForm(props) {
  const isEdit = () => !!props.preset;
  const [submitting, setSubmitting] = createSignal(false);

  const form = createForm(() => ({
    defaultValues: isEdit() ? {
      name: props.preset.name, aperture: props.preset.aperture, shutter: props.preset.shutter,
      iso: props.preset.iso, lookTag: props.preset.lookTag, favorite: props.preset.favorite,
    } : {
      name: "", aperture: store.aperture, shutter: store.shutter, iso: store.iso, lookTag: "", favorite: false,
    },
    validators: { onChange: schema, onSubmit: schema },
    onSubmit: async ({ value }) => {
      if (submitting()) return;
      setSubmitting(true);
      const data = schema.parse(value);
      if (isEdit()) updatePreset(props.preset.id, data);
      else createPreset(data);
      props.onClose();
    },
  }));

  const Err = (field, label) => (
    <Show when={field().state.meta.errors.length}>
      <span class="val-enter text-[11px] text-primary-soft block mt-0.5" role="alert">{label}: {field().state.meta.errors[0]}</span>
    </Show>
  );

  return (
    <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4" role="dialog" aria-modal="true" aria-label={isEdit() ? "Edit preset" : "Create preset"}>
      <div class="bg-ink border border-white/15 rounded-2xl shadow-2xl w-full max-w-md p-6 pop-in">
        <h2 class="font-display text-xl uppercase tracking-widest mb-5">{isEdit() ? "Edit preset" : "Save preset"}</h2>
        <form class="space-y-3" onSubmit={(e) => { e.preventDefault(); e.stopPropagation(); form.handleSubmit(); }}>
          <form.Field name="name">
            {(f) => (
              <div>
                <label for="pf-name" class="font-display text-[11px] uppercase tracking-wider text-white/60">Name</label>
                <input id="pf-name" value={f().state.value} onBlur={f().handleBlur} onInput={(e) => f().handleChange(e.target.value)} aria-invalid={!!f().state.meta.errors.length} aria-describedby="pf-name-err" class="w-full bg-black/40 border border-white/15 rounded px-2 py-1.5 text-sm text-white" placeholder="e.g. Golden Hour Soft" />
                <span id="pf-name-err">{Err(f, FIELD_LABEL.name)}</span>
              </div>
            )}
          </form.Field>
          <div class="grid grid-cols-3 gap-3">
            <form.Field name="aperture">
              {(f) => (
                <div>
                  <label for="pf-ap" class="font-display text-[11px] uppercase tracking-wider text-white/60">Aperture</label>
                  <select id="pf-ap" value={f().state.value} onBlur={f().handleBlur} onChange={(e) => f().handleChange(Number(e.target.value))} class="w-full bg-black/40 border border-white/15 rounded px-1 py-1.5 text-sm text-white">
                    <For each={APERTURE_STOPS}>{(v) => <option value={v}>f/{v}</option>}</For>
                  </select>
                  {Err(f, FIELD_LABEL.aperture)}
                </div>
              )}
            </form.Field>
            <form.Field name="shutter">
              {(f) => (
                <div>
                  <label for="pf-sh" class="font-display text-[11px] uppercase tracking-wider text-white/60">Speed</label>
                  <select id="pf-sh" value={f().state.value} onBlur={f().handleBlur} onChange={(e) => f().handleChange(Number(e.target.value))} class="w-full bg-black/40 border border-white/15 rounded px-1 py-1.5 text-sm text-white">
                    <For each={SHUTTER_STOPS}>{(v) => <option value={v}>1/{v}</option>}</For>
                  </select>
                  {Err(f, FIELD_LABEL.shutter)}
                </div>
              )}
            </form.Field>
            <form.Field name="iso">
              {(f) => (
                <div>
                  <label for="pf-iso" class="font-display text-[11px] uppercase tracking-wider text-white/60">ISO</label>
                  <select id="pf-iso" value={f().state.value} onBlur={f().handleBlur} onChange={(e) => f().handleChange(Number(e.target.value))} class="w-full bg-black/40 border border-white/15 rounded px-1 py-1.5 text-sm text-white">
                    <For each={ISO_STOPS}>{(v) => <option value={v}>{v}</option>}</For>
                  </select>
                  {Err(f, FIELD_LABEL.iso)}
                </div>
              )}
            </form.Field>
          </div>
          <form.Field name="lookTag">
            {(f) => (
              <div>
                <label for="pf-tag" class="font-display text-[11px] uppercase tracking-wider text-white/60">Look tag</label>
                <input id="pf-tag" value={f().state.value} onBlur={f().handleBlur} onInput={(e) => f().handleChange(e.target.value)} aria-invalid={!!f().state.meta.errors.length} aria-describedby="pf-tag-err" class="w-full bg-black/40 border border-white/15 rounded px-2 py-1.5 text-sm text-white" placeholder="e.g. Portrait" />
                <span id="pf-tag-err">{Err(f, FIELD_LABEL.lookTag)}</span>
              </div>
            )}
          </form.Field>
          <form.Field name="favorite">
            {(f) => (
              <label class="flex items-center gap-2 text-sm text-white/80">
                <input type="checkbox" checked={f().state.value} onChange={(e) => f().handleChange(e.target.checked)} class="w-4 h-4 accent-primary" />
                Mark as favorite
              </label>
            )}
          </form.Field>
          <div class="flex justify-end gap-3 pt-3 border-t border-white/10">
            <button type="button" onClick={props.onClose} class="hover-wash rounded px-4 py-2 text-sm text-white/70">Cancel</button>
            <form.Subscribe selector={(s) => s.canSubmit}>
              {(canSubmit) => (
                <button type="submit" disabled={!canSubmit() || submitting()} class="hover-wash rounded px-5 py-2 bg-primary hover:bg-primary-soft text-white text-sm font-display tracking-wide disabled:opacity-40 disabled:cursor-not-allowed">
                  {isEdit() ? "Update preset" : "Save preset"}
                </button>
              )}
            </form.Subscribe>
          </div>
        </form>
      </div>
    </div>
  );
}
